Repository elastic/connectors, pull requests merged in 2022-12, with the labels that each got.

#218 Add pagination and only return supported connectors
  connectors/byoc.py
  connectors/runner.py
  connectors/tests/test_byoc.py
  connectors/tests/test_runner.py
Labels: auto-backport, 8.7, v8.7.0.0

#221 [MySQL] Add Generic retry that loops over all the server calls.
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.7.0.0

#217 dont run pyspy on darwin
  connectors/tests/ftest.sh
Labels: v8.7.0.0

#229 Remove pipeline check
  connectors/byoc.py
  connectors/utils.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#227 Remove async close in MySQL test case.
  connectors/sources/tests/test_mysql.py
Labels: v8.7.0.0

#214 Plug the ingest attachment
  connectors/sources/directory.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/tests/test_directory.py
  connectors/sources/tests/test_network_drive.py
  connectors/sources/tests/test_s3.py
  connectors/tests/test_utils.py
  connectors/utils.py
  scripts/verify.py
Labels: v8.7.0.0

#234 [8.6] Fix makefile errors (#233)
  Makefile
Labels: backport

#231 Small cleanups
  connectors/byoc.py
  connectors/sources/directory.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/utils.py
Labels: v8.7.0.0

#238 Disabling this workflow
  .github/workflows/add-to-repo.yml
Labels: auto-backport, v8.7.0.0

#237 clean up spurious output and fix mysql test
  connectors/conftest.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_network_drive.py
  connectors/sources/tests/test_s3.py
Labels: v8.7.0.0

#226 Refactor service layout
  connectors/cli.py
  connectors/services/__init__.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/config.yml
  connectors/tests/config_2.yml
  connectors/tests/config_https.yml
  connectors/tests/config_mem.yml
  connectors/tests/fake_sources.py
  connectors/tests/memconfig.yml
  connectors/tests/test_cli.py
  connectors/tests/test_sync.py
  connectors/utils.py
Labels: v8.7.0.0, refactor

#235 Added the `--uvloop` option
  connectors/cli.py
  connectors/utils.py
  requirements/framework.txt
  setup.py
Labels: v8.7.0.0

#240 Add custom certificate authority
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.7.0.0

#245 Tweak perf8 options
  connectors/services/sync.py
  connectors/sources/tests/fixtures/mysql/loadsample.py
  connectors/sources/tests/fixtures/mysql/remove.py
  connectors/tests/ftest.sh
Labels: auto-backport, v8.6.0, v8.7.0.0

#215 [new connector] Google Cloud Storage
  MANIFEST.in
  config.yml
  connectors/sources/gcs.py
  connectors/sources/tests/fixtures/gcs/Makefile
  connectors/sources/tests/fixtures/gcs/docker-compose.yml
  connectors/sources/tests/fixtures/gcs/gcs_dummy_cert.pem
  connectors/sources/tests/fixtures/gcs/loadsample.py
  connectors/sources/tests/fixtures/gcs/mocked_http_responses.json
  connectors/sources/tests/fixtures/gcs/mockerserver.properties
  connectors/sources/tests/fixtures/gcs/prerequisites.py
  connectors/sources/tests/fixtures/gcs/remove.py
  connectors/sources/tests/fixtures/gcs/service_account_dummy_cert.pem
  connectors/sources/tests/test_gcs.py
  connectors/tests/ftest.sh
  requirements/framework.txt
Labels: v8.7.0.0

#242 Move get_docs method to ESIndex class
  connectors/byoc.py
  connectors/es.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_es.py
Labels: v8.7.0.0

#243 merge the headers
  connectors/services/base.py
  connectors/tests/entsearch.yml
  connectors/tests/test_sync.py
  connectors/utils.py
Labels: v8.5.0, auto-backport, v8.6.0

#249 [8.6] Merge the headers from `elasticsearch:headers` (#243)
  connectors/runner.py
  connectors/tests/entsearch.yml
  connectors/tests/test_runner.py
  connectors/utils.py
Labels: backport

#248 [8.5] Merge the headers from `elasticsearch:headers` (#243)
  connectors/runner.py
  connectors/tests/entsearch.yml
  connectors/tests/test_runner.py
  connectors/utils.py
Labels: backport

#251 Add rule for flake8 to enforce imports order + make autoformat now sorts imports
  .isort.cfg
  Makefile
  connectors/byoc.py
  connectors/byoei.py
  connectors/cli.py
  connectors/conftest.py
  connectors/es/__init__.py
  connectors/es/settings.py
  connectors/kibana.py
  connectors/logger.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/mongo.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/tests/fixtures/gcs/loadsample.py
  connectors/sources/tests/fixtures/mysql/loadsample.py
  connectors/sources/tests/fixtures/mysql/remove.py
  connectors/sources/tests/fixtures/network_drive/loadsample.py
  connectors/sources/tests/fixtures/s3/load_storage.py
  connectors/sources/tests/fixtures/s3/remove.py
  connectors/sources/tests/test_directory.py
  connectors/sources/tests/test_gcs.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_network_drive.py
  connectors/sources/tests/test_s3.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_cli.py
  connectors/tests/test_es_index.py
  connectors/tests/test_es_settings.py
  connectors/tests/test_kibana.py
  connectors/tests/test_logger.py
  connectors/tests/test_source.py
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
  connectors/utils.py
  requirements/tests.txt
  scripts/verify.py
  setup.py
Labels: auto-backport, v8.7.0.0

#253 fixed an intermittent+leftover from a merge
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
Labels: auto-backport, v8.6.0

#255 more cleanups
  connectors/sources/tests/test_gcs.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#257 moved ESCLient to connectors.es
  .isort.cfg
  connectors/byoei.py
  connectors/es/__init__.py
  connectors/es/client.py
  connectors/es/index.py
  connectors/tests/test_es_client.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.7.0.0

#244 docs: fix typo
  docs/DEVELOPING.md
Labels: auto-backport, v8.7.0.0

#258 Implement the nightly functional test
  .buildkite/nightly.yml
  .buildkite/run_nigthly.sh
  connectors/sources/tests/fixtures/README.md
  connectors/sources/tests/fixtures/fixture.py
  connectors/sources/tests/fixtures/gcs/Makefile
  connectors/sources/tests/fixtures/gcs/fixture.py
  connectors/sources/tests/fixtures/gcs/prerequisites.py
  connectors/sources/tests/fixtures/gcs/remove.py
  connectors/sources/tests/fixtures/gcs/requirements.txt
  connectors/sources/tests/fixtures/mysql/Makefile
  connectors/sources/tests/fixtures/mysql/fixture.py
  connectors/sources/tests/fixtures/mysql/remove.py
  connectors/sources/tests/fixtures/mysql/requirements.txt
  connectors/sources/tests/fixtures/network_drive/Makefile
  connectors/sources/tests/fixtures/network_drive/docker-compose.yml
  connectors/sources/tests/fixtures/network_drive/fixture.py
  connectors/sources/tests/fixtures/network_drive/remove.py
  connectors/sources/tests/fixtures/network_drive/requirements.txt
  connectors/sources/tests/fixtures/s3/Makefile
  connectors/sources/tests/fixtures/s3/docker-compose.yml
  connectors/sources/tests/fixtures/s3/fixture.py
  connectors/sources/tests/fixtures/s3/remove.py
  connectors/sources/tests/fixtures/s3/requirements.txt
  connectors/tests/ftest.sh
Labels: auto-backport, v8.7.0.0

#261 Extract pre-flight check to a function + rearrange arguments in _run function
  connectors/services/sync.py
Labels: v8.7.0.0

#262 Fix e2e in the CI for AWS
  connectors/sources/s3.py
  connectors/sources/tests/fixtures/s3/.env
  connectors/sources/tests/fixtures/s3/fixture.py
  connectors/tests/ftest.sh
Labels: auto-backport, v8.7.0.0

#264 Fixes the GCS e2e nightly test
  connectors/sources/gcs.py
  connectors/sources/tests/fixtures/gcs/.env
  connectors/sources/tests/fixtures/gcs/fixture.py
Labels: v8.7.0.0

#259 Add BasicRule class matching documents against a basic rule
  connectors/filtering/__init__.py
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
  requirements/framework.txt
Labels: auto-backport, v8.7.0.0

#265 [Filtering] Add BasicRule parse method
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
Labels: auto-backport, v8.7.0.0

#268 [Filtering] Validate basic rules against a JSON schema
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
  requirements/framework.txt
Labels: auto-backport, v8.7.0.0
