Repository elastic/connectors, pull requests merged in 2022-11, with the labels that each got.

#160 Update elasticsearch version to 8.5.0
  requirements.txt
Labels: v8.6.0.4

#158 [8.5] removed vendored version and downgraded pytz (#134)
  connectors/quartz.py
  connectors/utils.py
  requirements.txt
Labels: backport

#156 [8.5] Fix status check (#128)
  connectors/byoc.py
  connectors/conftest.py
  connectors/runner.py
  connectors/sources/tests/test_aws.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/test_byoc.py
  connectors/tests/test_runner.py
  connectors/utils.py
Labels: backport

#157 [8.5] Fix memory bloat issue on large text and dbs (#100)
  config.yml
  connectors/byoc.py
  connectors/byoei.py
  connectors/runner.py
  connectors/sources/mysql.py
  connectors/sources/tests/fixtures/mysql/loadsample.py
  connectors/sources/tests/support.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/ftest.sh
  connectors/tests/test_byoei.py
  connectors/tests/test_runner.py
  connectors/utils.py
  docs/CONFIG.md
Labels: backport

#150 do not add a new ts if the backend provides it
  connectors/byoei.py
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/config.yml
  connectors/tests/test_byoei.py
  connectors/tests/test_runner.py
Labels: v8.5.0, auto-backport, v8.6.0.4

#161 Update job status
  connectors/byoc.py
Labels: v8.6.0, v8.6.0.4

#162 [8.5] memory info utility (#126)
  .buildkite/run_dockerized_test.sh
  config.yml
  connectors/byoei.py
  connectors/runner.py
  connectors/tests/config_mem.yml
  connectors/tests/test_runner.py
  connectors/utils.py
  requirements.txt
Labels: backport

#164 [8.5] Remove the two-phase for files (#148)
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: backport

#163 [8.5] do not add a new ts if the backend provides it (#150)
  connectors/byoei.py
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/config.yml
  connectors/tests/test_byoei.py
  connectors/tests/test_runner.py
Labels: backport

#165 [8.5] limit the bulk queue and request in memory (#147)
  config.yml
  connectors/byoc.py
  connectors/byoei.py
  connectors/tests/memconfig.yml
  connectors/tests/test_runner.py
  connectors/tests/test_utils.py
  connectors/utils.py
  docs/CONFIG.md
Labels: backport

#169 speed up the memory lookups by doing a single call per item
  connectors/byoei.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: enhancement, v8.6.0.4

#12 [new connector] Network Drive
  config.yml
  connectors/sources/network_drive.py
  connectors/sources/tests/fixtures/network_drive/Makefile
  connectors/sources/tests/fixtures/network_drive/docker-compose.yml
  connectors/sources/tests/fixtures/network_drive/loadsample.py
  connectors/sources/tests/fixtures/network_drive/remove.py
  connectors/sources/tests/test_network_drive.py
  requirements.txt
Labels: enhancement, v8.6.0

#74 Populate service_type and configuration for custom connectors
  connectors/byoc.py
  connectors/runner.py
  connectors/source.py
  connectors/tests/test_byoc.py
  connectors/tests/test_runner.py
  connectors/tests/test_source.py
Labels: v8.5.0, auto-backport, v8.6.0

#179 [Network Drive] Increase number of files for ftest
  connectors/sources/tests/fixtures/network_drive/loadsample.py
Labels: v8.6.0.4

#181 added a pr-bot definition
  .buildkite/pull-requests.json
Labels: v8.6.0.4

#183 Update pull-requests.json
  .buildkite/pull-requests.json
Labels: auto-backport, v8.6.0.4

#175 Shorter MySQL config labels
  connectors/sources/mysql.py
Labels: v8.6.0.4

#174 Added `max_concurrency` for bulk requests
  config.yml
  connectors/byoc.py
  connectors/byoei.py
  connectors/tests/config.yml
  connectors/tests/config_2.yml
  connectors/tests/config_https.yml
  connectors/tests/config_mem.yml
  connectors/tests/memconfig.yml
  connectors/tests/test_byoc.py
  connectors/tests/test_source.py
  connectors/utils.py
  docs/CONFIG.md
Labels: v8.6.0.4

#184 Surface `analysis_icu` and `language_code` in config
  config.yml
  connectors/byoc.py
  connectors/tests/config.yml
  connectors/tests/test_byoc.py
  docs/CONFIG.md
Labels: v8.6.0.4

#152 Add retry mechanism
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: mysql, v8.5.0, auto-backport, v8.6.0.4

#193 Bump version to 8.7
  .backportrc.json
  connectors/VERSION
Labels: v8.7.0

#195 [8.6] starting the next release
  connectors/VERSION
Labels: v8.6.0

#151 [new connector] AWS S3
  config.yml
  connectors/sources/aws.py
  connectors/sources/s3.py
  connectors/sources/tests/fixtures/s3/Makefile
  connectors/sources/tests/fixtures/s3/docker-compose.yml
  connectors/sources/tests/fixtures/s3/load_storage.py
  connectors/sources/tests/fixtures/s3/remove.py
  connectors/sources/tests/test_aws.py
  connectors/sources/tests/test_s3.py
Labels: enhancement, v8.6.0.4

#196 Update RELEASING.md
  docs/RELEASING.md
Labels: v8.7.0.0

#173 [8.5] Populate service_type and configuration for custom connectors (#74)
  connectors/byoc.py
  connectors/runner.py
  connectors/source.py
  connectors/tests/test_byoc.py
  connectors/tests/test_runner.py
  connectors/tests/test_source.py
Labels: backport, v8.5.2

#199 [MySQL] Fields and Database validation
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#203 Bump version
  connectors/VERSION
Labels: v8.5.0

#204 avoid creating source class if not needed
  connectors/byoc.py
  connectors/runner.py
  connectors/source.py
  connectors/tests/test_byoc.py
  connectors/tests/test_runner.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#210 fix MANIFEST
  MANIFEST.in
Labels: auto-backport, v8.6.0, v8.7.0.0

#198 Add trigger_method to job
  connectors/byoc.py
  connectors/sources/mysql.py
Labels: auto-backport, v8.6.0, 8.7

#191 Add perf8 integration
  Makefile
  connectors/tests/ftest.sh
  requirements/framework.txt
  requirements/tests.txt
Labels: v8.7.0

#216 warning cleanups
  connectors/byoc.py
  connectors/sources/mysql.py
  connectors/sources/s3.py
  connectors/sources/tests/test_s3.py
Labels: auto-backport, v8.6.0, v8.7.0.0
