Repository elastic/connectors, pull requests merged in 2023-02, with the labels that each got.

#409 Fix linters for new version of black
  connectors/byoc.py
  connectors/source.py
  connectors/sources/mysql.py
  connectors/sources/tests/test_abs.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_network_drive.py
  connectors/sources/tests/test_oracle.py
  connectors/sources/tests/test_postgresql.py
  connectors/sources/tests/test_s3.py
  connectors/tests/test_validation.py
  setup.py
Labels: auto-backport, v8.7.0.0

#411 Fix linters on 8.5 branch
  connectors/sources/aws.py
  connectors/sources/mysql.py
  connectors/sources/tests/test_aws.py
  connectors/sources/tests/test_mongo.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_runner.py
  connectors/tests/test_source.py
  connectors/tests/test_utils.py
Labels: auto-backport, v8.7.0.0

#219 Job Cleanup task
  config.yml
  connectors/byoc.py
  connectors/cli.py
  connectors/es/client.py
  connectors/es/index.py
  connectors/services/job_cleanup.py
  connectors/tests/test_byoc.py
  connectors/tests/test_job_cleanup.py
  docs/CONFIG.md
Labels: v8.7.0, v8.7.0.0

#416 [Refactoring] Remove duplicate setup code/AsyncIter in test_mysql
  connectors/sources/tests/test_mysql.py
  connectors/tests/commons.py
Labels: auto-backport, v8.7.0.0

#415 [Testing] Read in filtering.json for functional tests
  connectors/kibana.py
  connectors/sources/tests/fixtures/mysql/filtering.json
  connectors/tests/ftest.sh
  connectors/tests/test_kibana.py
Labels: auto-backport, v8.7.0.0

#417 Don't delete content indices of existing connectors
  connectors/services/job_cleanup.py
  connectors/tests/test_job_cleanup.py
Labels: v8.7.0, v8.7.0.0

#382 Add logic to allow running a new job if connector was suspended before
  connectors/byoc.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
Labels: release_note, v8.7.0.0

#420 [Refactoring] PascalCase class names in test
  connectors/sources/tests/test_generic_database.py
Labels: auto-backport, v8.7.0.0

#412 [Docs] Documentation for implementing sync rules
  docs/CONTRIBUTING.md
Labels: auto-backport, v8.7.0.0

#419 [Refactoring] Remove duplicate AsyncIter class
  connectors/sources/tests/test_abs.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_oracle.py
  connectors/sources/tests/test_postgresql.py
  connectors/tests/commons.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_job_cleanup.py
Labels: auto-backport, v8.7.0.0

#376 Mark jobs that were running during service termination as Suspended
  connectors/byoc.py
  connectors/cli.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_sync.py
Labels: release_note, v8.7.0.0

#285 Remove --one-sync and --sync-now flags
  connectors/byoc.py
  connectors/cli.py
  connectors/kibana.py
  connectors/services/sync.py
  connectors/sources/tests/fixtures/fixture.py
  connectors/tests/ftest.sh
  connectors/tests/test_sync.py
Labels: v8.7.0

#413 Add name and service_type method to data source classes
  connectors/cli.py
  connectors/source.py
  connectors/sources/abs.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/s3.py
  connectors/tests/fake_sources.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#423 Adds docker
  .buildkite/nightly.yml
  .buildkite/publish_docker.sh
  Dockerfile
  Makefile
  docs/docker.md
Labels: v8.7.0.0

#407 improved the speed comparison to reduce noise
  connectors/tests/test_utils.py
Labels: v8.7.0.0

#425 fix filtering loading
  connectors/kibana.py
Labels: auto-backport, v8.7.0.0

#427 [8.6] Fix e2e in the CI for AWS (#262)
  connectors/sources/s3.py
  connectors/sources/tests/fixtures/s3/.env
  connectors/sources/tests/fixtures/s3/fixture.py
  connectors/tests/ftest.sh
Labels: backport

#429 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: v8.7.0.0

#432 Update source.py
  connectors/cli.py
  connectors/source.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#438 [Docs] Fix commands in docker docs
  docs/DOCKER.md
Labels: auto-backport, v8.7.0.0

#431 move log from method _sync_done to finally block
  connectors/byoc.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#436 Change create_and_run_service to make it more reliable
  connectors/tests/test_sync.py
Labels: auto-backport, v8.7.0.0

#439 Clean up config field names for all sources
  connectors/sources/abs.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/generic_database.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#430 Use None instead of empty string for datetime field
  connectors/kibana.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#441 remove oracle from the nighlty
  .buildkite/nightly.yml
Labels: v8.7.0.0

#422 Make the directory connector a full connector
  .buildkite/nightly.yml
  config.yml
  connectors/kibana.py
  connectors/sources/directory.py
  connectors/sources/tests/fixtures/dir/.env
  connectors/sources/tests/fixtures/dir/docker-compose.yml
  connectors/sources/tests/fixtures/dir/fixture.py
  connectors/sources/tests/test_directory.py
  connectors/tests/ftest.sh
  scripts/verify.py
Labels: v8.7.0.0

#445 [Refactoring] Move e2str to utils to avoid cyclic imports
  connectors/byoc.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.7.0.0

#442 Use active filter in async_bulk
  connectors/byoc.py
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#449 Add str2e function
  connectors/byoc.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#440 Implement Pipeline as a derived class of UserDict
  connectors/byoc.py
  connectors/byoei.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#443 Update SyncJobIndex
  connectors/byoc.py
  connectors/es/index.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#434 Update ConnectorIndex
  connectors/byoc.py
  connectors/services/job_cleanup.py
  connectors/services/sync.py
  connectors/tests/config_2.yml
  connectors/tests/test_byoc.py
Labels: v8.7.0, v8.7.0.0

#401 [ABS-GCS] Add developing.md
  .buildkite/nightly.yml
  MANIFEST.in
  config.yml
  connectors/sources/azure_blob_storage.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/tests/fixtures/azure_blob_storage/docker-compose.yml
  connectors/sources/tests/fixtures/azure_blob_storage/fixture.py
  connectors/sources/tests/fixtures/azure_blob_storage/requirements.txt
  connectors/sources/tests/fixtures/google_cloud_storage/.env
  connectors/sources/tests/fixtures/google_cloud_storage/docker-compose.yml
  connectors/sources/tests/fixtures/google_cloud_storage/fixture.py
  connectors/sources/tests/fixtures/google_cloud_storage/gcs_dummy_cert.pem
  connectors/sources/tests/fixtures/google_cloud_storage/mocked_http_responses.json
  connectors/sources/tests/fixtures/google_cloud_storage/mockerserver.properties
  connectors/sources/tests/fixtures/google_cloud_storage/requirements.txt
  connectors/sources/tests/fixtures/google_cloud_storage/service_account_dummy_cert.pem
  connectors/sources/tests/test_azure_blob_storage.py
  connectors/sources/tests/test_google_cloud_storage.py
  docs/DEVELOPING.md
Labels: v8.7.0.0

#448 [Filtering] Add method for checking a filter validation state
  connectors/byoc.py
  connectors/filtering/validation.py
  connectors/tests/test_byoc.py
  connectors/tests/test_validation.py
Labels: auto-backport, v8.7.0.0

#453 [Fix] Fix flaky test "test_sync_job"
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0.0

#446 Add --log-level setting for ingest service instead of --debug flag
  Makefile
  config.yml
  connectors/cli.py
  connectors/tests/test_cli.py
  docs/CONFIG.md
  docs/DEVELOPING.md
Labels: release_note, auto-backport, v8.7.0.0

#455 Bump main to 8.8
  .backportrc.json
  .buildkite/run_nigthly.sh
  connectors/VERSION
  connectors/tests/ftest.sh
Labels: auto-backport, v8.7.0.0

#433 Fix service stop code
  connectors/cli.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_sync.py
Labels: auto-backport, v8.7.0.0

#454 Make --action list command output to stdout
  connectors/cli.py
  connectors/tests/test_cli.py
Labels: auto-backport, 8.7, v8.8.0.0

#456 [8.7] Add --log-level setting for ingest service instead of --debug flag (#446)
  Makefile
  config.yml
  connectors/cli.py
  connectors/tests/test_cli.py
  docs/CONFIG.md
  docs/DEVELOPING.md
Labels: backport

#385 Clarify e2e test and add cross links
  docs/DEVELOPING.md
Labels: auto-backport, v8.7.0.0

#459 [8.7] Make --action list command output to stdout (#454)
  connectors/cli.py
  connectors/tests/test_cli.py
Labels: backport

#457 [8.7] Fix service stop code (#433)
  connectors/cli.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_sync.py
Labels: backport

#462 [Fix] delete_indices used a default mutable argument
  connectors/es/client.py
Labels: auto-backport, v8.7.0.0, v8.8.0.0

#458 bump elasticsearch client
  requirements/framework.txt
Labels: auto-backport, v8.6.0, v8.7.0.0, v8.8.0.0

#437 Terminate all services if one exits
  connectors/cli.py
  connectors/services/base.py
  connectors/tests/test_base_service.py
Labels: auto-backport, 8.7, v8.8.0.0

#463 [8.7] Terminate all services if one exits (#437)
  connectors/cli.py
  connectors/services/base.py
  connectors/tests/test_base_service.py
Labels: backport

#468 Add meta data as name and description
  .github/ISSUE_TEMPLATE/qa_connector_package.md
Labels: auto-backport, v8.8.0.0

#464 remove e2str and str2e
  connectors/byoc.py
  connectors/filtering/validation.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: v8.8.0.0

#447 Upgrade SQLAlchemy v2.0 to use python-oracledb and improve performance
  .buildkite/nightly.yml
  connectors/sources/generic_database.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/tests/fixtures/oracle/docker-compose.yml
  connectors/sources/tests/fixtures/oracle/fixture.py
  connectors/sources/tests/fixtures/oracle/requirements.txt
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_oracle.py
  requirements/framework.txt
Labels: v8.7.0.0

#475 Make SyncJobIndex methods param compulsory
  connectors/byoc.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#477 [Fix] Store filtering in its original form in .elastic-connectors-sync-job
  connectors/byoc.py
  connectors/filtering/validation.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0.0, v8.8.0.0

#482 [8.7] added flake8-bugbear (#481)
  Makefile
  connectors/byoei.py
  connectors/source.py
  connectors/sources/tests/fixtures/dir/fixture.py
  connectors/sources/tests/fixtures/fixture.py
  connectors/sources/tests/fixtures/mongodb/fixture.py
  connectors/sources/tests/fixtures/s3/fixture.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
  connectors/tests/test_validation.py
  requirements/tests.txt
  setup.cfg
Labels: backport

#488 Rename stuck jobs to idle jobs
  connectors/byoc.py
  connectors/services/job_cleanup.py
  connectors/tests/test_byoc.py
  connectors/tests/test_job_cleanup.py
Labels: auto-backport, v8.7.0

#460 Refactor SyncJob class
  connectors/byoc.py
  connectors/es/__init__.py
  connectors/es/document.py
  connectors/es/index.py
  connectors/services/job_cleanup.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_es_document.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_sync.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#479 [Docs] Move connector protocol to python
  README.md
  docs/CONNECTOR_PROTOCOL.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#492 [Refactoring] Make error more explicit when basic auth and api key are used at the same time
  connectors/es/client.py
Labels: auto-backport, v8.8.0.0

#478 Remove assert from source.py and replace it with manual validation
  connectors/source.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#489 Make param indices of delete_indices method mandatory
  connectors/es/client.py
  connectors/tests/test_es_client.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#364 Include the unit of measure for size field in Amazon S3
  connectors/sources/s3.py
  connectors/sources/tests/test_s3.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#487 added a small e2e test (runs for each PR)
  .buildkite/run_dockerized_test.sh
  .buildkite/run_nigthly.sh
  .github/PULL_REQUEST_TEMPLATE.md
  connectors/sources/tests/fixtures/dir/fixture.py
  connectors/sources/tests/fixtures/fixture.py
  connectors/tests/ftest.sh
Labels: auto-backport, v8.7.0, v8.8.0.0

#495 Make filtering validation VALID by default
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#504 [8.7] Refactor SyncJob class (#460)
  connectors/byoc.py
  connectors/es/__init__.py
  connectors/es/document.py
  connectors/es/index.py
  connectors/services/job_cleanup.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_es_document.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_sync.py
Labels: backport

#503 Update validate_filtering function
  connectors/filtering/validation.py
  connectors/services/sync.py
  connectors/tests/test_validation.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#508 Remove unused mock
  connectors/tests/test_validation.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#510 Use TODOs consistently throughout the codebase
  .buildkite/run_dockerized_test.sh
  .buildkite/run_nigthly.sh
  connectors/byoei.py
  connectors/kibana.py
  connectors/services/sync.py
  connectors/sources/mongo.py
  connectors/sources/tests/fixtures/fixture.py
  connectors/tests/test_es_client.py
Labels: auto-backport, v8.8.0.0

#518 Remove unused patch
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#474 Update Connector class to only include connector attributes and self-mutating methods
  connectors/byoc.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#498 Validate filtering only when it's in EDITED state
  connectors/byoc.py
  connectors/filtering/validation.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
  connectors/tests/test_validation.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#525 Rename param filter to filter_
  connectors/byoc.py
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#506 use a dict comprehension
  connectors/source.py
Labels: v8.8.0.0

#524 Set logger before parsing config
  connectors/cli.py
  connectors/tests/test_cli.py
Labels: auto-backport, 8.7, v8.8.0.0

#465 draft for pr etiquette
  docs/CONTRIBUTING.md
Labels: v8.8.0.0

#521 [Generic Database Connector] Use singular for database label
  connectors/sources/generic_database.py
Labels: auto-backport, v8.8.0.0

#531 [8.7] Set logger before parsing config (#524)
  connectors/cli.py
  connectors/tests/test_cli.py
Labels: backport

#519 [MySQL] Only allow one database to be configured
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#516 Make MySQL connector terminate faster when connector is retrying
  connectors/sources/mysql.py
Labels: auto-backport, 8.7, v8.8.0.0

#540 [8.7] [Fix] Store filtering in its original form in .elastic-connectors-sync-job (#477)
  connectors/filtering/validation.py
  connectors/sources/tests/test_mysql.py
Labels: backport

#542 Allow multiple ".digit" postfixes after major.minor in .backportrc
  .backportrc.json
Labels: auto-backport, v8.8.0.0

#529 Documented the `cli` module
  connectors/cli.py
Labels: v8.8.0.0

#530 Document the `byoei` module
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.8.0.0

#536 Extract ready_to_sync method from Connector to SyncService
  connectors/byoc.py
  connectors/services/sync.py
Labels: auto-backport, v8.8.0.0

#551 Fix issues raising from base service swallowing errors
  connectors/byoc.py
  connectors/tests/test_sync.py
Labels: v8.8.0.0

#533 [Docs] Document the filtering module
  connectors/filtering/basic_rule.py
  connectors/filtering/validation.py
Labels: auto-backport, v8.8.0.0

#548 [Network Drive] Add support for e2e in Macbook with m1 chip
  connectors/sources/tests/fixtures/network_drive/docker-compose.yml
Labels: auto-backport, v8.6.0, v8.7.0, v8.8.0.0

#555 added pyright and fixed a few issues
  Makefile
  connectors/byoc.py
  connectors/es/client.py
  connectors/logger.py
  connectors/services/job_cleanup.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/s3.py
  connectors/utils.py
  pyrightconfig.json
  requirements/tests.txt
Labels: v8.8.0.0

#558 Minor refactor of SyncService
  connectors/services/sync.py
Labels: v8.8.0.0

#552 Introduce "validate_configuration" method to BaseSource and use it
  connectors/byoc.py
  connectors/source.py
  connectors/sources/mysql.py
  connectors/tests/fake_sources.py
  connectors/tests/test_sync.py
Labels: v8.8.0.0

#564 Change tech preview with beta
  README.md
Labels: auto-backport, v8.8.0.0
