Repository elastic/connectors, pull requests merged in 2023-03, with the labels that each got.

#500 Refactor SyncService class
  connectors/byoc.py
  connectors/services/sync.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#567 Fix pyright errors
  connectors/kibana.py
  connectors/sources/s3.py
Labels: v8.8.0.0

#546 [MySQL] Make tables configurable
  connectors/sources/generic_database.py
  connectors/sources/mysql.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#549 [Generic Database Connector] Added documentation for PostgreSQL in developing.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#571 Fix typo in `oracle.py`
  connectors/sources/oracle.py
Labels: auto-backport, 8.7, v8.8.0.0

#556 [Generic Database Connector] Added documentation for Oracle Database in developing.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#557 [Generic Database Connector] Added documentation for Microsoft SQL in developing.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#509 [Generic Database Connector] Added Microsoft SQL Connector
  .buildkite/nightly.yml
  .isort.cfg
  config.yml
  connectors/sources/generic_database.py
  connectors/sources/mssql.py
  connectors/sources/tests/fixtures/mssql/docker-compose.yml
  connectors/sources/tests/fixtures/mssql/fixture.py
  connectors/sources/tests/fixtures/mssql/requirements.txt
  connectors/sources/tests/test_mssql.py
  requirements/framework.txt
Labels: auto-backport, v8.8.0.0

#581 Add more tests for ESIndex class
  connectors/tests/test_es_index.py
Labels: auto-backport, v8.8.0.0

#575 Add last_sync_scheduled_at to connector index
  connectors/kibana.py
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.8.0.0

#586 [MySQL] Add assertions to "close" tests
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#587 [MySQL] Use pass for noop statement in test
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#588 [MySQL] Rename a test
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#578 [Rename]-Positive name for SSL flag
  connectors/sources/generic_database.py
  connectors/sources/mysql.py
  connectors/sources/postgresql.py
  connectors/sources/tests/test_generic_database.py
  docs/DEVELOPING.md
Labels: auto-backport, 8.7, v8.8.0.0

#585 [MongoDB] Advanced rules validator
  connectors/sources/mongo.py
  connectors/sources/tests/test_mongo.py
Labels: auto-backport, v8.8.0.0

#493 [GCS]-Parse configurations from Kibana UI
  connectors/sources/google_cloud_storage.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, 8.7, v8.8.0.0

#589 [8.7] [GCS]-Parse configurations from Kibana UI (#493)
  connectors/sources/google_cloud_storage.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: backport

#591 [MongoDB] Allow empty advanced rules
  connectors/sources/mongo.py
  connectors/sources/tests/test_mongo.py
Labels: auto-backport, v8.8.0.0

#584 service factory metaclass
  connectors/cli.py
  connectors/services/__init__.py
  connectors/services/base.py
  connectors/services/job_cleanup.py
  connectors/services/job_scheduling.py
  connectors/tests/test_base_service.py
  connectors/tests/test_cli.py
Labels: auto-backport, v8.8.0.0

#595 [CODEOWNERS] Add elastic/ingestion-team as codeowner for every file
  .github/CODEOWNERS
Labels: auto-backport, v8.8.0.0

#597 document the services/base.py module
  connectors/services/base.py
Labels: auto-backport, v8.8.0.0

#594 [Filtering] Empty advanced rules shouldn't be validated
  connectors/filtering/validation.py
  connectors/tests/test_validation.py
Labels: auto-backport, v8.8.0.0

#600 fix leak -- fixes #599
  connectors/sources/tests/test_google_cloud_storage.py
Labels: auto-backport, v8.8.0.0

#514 Temporary solve the problem with cancellation
  connectors/services/base.py
  connectors/tests/test_base_service.py
Labels: auto-backport, 8.7, v8.8.0.0

#486 Add validation and errors for invalid mongodb database/collection
  connectors/sources/mongo.py
  connectors/sources/tests/test_mongo.py
Labels: v8.8.0.0

#609 Add _seq_no and _primary_term to ESDocument
  connectors/es/document.py
  connectors/tests/test_es_document.py
Labels: v8.8.0.0

#616 Add default field properties for configuration
  connectors/source.py
  connectors/sources/mongo.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#618 Update config fields for more connector types (1/3)
  connectors/sources/azure_blob_storage.py
  connectors/sources/directory.py
  connectors/sources/generic_database.py
Labels: v8.8.0.0

#537 [new connector] SharePoint - Online & Servers
  .buildkite/nightly.yml
  config.yml
  connectors/sources/sharepoint.py
  connectors/sources/tests/fixtures/sharepoint/Dockerfile
  connectors/sources/tests/fixtures/sharepoint/docker-compose.yml
  connectors/sources/tests/fixtures/sharepoint/fixture.py
  connectors/sources/tests/fixtures/sharepoint/requirements.txt
  connectors/sources/tests/test_sharepoint.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#527 [New Connector] Jira connector - On Cloud and Server
  .buildkite/nightly.yml
  config.yml
  connectors/sources/jira.py
  connectors/sources/tests/fixtures/jira/Dockerfile
  connectors/sources/tests/fixtures/jira/docker-compose.yml
  connectors/sources/tests/fixtures/jira/fixture.py
  connectors/sources/tests/fixtures/jira/requirements.txt
  connectors/sources/tests/test_jira.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#620 Update config fields for more connector types (2/3)
  connectors/sources/google_cloud_storage.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
Labels: v8.8.0.0

#625 [8.7] Upgrade SQLAlchemy v2.0 to use python-oracledb and improve performance (#447)
  .buildkite/nightly.yml
  connectors/sources/generic_database.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/tests/fixtures/oracle/docker-compose.yml
  connectors/sources/tests/fixtures/oracle/fixture.py
  connectors/sources/tests/fixtures/oracle/requirements.txt
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_oracle.py
  requirements/framework.txt
Labels: backport

#621 Update config fields for more connector types (3/3)
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
Labels: v8.8.0.0

#628 [8.7] [Generic Database Connector] Added documentation for PostgreSQL in developing.md (#549)
  docs/DEVELOPING.md
Labels: backport

#605 Add a simple test to check that service keeps running if sync fails
  connectors/tests/test_job_scheduling.py
Labels: auto-backport, v8.8.0.0

#629 [8.7] [Generic Database Connector] Added documentation for Oracle Database in developing.md (#556)
  docs/DEVELOPING.md
Labels: backport

#608 Add optimistic concurrency control to update method
  connectors/es/index.py
  connectors/tests/test_es_index.py
Labels: v8.8.0.0

#610 Update reload method
  connectors/es/document.py
  connectors/es/index.py
  connectors/services/job_cleanup.py
  connectors/services/job_scheduling.py
  connectors/sync_job_runner.py
  connectors/tests/test_es_document.py
  connectors/tests/test_es_index.py
  connectors/tests/test_job_cleanup.py
Labels: auto-backport, v8.8.0.0

#562 [MySQL connector] Fix connection pool initialisation to be a context method - with_connection_pool
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.8.0.0

#635 Introduce validate_config to ABS connector
  connectors/sources/azure_blob_storage.py
  connectors/sources/tests/test_azure_blob_storage.py
Labels: auto-backport, v8.8.0.0

#633 Add more explicit messages for connector errors when status is unexpected
  connectors/services/job_scheduling.py
Labels: v8.8.0.0

#611 Remove setters
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#632 Log service version once real service starts
  connectors/cli.py
Labels: auto-backport, v8.8.0.0

#636 Replace print with logger.info for directory connector
  connectors/sources/directory.py
Labels: v8.8.0.0

#612 [Confluence] Add E2E test for the connector
  .buildkite/nightly.yml
  connectors/sources/tests/fixtures/confluence/Dockerfile
  connectors/sources/tests/fixtures/confluence/docker-compose.yml
  connectors/sources/tests/fixtures/confluence/fixture.py
  connectors/sources/tests/fixtures/confluence/requirements.txt
Labels: v8.8.0.0

#639 Introduce and use ConfigurableFieldValueError
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/s3.py
  connectors/sources/sharepoint.py
  connectors/sources/tests/test_azure_blob_storage.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/sources/tests/test_jira.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_s3.py
  connectors/sources/tests/test_sharepoint.py
Labels: v8.8.0.0

#643 [MySQL] Use ConfigurableFieldError in validate_config
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#603 [MongoDB] Advanced rules "find"
  connectors/sources/mongo.py
  connectors/sources/tests/test_mongo.py
Labels: auto-backport, v8.8.0.0

#642 Add human-readable error messages to QueueFull
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: v8.8.0.0

#653 [MySQL] Improve test names
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#656 [8.7] Fix issues raising from base service swallowing errors (#551)
  connectors/byoc.py
  connectors/tests/test_sync.py
Labels: backport

#631 Add dependency in arm64 for PostgreSQL
  requirements/arm64.txt
Labels: auto-backport, v8.7.0, v8.8.0.0

#657 Adds PR hygiene checks to checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.8.0.0

#664 Use lazy evaluation for expensive function in DEBUG log
  connectors/byoei.py
Labels: v8.8.0.0

#663 Add missing async/await for validate_config in s3
  connectors/sources/s3.py
  connectors/sources/tests/test_s3.py
Labels: v8.8.0.0

#665 Allow wildcards in MySQL table accessibility validation
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.8.0.0

#645 Remove enable_content_extraction
  connectors/byoei.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/directory.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/sharepoint.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoei.py
  docs/DEVELOPING.md
Labels: v8.8.0.0

#617 Update DOCKER.md to include user-friendly steps of running service in Docker
  docs/DOCKER.md
Labels: auto-backport, 8.7, v8.7.0, v8.8.0.0

#652 [Jira] Introduce a new configuration parameter - `projects`
  connectors/sources/jira.py
  connectors/sources/tests/test_jira.py
Labels: auto-backport, v8.8.0.0

#668 [DOCS] Remove connectors info, link to elastic.co docs
  docs/DEVELOPING.md
Labels: documentation, auto-backport, v8.7.0, v8.8.0.0

#672 [8.7] Remove connectors info, link to elastic.co docs (#668)
  docs/DEVELOPING.md
Labels: backport

#673 [Sync Job] Check length of "_id" of a yielded doc
  connectors/sync_job_runner.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#662 Allow override of connector record in the index when running functional tests
  connectors/kibana.py
  connectors/sources/tests/fixtures/mongodb/connector.json
  connectors/sources/tests/fixtures/mysql/connector.json
  connectors/sources/tests/fixtures/mysql/filtering.json
  connectors/tests/connector.json
  connectors/tests/ftest.sh
  connectors/tests/test_kibana.py
Labels: v8.8.0.0

#676 [MySQL] Remove unnecessary log
  connectors/sources/mysql.py
Labels: auto-backport, v8.8.0.0

#675 [MySQL] Use queries class
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#515 Report ingestion stats during job execution
  connectors/byoc.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#682 added a 2mn pause to give a chanche to perf8 to wrap up
  connectors/tests/ftest.sh
Labels: auto-backport, v8.8.0.0

#654 Restrict ingestion stats fields
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0
