Repository elastic/connectors, pull requests merged in 2023-05, with the labels that each got.

#827 added a max duration
  connectors/sources/tests/fixtures/fixture.py
  connectors/tests/ftest.sh
Labels: auto-backport, v8.7.0, v8.9.0.0, v8.8.0

#833 useVault: false for pipelines - we don't use Vault
  .buildkite/nightly.yml
  .buildkite/pipeline.yml
Labels: auto-backport, 8.7, v8.9.0.0, 8.8

#834 Fix regex for main labelling for backportrc
  .backportrc.json
Labels: auto-backport, v8.9.0.0

#831 Bump ftest to use 8.9.0-SNAPSHOT
  connectors/tests/ftest.sh
Labels: auto-backport, v8.9.0.0

#836 Fix perf8 example
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.0.0

#838 Use vault in nightly tests
  .buildkite/nightly.yml
Labels: auto-backport, v8.9.0.0

#808 Add items that are too big to ingest into the queue anyway
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, 8.7, v8.8.0.0

#576 Improve performance for S3
  connectors/sources/s3.py
  connectors/sources/tests/test_s3.py
  requirements/aarch64.txt
  requirements/x86_64.txt
Labels: auto-backport, v8.8.0.0, team:external

#848 Fix linters for now
  connectors/sources/generic_database.py
Labels: auto-backport, 8.7, v8.9.0.0, 8.8

#849 [8.8] Fix linters for now (#848)
  connectors/sources/generic_database.py
Labels: backport

#850 [8.7] Fix linters for now (#848)
  connectors/sources/generic_database.py
Labels: backport

#851 [8.7] Report indexed_document_volume in MiB (#796)
  connectors/byoei.py
Labels: backport

#846 Update docker documentation
  docs/DOCKER.md
Labels: v8.9.0.0

#845 [MySQL] Filter table update times, which are None
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.9.0.0, v8.8.0

#858 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.9.0.0

#847 Update catalog-info.yaml
  catalog-info.yaml
Labels: auto-backport, v8.7.0, v8.9.0.0, v8.8.0

#859 Update catalog-info.yaml
  catalog-info.yaml
Labels: auto-backport, v8.9.0.0

#842 [8.7] Add items that are too big to ingest into the queue anyway (#808)
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: backport

#857 Update SSL cert label for MSSQL
  connectors/sources/mssql.py
Labels: auto-backport, v8.9.0.0

#864 Update catalog-info.yaml
  catalog-info.yaml
Labels: auto-backport, v8.9.0.0

#865 Return connectors-python back
  catalog-info.yaml
Labels: auto-backport, v8.9.0.0

#869 [Docs] Update DOCKER.md with new connectors
  docs/DOCKER.md
Labels: auto-backport, v8.9.0.0

#868 [8.8] Update SSL cert label for MSSQL (#857)
  connectors/sources/mssql.py
Labels: backport

#830 Remove 8.6 from backportrc
  .backportrc.json
Labels: auto-backport, v8.9.0

#278 Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: v8.7.0

#787 [SharePoint]Add Support for ingesting Site Pages
  connectors/sources/sharepoint.py
  connectors/sources/tests/test_sharepoint.py
  connectors/utils.py
Labels: auto-backport, team:external, v8.8.0

#878 [Docs] MySQL sync rules examples
  README.md
  docs/sync-rules/MYSQL.md
Labels: auto-backport, v8.9.0.0

#835 Add a sample option to CLI to get connector default config
  Makefile
  connectors/cli.py
Labels: auto-backport, v8.9.0

#580 [SharePoint] Documentation for SharePoint connector
  docs/DEVELOPING.md
Labels: auto-backport, team:external, v8.8.0

#876 [ServiceNow] Implementation Sync feature
  connectors/sources/servicenow.py
  connectors/sources/tests/test_servicenow.py
Labels: servicenow, v8.9.0, team:external

#881 [ServiceNow] E2E feature
  .buildkite/nightly.yml
  connectors/sources/tests/fixtures/servicenow/.env
  connectors/sources/tests/fixtures/servicenow/Dockerfile
  connectors/sources/tests/fixtures/servicenow/docker-compose.yml
  connectors/sources/tests/fixtures/servicenow/fixture.py
  connectors/sources/tests/fixtures/servicenow/requirements.txt
Labels: servicenow, v8.9.0, team:external

#893 Add rich configurable fields to connector protocol
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.8.0, v8.9.0.0

#889 Tips on logging levels
  docs/CONTRIBUTING.md
Labels: auto-backport, v8.9.0.0

#896 [8.8] Add rich configurable fields to connector protocol (893)
  docs/CONNECTOR_PROTOCOL.md
Labels: backport

#894 Add xlsb, xlsm in tika supported filetypes
  connectors/utils.py
Labels: auto-backport, v8.9.0.0

#890 [Sharepoint] Make all documents IDs size 36 bytes
  connectors/sources/tests/fixtures/sharepoint/fixture.py
Labels: auto-backport, sharepoint, v8.9.0, v8.9.0.0

#885 Rename `byoc` to `connectors.protocol.*`
  connectors/byoei.py
  connectors/preflight_check.py
  connectors/protocol/__init__.py
  connectors/protocol/connectors.py
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_mysql.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoei.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_job_execution.py
  connectors/tests/test_job_scheduling.py
  connectors/tests/test_preflight_check.py
  connectors/tests/test_protocol.py
  connectors/tests/test_sync_job_runner.py
  connectors/tests/test_validation.py
Labels: v8.9.0.0

#906 [8.8] add xlsb, xlsm in tika supported filetypes (#894)
  connectors/utils.py
Labels: backport

#903 [Sharepoint] Support multiple file sizes
  connectors/sources/tests/fixtures/sharepoint/fixture.py
Labels: team:ingestion, sharepoint, v8.9.0

#908 Fix problem with incorrect mappings created for content indices
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.8.0, v8.9.0.0

#907 Don't stop the ConcurrentTasks when one task raises exception
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0, v8.9.0.0

#911 SharePoint is tech preview in 8.8, not beta
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0, v8.9.0.0

#909 Add malformed configuration error to document
  connectors/protocol/connectors.py
  connectors/source.py
  connectors/sync_job_runner.py
  connectors/tests/test_protocol.py
  connectors/tests/test_source.py
  connectors/tests/test_sync_job_runner.py
Labels: auto-backport, v8.8.0, v8.9.0.0

#914 [8.8] Add malformed configuration error to document (#909)
  connectors/byoc.py
  connectors/source.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoc.py
  connectors/tests/test_source.py
  connectors/tests/test_sync_job_runner.py
Labels: backport

#913 [8.8] Fix problem with incorrect mappings created for content indices (#908)
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: backport

#919 make sure we switch to the right branch
  Dockerfile
Labels: auto-backport, v8.7.0, v8.8.0, v8.9.0.0

#922 Fix Sharepoint e2e test
  .buildkite/nightly.yml
  .buildkite/run_nigthly.sh
  connectors/sources/tests/fixtures/sharepoint/fixture.py
Labels: bug, auto-backport, v8.9.0, v8.9.0.0

#904 [Sharepoint] Support HTTP requests throttling
  connectors/sources/tests/fixtures/sharepoint/fixture.py
  connectors/sources/tests/fixtures/sharepoint/requirements.txt
Labels: auto-backport, team:ingestion, sharepoint, v8.9.0, v8.9.0.0

#925 [Sharepoint] Fix DATA_SIZE variable
  connectors/sources/tests/fixtures/sharepoint/docker-compose.yml
Labels: bug, auto-backport, v8.9.0, v8.9.0.0

#927 fix pyright on latest 3.10
  connectors/sources/generic_database.py
Labels: auto-backport, v8.8.0, v8.9.0.0

#905 renamed byoei.* to connectors.es.*
  connectors/es/sink.py
  connectors/kibana.py
  connectors/sync_job_runner.py
  tests/test_kibana.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.9.0.0

#928 Reorganized docs for contributing, development, and reference
  README.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/REFERENCE.md
  docs/reference/confluence.md
  docs/reference/jira.md
  docs/reference/sharepoint.md
Labels: auto-backport, v8.9.0, v8.8.0, v8.9.0.0

#932 Reset connector error when a new sync job starts
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.8.0, v8.9.0.0

#916 [New Connector] GitHub: Ping feature
  config.yml
  connectors/sources/github.py
  requirements/framework.txt
  tests/sources/test_github.py
Labels: v8.9.0, team:external, github

#936 [DLS] Add "last_permissions_sync_scheduled_at" property to connector class
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#938 [DLS] Add permissions scheduling accessor
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#946 Jira advanced sync rules
  connectors/sources/atlassian.py
  connectors/sources/jira.py
  tests/sources/test_atlassian.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, v8.9.0, team:external, v8.9.0.0

#937 [DLS] Add "get_permissions" to BaseDataSource
  connectors/source.py
  tests/test_source.py
Labels: auto-backport, v8.9.0.0

#942 [DLS] Add "permissions" job_type to SyncJob class
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#943 [DLS] Add "document_level_security" feature flag
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#955 [DLS] Add "last_permissions_sync_scheduled_at" to Kibana fake
  connectors/kibana.py
Labels: auto-backport, v8.9.0.0

#957 [DLS] Add "last_permissions_sync_scheduled_at" to protocol docs
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.9.0.0

#935 developer docs for GA
  README.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/UPGRADING.md
Labels: auto-backport, v8.9.0, v8.8.0, v8.9.0.0, v8.8.0.0

#918 [New Connector] Dropbox: Ping feature
  config.yml
  connectors/sources/dropbox.py
  requirements/framework.txt
  tests/sources/test_dropbox.py
Labels: v8.9.0, team:external, dropbox

#947 [DLS] Add "last_permissions_sync_scheduled_at" mutator
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#958 Add sync_cursor to connector protocol doc
  docs/CONNECTOR_PROTOCOL.md
Labels: v8.9.0, v8.9.0.0

#959 Add sync_cursor to ftest connector.json
  connectors/kibana.py
  tests/fixtures/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mysql/connector.json
Labels: v8.9.0, v8.9.0.0

#956 Add Confluence advanced sync rules
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, v8.9.0, team:external, v8.9.0.0

#964 [DLS] Add "last_permissions_sync_status" to connector protocol docs
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.9.0.0

#965 [DLS] Add "last_permissions_sync_status" to kibana and fixtures
  connectors/kibana.py
  tests/fixtures/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mysql/connector.json
Labels: auto-backport, v8.9.0.0

#960 [8.8] backport developer docs 8.8
  README.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/UPGRADING.md
Labels: backport

#962 Add incremental job type
  connectors/protocol/connectors.py
  docs/CONNECTOR_PROTOCOL.md
Labels: v8.9.0, v8.9.0.0

#976 Add last_incremental_sync_scheduled_at to Connector
  connectors/protocol/connectors.py
  docs/CONNECTOR_PROTOCOL.md
  tests/protocol/test_connectors.py
Labels: v8.9.0, v8.9.0.0

#972 switch to ruff
  .ruff.toml
  Makefile
  connectors/es/client.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/mysql.py
  requirements/tests.txt
  setup.cfg
  tests/sources/test_mysql.py
Labels: auto-backport, v8.9.0.0

#983 Rectify spelling mistakes
  connectors/services/base.py
  connectors/utils.py
  docs/CONFIG.md
  docs/CONNECTOR_PROTOCOL.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.0.0

#978 Add incremental_sync feature flag
  connectors/protocol/connectors.py
  docs/CONNECTOR_PROTOCOL.md
  tests/protocol/test_connectors.py
Labels: v8.9.0, v8.9.0.0

#971 @tracer.start_as_current_span
  connectors/es/sink.py
  connectors/logger.py
  tests/test_logger.py
Labels: auto-backport, v8.9.0.0

#966 [DLS] Add last_access_control_sync_status property to Connector
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#987 [DLS] Rename "scheduling.permissions" to "scheduling.access_control"
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0.0

#988 Update DEVELOPING.md
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.0.0

#989 Install pymongo[srv] on M1 and ARM linux
  requirements/aarch64.txt
  requirements/arm64.txt
Labels: auto-backport, v8.7.0, v8.9.0.0, v8.8.0.0

#985 unify the metrics API
  connectors/es/sink.py
  connectors/logger.py
  tests/test_logger.py
Labels: v8.9.0.0
