Repository elastic/connectors, pull requests merged in 2023-08, with the labels that each got.

#1365 Add missing asyncio plugin
  tests/sources/test_network_drive.py
Labels: v8.10.0.0, v8.10.0

#1370 Slow down SPO fake server to have 50ms latency
  tests/sources/fixtures/sharepoint_online/fixture.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1347 Decouple PostgreSQLDataSource from GenericBaseDataSource
  connectors/sources/postgresql.py
  tests/sources/test_postgresql.py
Labels: v8.10.0.0, v8.10.0

#1378 [Google Drive] Link to official connector docs, remove migrated docs from repo
  docs/REFERENCE.md
  docs/reference/google_drive.md
Labels: auto-backport, v8.10.0.0

#1353 GitHub connector with GraphQL implementation
  README.md
  connectors/sources/github.py
  docs/reference/github.md
  docs/sync-rules/GITHUB.md
  tests/sources/fixtures/github/fixture.py
  tests/sources/test_github.py
Labels: auto-backport, team:external, github, v8.10.0.0, v8.10.0

#1366 [SPO] Granular permissions for site list items + propagate site admin permissions for site-list and list-item
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1355 Add PostgreSQLClient abstraction
  connectors/sources/postgresql.py
  tests/sources/test_postgresql.py
Labels: v8.10.0

#1374 Add colored logging
  connectors/logger.py
  tests/test_logger.py
Labels: v8.10.0.0, v8.10.0

#1381 Update default configs for dropbox & servicenow
  connectors/sources/dropbox.py
  connectors/sources/servicenow.py
  tests/sources/test_dropbox.py
  tests/sources/test_servicenow.py
Labels: auto-backport, v8.10.0.0, v8.10.0

#1384 Stabilize SPO site page ids
  connectors/sources/sharepoint_online.py
Labels: release_note, auto-backport, v8.9.0, v8.10.0.0, vpre-8.10-stable

#1386 [8.9] Stabilize SPO site page ids (#1384)
  connectors/sources/sharepoint_online.py
Labels: backport

#1391 Add connector.json for ServiceNow
  tests/sources/fixtures/servicenow/connector.json
Labels: auto-backport, v8.9.0, v8.10.0.0

#1341 [Network Drive] Advanced Sync Rules
  README.md
  connectors/sources/network_drive.py
  docs/sync-rules/NETWORK_DRIVE.md
  requirements/framework.txt
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.10.0.0

#1363 Decouple MSSQLDataSource from GenericBaseDataSource
  connectors/sources/mssql.py
  tests/sources/test_generic_database.py
  tests/sources/test_mssql.py
Labels: v8.10.0.0, v8.10.0

#1332 Fix warning messages for respective connectors test cases
  connectors/sources/google_cloud_storage.py
  tests/sources/fixtures/google_cloud_storage/service_account_dummy_cert.pem
  tests/sources/support.py
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_confluence.py
  tests/sources/test_directory.py
  tests/sources/test_dropbox.py
  tests/sources/test_generic_database.py
  tests/sources/test_github.py
  tests/sources/test_jira.py
  tests/sources/test_mongo.py
  tests/sources/test_mssql.py
  tests/sources/test_mysql.py
  tests/sources/test_network_drive.py
  tests/sources/test_oracle.py
  tests/sources/test_postgresql.py
  tests/sources/test_s3.py
  tests/sources/test_servicenow.py
  tests/sources/test_sharepoint_online.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, team:external, v8.10.0.0

#1394 Try out buildkite diff plugin to run ftest once connector changes
  .buildkite/diff
  .buildkite/pipeline.yml
Labels: auto-backport, v8.10.0.0

#1329 [SPO] Remove redundant with drive items permissions call
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1330 [SPO] Fix typo and wrong docs
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0

#1298 Slack connector
  config.yml
  connectors/sources/slack.py
  connectors/utils.py
  docs/reference/slack.md
  tests/sources/test_slack.py
Labels: release_note, auto-backport, v8.10.0.0, v8.11.0

#1395 Add skipped exceptions to retryable
  connectors/utils.py
  tests/test_utils.py
Labels: v8.10.0.0, v8.10.0

#1364 Decouple OracleDataSource from GenericBaseDataSource
  connectors/sources/generic_database.py
  connectors/sources/mssql.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  tests/sources/test_generic_database.py
  tests/sources/test_oracle.py
Labels: v8.10.0.0, v8.10.0

#1401 Refactor execute_query function
  connectors/sources/generic_database.py
  connectors/sources/postgresql.py
  tests/sources/test_generic_database.py
  tests/sources/test_postgresql.py
Labels: v8.10.0.0, v8.10.0

#1393 [Salesforce] Improve request handling
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: v8.10.0.0, v8.10.0

#1409 Typo in new change checking step
  .buildkite/pipeline.yml
Labels: auto-backport, v8.10.0.0

#1418 [Refactoring] Split up test_get_pem_format tests
  tests/test_utils.py
Labels: auto-backport, v8.10.0.0

#1419 [SPO] Fix small typo
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0

#1407 [Salesforce] Ingest Contacts and Leads
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: v8.10.0.0, v8.10.0

#1397 Implement Confluence DLS
  connectors/sources/confluence.py
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, team:external, v8.10.0.0, v8.10.0

#1425 [Refactoring] Remove shadow variables
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0

#1414 [OneDrive] Add Indexing Implementation
  connectors/sources/onedrive.py
  tests/sources/test_onedrive.py
Labels: v8.10.0.0

#1416 [OneDrive] Add e2e feature
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  tests/sources/fixtures/onedrive/.env
  tests/sources/fixtures/onedrive/Dockerfile
  tests/sources/fixtures/onedrive/config.yml
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/onedrive/fixture.py
  tests/sources/fixtures/onedrive/requirements.txt
Labels: v8.10.0.0

#1431 Ingest Campaign, Case and related sobjects
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: v8.10.0.0, v8.10.0

#1396 Implement Jira DLS
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.10.0.0, v8.10.0

#1193 Make tests fail on warnings; add some warnings to ignore list
  pytest.ini
  setup.cfg
  tests/sources/test_slack.py
Labels: auto-backport, v8.10.0.0

#1436 Enable linter rule to report shadowing issues
  .ruff.toml
  connectors/logger.py
  connectors/source.py
  connectors/sources/github.py
  connectors/sources/google_drive.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/conftest.py
  tests/es/test_settings.py
  tests/services/test_job_cleanup.py
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/fixtures/google_drive/fixture.py
  tests/sources/fixtures/jira/fixture.py
  tests/sources/fixtures/sharepoint_server/fixture.py
  tests/sources/test_github.py
  tests/sources/test_mysql.py
  tests/test_source.py
Labels: auto-backport, v8.10.0.0

#1437 [Commons] Add assert_called_once_with to AsyncIterator
  tests/commons.py
  tests/sources/test_sharepoint_online.py
  tests/test_commons.py
Labels: auto-backport, v8.10.0.0

#1433 Add OneDrive connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  config.yml
  connectors/sources/onedrive.py
  tests/sources/fixtures/onedrive/.env
  tests/sources/fixtures/onedrive/Dockerfile
  tests/sources/fixtures/onedrive/config.yml
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/onedrive/fixture.py
  tests/sources/fixtures/onedrive/requirements.txt
  tests/sources/test_onedrive.py
Labels: auto-backport, v8.10.0.0, v8.10.0

#1430 Add DLS docs for Jira and Confluence
  README.md
  docs/document-level-security/CONFLUENCE.md
  docs/document-level-security/JIRA.md
Labels: auto-backport, confluence, jira, team:external, v8.10.0.0, v8.10.0

#1446 Add _dls_enabled() before fetching unique permissions
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1449 Drop standalone isort and use one from ruff distribution
  .isort.cfg
  .ruff.toml
  Makefile
  connectors/es/client.py
  requirements/tests.txt
Labels: auto-backport, v8.10.0.0

#1452 Update RCFs
  connectors/sources/salesforce.py
Labels: v8.10.0.0, v8.10.0

#1440 Populate webUrl for site pages and list item attachments
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/fixture.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, v8.10.0.0, vpre-8.10-stable

#1454 Bump aiohttp and flask versions due to security risks
  requirements/framework.txt
  tests/sources/fixtures/confluence/requirements.txt
  tests/sources/fixtures/google_cloud_storage/requirements.txt
  tests/sources/fixtures/google_drive/requirements.txt
  tests/sources/fixtures/jira/requirements.txt
  tests/sources/fixtures/servicenow/requirements.txt
  tests/sources/fixtures/sharepoint_online/requirements.txt
  tests/sources/fixtures/sharepoint_server/requirements.txt
Labels: auto-backport, v8.10.0.0, v8.10.0

#1451 Download ContentDocuments and extract binary content
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: v8.10.0.0, v8.10.0

#1404 move default configs to code
  config.yml
  connectors/config.py
  connectors/kibana.py
  docs/CONFIG.md
  scripts/verify.py
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/dropbox/config.yml
  tests/sources/fixtures/github/config.yml
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/google_drive/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/sharepoint_online/config.yml
  tests/sources/fixtures/sharepoint_server/config.yml
  tests/test_config.py
Labels: release_note, auto-backport, v8.10.0.0, v8.10.0

#1456 reformat config yaml
  config.yml
Labels: auto-backport, v8.10.0.0, v8.10.0

#1317 [GMail] New connector
  connectors/config.py
  connectors/sources/gmail.py
  connectors/sources/google.py
  connectors/utils.py
  tests/test_gmail.py
  tests/test_google.py
  tests/test_utils.py
Labels: auto-backport, v8.10.0.0

#1457 Bump app version to 8.11
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
Labels: v8.11.0

#1459 [Google Drive] Fix ACL sync logic for case when user has no groups
  connectors/sources/google_drive.py
  tests/sources/fixtures/google_drive/connector.json
Labels: bug, auto-backport, v8.10.0.0

#1466 [Access control] Add new module for common functions
  connectors/access_control.py
  connectors/sources/confluence.py
  connectors/sources/gmail.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/sharepoint_online.py
  tests/sources/test_jira.py
  tests/sources/test_sharepoint_online.py
  tests/test_access_control.py
Labels: auto-backport, v8.11.0.0

#1450 Make validate_config of data source call its super method first
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/github.py
  connectors/sources/gmail.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
  connectors/sources/sharepoint_server.py
Labels: v8.10.0.0, v8.10.0

#1444 [Basic Rules] Debug log, if a basic rule included or excluded a document
  connectors/filtering/basic_rule.py
Labels: auto-backport, v8.9.0, v8.8.0, v8.10.0.0

#1478 [Google Drive] Handle failures when fetching file ACLs
  connectors/sources/google_drive.py
Labels: bug, auto-backport, v8.10.0.0, v8.11.0.0

#1494 Fix warning error for mysql
  tests/sources/test_mysql.py
Labels: auto-backport, team:external, v8.11.0.0

#1389 [Salesforce] Add Salesforce connector
  connectors/config.py
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: auto-backport, v8.10.0.0, v8.10.0

#1495 [Tests] Move GMail and Google tests to correct directory
  tests/sources/test_gmail.py
  tests/sources/test_google.py
Labels: auto-backport, v8.11.0.0

#1470 default to api_key, fallback on username/password
  config.yml
  connectors/es/client.py
  tests/es/test_client.py
Labels: auto-backport, v8.10.0, v8.11.0, v8.11.0.0

#1464 Improve logging in the framework
  connectors/es/sink.py
  connectors/filtering/validation.py
  connectors/preflight_check.py
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  connectors/sync_job_runner.py
Labels: auto-backport, v8.10.0, v8.11.0.0

#1514 Fix mongodb tests by removing mocking of _get_socket + patching admin ping call
  tests/sources/test_mongo.py
Labels: auto-backport, v8.10.0, vpre-8.10-stable, v8.11.0.0

#1515 [Salesforce] Fix configuration
  connectors/sources/salesforce.py
Labels: auto-backport, v8.10.0.0, v8.10.0, v8.11.0.0

#1511 Add more tests to improve test coverage
  tests/protocol/test_connectors.py
  tests/test_utils.py
Labels: auto-backport, v8.10.0, v8.11.0.0

#1428 Add real-time data availability option
  docs/CONNECTOR_PROTOCOL.md
  docs/DEVELOPING.md
Labels: v8.10.0.0, v8.10.0

#1513 [Confluence] Move common code to Atlassian module
  connectors/sources/atlassian.py
  connectors/sources/confluence.py
  tests/sources/test_atlassian.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, team:external, v8.10.0, v8.11.0.0

#1522 lock pymongo version
  requirements/aarch64.txt
  requirements/x86_64.txt
Labels: auto-backport, v8.10.0, v8.11.0, v8.11.0.0

#1527 Fix log message for access control sync after refactoring
  connectors/es/sink.py
Labels: auto-backport, v8.10.0, v8.11.0.0

#1526 [GMail] Pass subject RCF value to Google Directory client
  connectors/sources/gmail.py
  connectors/sources/google.py
  tests/sources/test_google.py
Labels: auto-backport, v8.10.0.0, v8.11.0.0

#1448 [Basic Rules] Debug logging for basic rules validation
  connectors/filtering/basic_rule.py
  connectors/filtering/validation.py
  tests/filtering/test_basic_rule.py
Labels: auto-backport, v8.10.0.0, v8.11.0.0

#1467 [SPO] Remove site_group_id and site_user_id
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.11.0.0

#1533 [GMail/GDrive] Make validate_service_account_json a common method
  connectors/sources/gmail.py
  connectors/sources/google.py
  connectors/sources/google_drive.py
  tests/sources/test_gmail.py
  tests/sources/test_google.py
Labels: auto-backport, v8.11.0.0

#1535 Update DOCKER docs for 8.10 release
  docs/DOCKER.md
Labels: auto-backport, v8.10.0.0, v8.11.0.0

#1323 Initialise empty RCF values in type-safe way
  connectors/source.py
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_confluence.py
  tests/sources/test_dropbox.py
  tests/sources/test_github.py
  tests/sources/test_gmail.py
  tests/sources/test_jira.py
  tests/sources/test_mysql.py
  tests/sources/test_s3.py
  tests/sources/test_servicenow.py
  tests/sources/test_sharepoint_online.py
  tests/test_source.py
Labels: auto-backport, v8.11.0, v8.11.0.0

#761 Remove value field from connector default RCFs (batch 1)
  connectors/source.py
  connectors/sources/mongo.py
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  tests/sources/fixtures/mssql/connector.json
  tests/sources/fixtures/oracle/connector.json
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/test_mongo.py
  tests/sources/test_mssql.py
  tests/sources/test_mysql.py
  tests/sources/test_oracle.py
  tests/sources/test_postgresql.py
Labels: v8.11.0, v8.11.0.0

#1539 Remove value field from connector default RCFs (batch 2)
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/github.py
  connectors/sources/network_drive.py
  connectors/sources/servicenow.py
  tests/sources/fixtures/azure_blob_storage/connector.json
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_confluence.py
  tests/sources/test_dropbox.py
  tests/sources/test_github.py
  tests/sources/test_network_drive.py
  tests/sources/test_servicenow.py
Labels: v8.11.0, v8.11.0.0

#1540 Remove value field from connector default RCFs (batch 3)
  connectors/sources/gmail.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/onedrive.py
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/test_gmail.py
  tests/sources/test_google_cloud_storage.py
  tests/sources/test_google_drive.py
  tests/sources/test_jira.py
Labels: v8.11.0, v8.11.0.0

#1485 [Microsoft SQL] Advanced Sync rules
  README.md
  connectors/sources/generic_database.py
  connectors/sources/mssql.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  docs/sync-rules/MSSQL.md
  tests/sources/test_generic_database.py
  tests/sources/test_mssql.py
Labels: auto-backport, team:external, v8.11.0, v8.11.0.0

#1541 Remove value field from connector default RCFs (batch 4)
  connectors/sources/s3.py
  connectors/sources/salesforce.py
  connectors/sources/sharepoint_online.py
  connectors/sources/sharepoint_server.py
  connectors/sources/slack.py
  tests/sources/fixtures/README.md
  tests/sources/fixtures/s3/connector.json
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/test_s3.py
  tests/sources/test_sharepoint_online.py
  tests/sources/test_sharepoint_server.py
Labels: v8.11.0, v8.11.0.0

#1504 [New Connector] Zoom Implementation
  connectors/config.py
  connectors/sources/zoom.py
  tests/sources/test_zoom.py
Labels: auto-backport, team:external, v8.11.0, zoom, v8.11.0.0

#1543 [New Connector] Zoom Functional test
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/zoom.py
  tests/sources/fixtures/zoom/.env
  tests/sources/fixtures/zoom/Dockerfile
  tests/sources/fixtures/zoom/config.yml
  tests/sources/fixtures/zoom/connector.json
  tests/sources/fixtures/zoom/docker-compose.yml
  tests/sources/fixtures/zoom/fixture.py
  tests/sources/fixtures/zoom/requirements.txt
Labels: team:external, v8.11.0, zoom

#1546 [Setup] Fix team name
  setup.py
Labels: v8.10.0.0

#1537 [DOCS] Update README.md
  README.md
Labels: auto-backport, v8.9.0, v8.10.0, v8.11.0.0

#1547 [GMail] Add include_spam_and_trash RCF
  connectors/sources/gmail.py
  connectors/sources/google.py
  tests/sources/test_gmail.py
Labels: auto-backport, v8.11.0.0

#1549 [FakeSource] Adjust name
  tests/fake_sources.py
  tests/test_cli.py
Labels: auto-backport, v8.11.0.0

#1550 [8.10] [DOCS] Update README.md (#1537)
  README.md
Labels: backport

#1545 Fix slack time range error
  connectors/sources/slack.py
  tests/sources/test_slack.py
Labels: auto-backport, v8.10.0, v8.11.0.0

#1483 [OneDrive] Add sync rules
  connectors/sources/onedrive.py
  docs/sync-rules/ONEDRIVE.md
  tests/sources/test_onedrive.py
Labels: auto-backport, v8.11.0.0

#1552 Revert removed boolean `value` fields
  connectors/sources/confluence.py
  connectors/sources/github.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/postgresql.py
Labels: v8.11.0, v8.11.0.0

#1548 [Setup] Use team email as author email
  setup.py
Labels: auto-backport, v8.10.0.0, v8.11.0.0
