Repository elastic/connectors, pull requests merged in 2023-01, with the labels that each got.

#267 [Filtering] Add BasicRuleEngine to execute a list of rules against a document
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
Labels: auto-backport, v8.7.0.0

#269 [Filtering] Add BasicRuleNoMatchAllRegexValidator
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
Labels: auto-backport, v8.7.0.0

#270 [Filtering] Add BasicRuleSetSemanticValidator
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
Labels: auto-backport, v8.7.0.0

#276 added convert_to_b64
  Makefile
  connectors/tests/test_utils.py
  connectors/utils.py
  requirements/framework.txt
Labels: auto-backport, v8.7.0.0

#277 [Makefile] Add 'bin/elastic-ingest' command to 'install' command
  Makefile
Labels: v8.7.0.0

#279 adds concurency in lazy download
  connectors/byoc.py
  connectors/byoei.py
  connectors/source.py
  connectors/tests/fake_sources.py
  connectors/tests/test_byoc.py
  connectors/utils.py
  docs/CONFIG.md
Labels: v8.7.0.0

#283 use convert_to_b64 for system level encoding
  connectors/sources/gcs.py
Labels: auto-backport, v8.7.0.0

#291 Update elasticsearch client to 8.6.0
  requirements/framework.txt
Labels: v8.7.0, v8.7.0.0

#287 Fix configuration values sent to Kibana
  connectors/byoc.py
  connectors/services/sync.py
  connectors/source.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/tests/test_gcs.py
  connectors/tests/test_byoc.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.6.0

#290 [MySQL] Update document key as database_table_column
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.7.0.0

#294 [8.6] Fix configuration values sent to Kibana (#287)
  connectors/byoc.py
  connectors/runner.py
  connectors/source.py
  connectors/sources/directory.py
  connectors/sources/mysql.py
  connectors/tests/test_byoc.py
  connectors/tests/test_source.py
Labels: backport

#266 Document S3 and network drives connectors
  docs/DEVELOPING.md
Labels: auto-backport, v8.6.0, v8.7.0.0

#298 Remove password log line
  connectors/es/client.py
Labels: v8.5.0, auto-backport, v8.6.0, v8.5.2, v8.7.0

#303 [8.6] [new connector] AWS S3 (#151)
  config.yml
  connectors/sources/aws.py
  connectors/sources/s3.py
  connectors/sources/tests/fixtures/s3/Makefile
  connectors/sources/tests/fixtures/s3/docker-compose.yml
  connectors/sources/tests/fixtures/s3/load_storage.py
  connectors/sources/tests/fixtures/s3/remove.py
  connectors/sources/tests/test_aws.py
  connectors/sources/tests/test_s3.py
Labels: backport

#300 add pull request checklist items
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.6.0, v8.7.0, v8.7.0.0

#301 Fix log message
  connectors/es/client.py
Labels: auto-backport, v8.7.0.0

#308 [8.5] Fix log message (#301)
  connectors/utils.py
Labels: backport

#309 [8.6] Fix log message (#301)
  connectors/utils.py
Labels: backport

#280 [Filtering] Persist filtering in .elastic-connectors-sync-jobs
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0.0

#305 [8.6] Implement the nightly functional test (#258)
  .buildkite/nightly.yml
  .buildkite/run_nigthly.sh
  connectors/sources/tests/fixtures/README.md
  connectors/sources/tests/fixtures/fixture.py
  connectors/sources/tests/fixtures/mysql/Makefile
  connectors/sources/tests/fixtures/mysql/fixture.py
  connectors/sources/tests/fixtures/mysql/remove.py
  connectors/sources/tests/fixtures/mysql/requirements.txt
  connectors/sources/tests/fixtures/network_drive/Makefile
  connectors/sources/tests/fixtures/network_drive/docker-compose.yml
  connectors/sources/tests/fixtures/network_drive/fixture.py
  connectors/sources/tests/fixtures/network_drive/remove.py
  connectors/sources/tests/fixtures/network_drive/requirements.txt
  connectors/sources/tests/fixtures/s3/Makefile
  connectors/sources/tests/fixtures/s3/docker-compose.yml
  connectors/sources/tests/fixtures/s3/fixture.py
  connectors/sources/tests/fixtures/s3/remove.py
  connectors/sources/tests/fixtures/s3/requirements.txt
  connectors/tests/ftest.sh
Labels: backport

#312 Simplify the __init__ for BaseDataSource
  connectors/byoc.py
  connectors/source.py
  connectors/sources/abs.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/tests/support.py
  connectors/sources/tests/test_gcs.py
  connectors/tests/fake_sources.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.7.0.0

#314 pin all deps
  requirements/aarch64.txt
  requirements/framework.txt
  requirements/x86_64.txt
Labels: auto-backport, v8.6.0, v8.7.0.0

#295 reimplemented the MemQueue class to avoid unordered inserts
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: v8.7.0.0

#288 Add Config module
  connectors/cli.py
  connectors/config.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/test_config.py
  connectors/tests/test_sync.py
Labels: v8.7.0

#319 the conversion for bool=false is broken
  connectors/source.py
  connectors/sources/mysql.py
  connectors/tests/test_source.py
Labels: bug, auto-backport, v8.6.0, v8.7.0.0

#323 [8.6] the conversion for bool=false is broken (#319)
  connectors/source.py
  connectors/tests/test_source.py
Labels: backport

#327 Fix test_config.py
  connectors/tests/test_config.py
Labels: auto-backport, v8.7.0.0

#318 fix macOS specific issue
  connectors/sources/abs.py
  connectors/sources/gcs.py
  connectors/utils.py
Labels: auto-backport, v8.7.0.0

#328 removed guppy and tracemem
  config.yml
  connectors/services/sync.py
  connectors/tests/test_sync.py
  connectors/utils.py
  requirements/framework.txt
Labels: v8.7.0.0

#329 forgot to remove _snapshot
  connectors/utils.py
Labels: v8.7.0.0

#330 Fix test_config.py
  connectors/tests/test_config.py
Labels: v8.7.0

#321 [Filtering] Execute filtering validation pre-sync
  connectors/filtering/basic_rule.py
  connectors/filtering/validation.py
  connectors/services/sync.py
  connectors/source.py
  connectors/tests/config.yml
  connectors/tests/fake_sources.py
  connectors/tests/test_basic_rule.py
  connectors/tests/test_source.py
  connectors/tests/test_sync.py
  connectors/tests/test_validation.py
Labels: auto-backport, v8.7.0.0

#333 [ABS] Add concurrent_downloads option & archive check
  connectors/sources/abs.py
  connectors/sources/tests/test_abs.py
Labels: v8.7.0.0

#334 dont send huge sql queries in load()
  connectors/sources/tests/fixtures/mysql/fixture.py
Labels: auto-backport, v8.6.0, v8.7.0.0

#297 Extract preflight check from SyncService
  connectors/byoc.py
  connectors/cli.py
  connectors/conftest.py
  connectors/preflight_check.py
  connectors/services/sync.py
  connectors/tests/test_cli.py
  connectors/tests/test_preflight_check.py
  connectors/tests/test_sync.py
Labels: v8.7.0, v8.7.0.0

#310 Remove language_code and analysis_icu from config
  config.yml
  connectors/byoc.py
  connectors/byoei.py
  connectors/es/__init__.py
  connectors/es/settings.py
  connectors/kibana.py
  connectors/tests/config.yml
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_es_settings.py
  connectors/tests/test_kibana.py
  connectors/tests/test_sync.py
  docs/CONFIG.md
Labels: v8.7.0.0

#336 [8.6] Add perf8 integration (#191)
  Makefile
  connectors/sources/tests/fixtures/mysql/fixture.py
  connectors/tests/ftest.sh
  requirements/framework.txt
  requirements/tests.txt
Labels: backport

#343 Speed up test_preflight_check.py tests
  connectors/tests/test_preflight_check.py
Labels: v8.7.0.0

#347 Fix one flaky test relying on time
  connectors/tests/test_utils.py
  requirements/tests.txt
Labels: v8.7.0.0

#337 Refactor services
  connectors/cli.py
  connectors/services/base.py
  connectors/services/sync.py
  connectors/tests/test_sync.py
Labels: v8.7.0

#348 Update data source __doc__
  connectors/source.py
  connectors/sources/abs.py
  connectors/sources/gcs.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
Labels: auto-backport, v8.7.0, v8.7.0.0

#350 testing a github issue copying app
  .github/issue-up.yml
Labels: auto-backport, v8.7.0.0

#353 fix typo
  .github/issue-up.yml
Labels: auto-backport, v8.7.0.0

#355 Delete issue-up.yml
  .github/issue-up.yml
Labels: auto-backport, v8.7.0.0

#344 Speed up test_es_client.py and test_utils.py slow tests
  connectors/tests/test_es_client.py
  connectors/tests/test_utils.py
Labels: v8.7.0.0

#367 [Performance] Speed up sync tests
  connectors/tests/test_sync.py
Labels: auto-backport, v8.7.0.0

#357 fix deprecation
  connectors/preflight_check.py
Labels: auto-backport, v8.7.0.0

#332 Add SyncJobIndex
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.7.0, v8.7.0.0

#368 Add pytest plugin to fail tests that are too slow
  Makefile
  connectors/tests/test_utils.py
  requirements/tests.txt
Labels: auto-backport, v8.7.0.0

#370 [Typos] Fix some typos
  connectors/byoc.py
  connectors/byoei.py
Labels: v8.7.0.0

#369 [Filtering] Respect filtering feature flags (backwards compatible)
  connectors/byoc.py
  connectors/byoei.py
  connectors/services/sync.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_sync.py
  connectors/tests/test_utils.py
Labels: v8.7.0.0

#366 Certificate verify error is thrown when syncing S3
  docs/DEVELOPING.md
Labels: auto-backport, v8.7.0.0

#365 Add guidance on what permissions are necessary for the S3 connector in an IAM policy
  docs/DEVELOPING.md
Labels: auto-backport, v8.6.0, v8.7.0.0

#299 [new connector] Generic Database Connector (PostgreSQL, Oracle)
  .buildkite/nightly.yml
  config.yml
  connectors/source.py
  connectors/sources/generic_database.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/tests/fixtures/oracle/docker-compose.yml
  connectors/sources/tests/fixtures/oracle/fixture.py
  connectors/sources/tests/fixtures/oracle/requirements.txt
  connectors/sources/tests/fixtures/postgresql/docker-compose.yml
  connectors/sources/tests/fixtures/postgresql/fixture.py
  connectors/sources/tests/fixtures/postgresql/requirements.txt
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_oracle.py
  connectors/sources/tests/test_postgresql.py
  requirements/framework.txt
Labels: auto-backport, v8.7.0.0

#338 [GCS] Update Pinned version and change method name
  connectors/sources/tests/fixtures/gcs/fixture.py
  requirements/framework.txt
Labels: v8.7.0.0

#379 [Performance] Fix and speed up test in MySQL tests
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.7.0.0

#381 [Refactoring] Remove duplicate serialize method
  connectors/source.py
  connectors/sources/mysql.py
Labels: auto-backport, v8.7.0.0

#383 [Fix] Fix test_serialize tests to test the actual logic
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.7.0.0

#378 [Filtering] Add advanced rules filtering to MySQL and extend the BaseDataSource API
  connectors/byoc.py
  connectors/source.py
  connectors/sources/abs.py
  connectors/sources/directory.py
  connectors/sources/gcs.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/s3.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/fake_sources.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.7.0.0

#386 [Fix] Add empty filtering to functional tests and update the default filtering
  connectors/byoc.py
  connectors/kibana.py
  connectors/tests/commons.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
Labels: auto-backport, v8.7.0.0

#317 Add service_type to config file
  config.yml
Labels: auto-backport, v8.6.0, v8.7.0.0

#388 Fix mongodb functional test fixture
  config.yml
  connectors/sources/mongo.py
  connectors/sources/tests/fixtures/mongo/Makefile
  connectors/sources/tests/fixtures/mongo/loadsample.sh
  connectors/sources/tests/fixtures/mongodb/docker-compose.yml
  connectors/sources/tests/fixtures/mongodb/fixture.py
  connectors/sources/tests/fixtures/mongodb/requirements.txt
  connectors/sources/tests/test_mongo.py
Labels: auto-backport, v8.7.0.0

#339 Use 8.6 reference for the links in the documentation
  docs/DEVELOPING.md
Labels: auto-backport, v8.6.0, v8.7.0.0

#396 Pin azure-storage-blob version
  requirements/framework.txt
Labels: auto-backport, v8.7.0.0

#394 tweak the user-agent - fixes #377
  connectors/es/client.py
Labels: v8.7.0.0

#389 Create an event loop instead of getting for verify.py
  scripts/verify.py
Labels: v8.7.0.0

#405 [Filtering] Order basic rules in ascending order with respect to the "order" field
  connectors/filtering/basic_rule.py
  connectors/tests/test_basic_rule.py
Labels: v8.7.0.0

#406 [Refactoring] Naming improvements in MySQL and GenericDatabase connectors
  connectors/sources/generic_database.py
  connectors/sources/mysql.py
Labels: auto-backport, v8.7.0.0

#393 Allow concurrent syncs
  config.yml
  connectors/byoc.py
  connectors/services/sync.py
  connectors/tests/config.yml
  connectors/tests/test_sync.py
  connectors/utils.py
  docs/CONFIG.md
Labels: v8.7.0.0

#395 Add support for fetching data all buckets
  connectors/sources/s3.py
  connectors/sources/tests/test_s3.py
  docs/DEVELOPING.md
Labels: auto-backport, v8.6.0, v8.7.0.0
