Repository elastic/connectors, pull requests merged in 2023-11, with the labels that each got.

#1477 Use BoundedSemaphore instead of asyncio.Event to control the max concurrency
  connectors/utils.py
  tests/test_utils.py
Labels: v8.12.0

#1840 Break JobExecutionSerivce to ContentSyncJobExecutionService and AccessControlSyncJobExecutionService
  connectors/cli.py
  connectors/services/__init__.py
  connectors/services/access_control_sync_job_execution.py
  connectors/services/content_sync_job_execution.py
  tests/services/test_access_control_sync_job_execution.py
  tests/services/test_content_sync_job_execution.py
  tests/services/test_job_execution.py
Labels: v8.12.0

#1866 Update DOCKER.md with link to elastic docker registry
  docs/DOCKER.md
  tests/sources/test_sharepoint_online.py
Labels: documentation, auto-backport, v8.12.0.0

#1873 [8.10] Update DOCKER.md with link to elastic docker registry (#1866)
  docs/DOCKER.md
  tests/sources/test_sharepoint_online.py
Labels: backport

#1872 [8.11] Update DOCKER.md with link to elastic docker registry (#1866)
  docs/DOCKER.md
  tests/sources/test_sharepoint_online.py
Labels: backport

#1857 Enable S rule
  .ruff.toml
  connectors/cli.py
  connectors/sources/directory.py
  connectors/sources/dropbox.py
  connectors/sources/microsoft_teams.py
  connectors/sources/outlook.py
  connectors/sources/s3.py
  connectors/sources/salesforce.py
  connectors/utils.py
Labels: auto-backport, v8.12.0.0

#1863 Clean up unused code
  connectors/es/client.py
  connectors/es/sink.py
  connectors/filtering/basic_rule.py
  connectors/filtering/validation.py
  connectors/kibana.py
  connectors/sources/dropbox.py
  connectors/sources/gmail.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/mysql.py
  connectors/sources/sharepoint_online.py
  connectors/sources/slack.py
  tests/filtering/test_basic_rule.py
  tests/sources/test_mysql.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.12.0.0

#1338 [DOCS] `s/on-prem/self-managed`
  docs/DOCKER.md
Labels: documentation, auto-backport, v8.9.0, v8.10.0.0, v8.11.0, v8.11.0.0, v8.12.0.0

#1875 [DOCS] Update CONTRIBUTING.md, DEVELOPING.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
Labels: documentation, auto-backport, v8.10.0.0, v8.10.0, v8.11.0, v8.11.0.0, v8.12.0.0

#1892 [DOCS] Delete prerelease refs that now live in Elastic docs
  docs/reference/README.md
  docs/reference/box.md
  docs/reference/dropbox.md
  docs/reference/github.md
  docs/reference/microsoft_teams.md
  docs/reference/onedrive.md
  docs/reference/outlook.md
  docs/reference/slack.md
  docs/reference/zoom.md
  docs/sync-rules/CONFLUENCE.md
  docs/sync-rules/DROPBOX.md
  docs/sync-rules/GITHUB.md
  docs/sync-rules/GMAIL.md
  docs/sync-rules/JIRA.md
  docs/sync-rules/MSSQL.md
  docs/sync-rules/MYSQL.md
  docs/sync-rules/NETWORK_DRIVE.md
  docs/sync-rules/ONEDRIVE.md
  docs/sync-rules/POSTGRESQL.md
  docs/sync-rules/SERVICENOW.md
Labels: auto-backport, v8.11.0, v8.11.0.0, v8.12.0.0, v8.11.1

#1894 Add config for telemetry
  config.yml
  connectors/config.py
Labels: v8.12.0, v8.12.0.0

#1897 bump version after 8.11.1 release
  connectors/VERSION
  tests/ftest.sh
Labels: v8.11.1.1

#1902 [8.10] [DOCS] Update CONTRIBUTING.md, DEVELOPING.md (#1875)
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
Labels: backport

#1901 [8.11] [DOCS] Update CONTRIBUTING.md, DEVELOPING.md (#1875)
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
Labels: backport

#1839 Add support for DLS in Dropbox
  connectors/sources/dropbox.py
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/test_dropbox.py
Labels: auto-backport, team:external, v8.12.0.0

#1898 Specify port when calling all smbclient methods in network drive connector
  connectors/sources/network_drive.py
Labels: auto-backport, v8.12.0.0

#1884 [SPO] Adding OData__UIVersionString document version field
  connectors/sources/sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.12.0.0, v8.11.1, v8.10.5

#1899 [Oracle] Update Labels
  connectors/sources/oracle.py
  tests/sources/fixtures/oracle/connector.json
Labels: auto-backport, v8.12.0.0

#1907 Remove timestamp optimization for full syncs
  connectors/es/sink.py
  tests/test_sink.py
Labels: release_note, auto-backport, v8.12.0, v8.12.0.0, v8.10.5, v8.11.2

#1913 Make service_account_credentials RCF sensitive
  connectors/sources/gmail.py
  connectors/sources/google_cloud_storage.py
Labels: v8.12.0, v8.12.0.0

#1911 Bump Dockerfile base image to python:3.11.6-slim
  Dockerfile
  Dockerfile.ftest
Labels: auto-backport, v8.12.0.0

#1914 Add Documentation for DLS in Dropbox
  docs/document-level-security/DROPBOX.md
Labels: auto-backport, v8.12.0.0

#1889 Extend a non-blocking Semaphore implementation
  connectors/utils.py
  tests/test_utils.py
Labels: v8.12.0

#1918 [DOCS] Delete DLS docs, now available in main docs
  docs/document-level-security/CONFLUENCE.md
  docs/document-level-security/JIRA.md
  docs/document-level-security/NETWORK_DRIVE.md
  docs/document-level-security/ONEDRIVE.md
Labels: auto-backport, v8.11.0, v8.11.0.0, v8.12.0, v8.12.0.0, v8.11.1, v8.11.1.1

#1920 [8.11] [DOCS] Delete DLS docs, now available in main docs (#1918)
  docs/document-level-security/CONFLUENCE.md
  docs/document-level-security/JIRA.md
  docs/document-level-security/NETWORK_DRIVE.md
  docs/document-level-security/ONEDRIVE.md
Labels: backport

#1479 Add non-blocking try_put method to ConcurrentTasks
  connectors/utils.py
  tests/test_utils.py
Labels: v8.12.0

#1926 Revert "Add config for telemetry"
  config.yml
  connectors/config.py
Labels: v8.12.0.0

#1928 Update ACL index name pattern
  connectors/protocol/connectors.py
Labels: release_note, v8.12.0, v8.12.0.0

#1921 [S3] Advanced Sync rules
  connectors/sources/s3.py
  tests/sources/test_s3.py
Labels: auto-backport, v8.12.0.0

#1616 Connectors CLI tool
  .gitignore
  connectors/cli/.gitkeep
  connectors/cli/auth.py
  connectors/cli/connector.py
  connectors/cli/index.py
  connectors/cli/job.py
  connectors/connectors_cli.py
  connectors/es/client.py
  connectors/service_cli.py
  requirements/framework.txt
  setup.py
  tests/test_connectors_cli.py
  tests/test_service_cli.py
Labels: release_note, auto-backport, v8.12.0, v8.12.0.0

#1931 Skip empty permission batches
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: release_note, auto-backport, v8.12.0, v8.12.0.0, v8.10.5, v8.11.2

#1923 Added DLS For GitHub
  connectors/sources/github.py
  tests/sources/fixtures/github/connector.json
  tests/sources/test_github.py
Labels: auto-backport, v8.12.0.0
