Repository elastic/connectors, pull requests merged in 2023-12, with the labels that each got.

#1916 [OneDrive] Improve performance with DLS enabled
  connectors/sources/onedrive.py
  tests/sources/fixtures/onedrive/fixture.py
  tests/sources/test_onedrive.py
Labels: auto-backport, v8.12.0.0

#1943 [8.11] [GitHub] Add missing re-raise on ClientResponseError (#1806)
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: backport

#1944 add RCF+kibana PR checklist item
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.12.0.0

#1936 Documentation for S3 sync rules
  docs/sync-rules/s3.md
Labels: auto-backport, v8.12.0.0

#1945 Ensure that Exceptions with empty error messages at least state the exception
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: release_note, auto-backport, v8.12.0, v8.12.0.0, v8.11.3

#1938 [Salesforce] Add custom objects and fields support via Advanced Sync Rules
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: release_note, auto-backport, team:external, salesforce, v8.12.0, v8.12.0.0

#1954 [Connectors API] Add postman collection
  resources/connectors_api/Connectors API.postman_collection.json
  resources/connectors_api/README.md
Labels: auto-backport, v8.12.0.0

#1960 Bump stack version 8.11.2
  connectors/VERSION
Labels: v8.11.2

#1940 Use default configs in config module
  config.yml
  connectors/services/access_control_sync_job_execution.py
  connectors/services/content_sync_job_execution.py
  tests/services/test_content_sync_job_execution.py
Labels: auto-backport, v8.12.0, v8.12.0.0

#1967 [CLI] Fix typo in connector create command
  connectors/connectors_cli.py
Labels: auto-backport, v8.12.0, v8.13.0.0

#1961 Update VERSION for 8.11.3 release
  connectors/VERSION
Labels: v8.11.3

#1953 Add some logging to github connector for debugging
  connectors/sources/github.py
Labels: auto-backport, v8.12.0, v8.12.0.0, v8.11.3

#1971 [8.11] Add some logging to github connector for debugging (#1953)
  connectors/sources/github.py
Labels: backport

#1956 [GitHub] DLS documentation
  docs/document-level-security/GITHUB.md
Labels: documentation, team:external, github, v8.12.0

#1949 [Salesforce] Advanced Sync Rules documentation
  docs/sync-rules/SALESFORCE.md
Labels: auto-backport, team:external, salesforce, v8.12.0, v8.12.0.0

#1935 Fix issue for skipping buckets for GCS and ABS if it doesn't have access
  connectors/sources/azure_blob_storage.py
  connectors/sources/google_cloud_storage.py
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_google_cloud_storage.py
Labels: auto-backport, v8.12.0.0

#1978 Fix job cleanup calling fail with wrong argument
  connectors/services/job_cleanup.py
  tests/services/test_job_cleanup.py
Labels: auto-backport, v8.12.0, v8.13.0.0

#1986 [8.10] [SPO] Fix bugs when handling drive_items in incremental sync (#1827)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1991 [CLI] Add a command to show specific job informaton
  connectors/cli/job.py
  connectors/connectors_cli.py
  connectors/protocol/connectors.py
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#1990 check if DLS is enabled before fetching drive item permissions
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, v8.12.0, v8.13.0.0, v8.11.4

#1992 Ignore errors when Sink or Extractor is forcibly canceled
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v8.12.0, v8.13.0.0

#1993 Make test fixture retry 429 errors
  tests/sources/fixtures/fixture.py
Labels: auto-backport, v8.13.0.0

#2001 [CLI] Remove blink=True
  connectors/connectors_cli.py
Labels: auto-backport, v8.12.0, v8.13.0.0

#2005 [MySQL] Remove duplicate PK check in advanced sync rules
  connectors/sources/mysql.py
Labels: auto-backport, v8.12.0, v8.12.0.0, v8.12.1

#2008 [8.11] [MySQL] Remove duplicate PK check in advanced sync rules (#2005)
  connectors/sources/mysql.py
Labels: backport

#1999 Refactor ES Client methods
  connectors/cli/auth.py
  connectors/cli/connector.py
  connectors/cli/index.py
  connectors/cli/job.py
  connectors/es/client.py
  connectors/es/index.py
  connectors/preflight_check.py
  connectors/protocol/connectors.py
  connectors/services/job_cleanup.py
  tests/es/test_client.py
  tests/protocol/test_connectors.py
  tests/services/test_job_cleanup.py
  tests/sources/fixtures/fixture.py
  tests/test_connectors_cli.py
  tests/test_preflight_check.py
Labels: auto-backport, v8.13.0.0

#1989 [ServiceNow] Add DLS for ServiceNow
  connectors/sources/servicenow.py
  tests/sources/fixtures/servicenow/connector.json
  tests/sources/test_servicenow.py
Labels: auto-backport, servicenow, team:external, v8.13.0.0

#2010 Include fixture.py into diff for all pipeline tests
  .buildkite/pipeline.yml
Labels: auto-backport, v8.12.1, v8.13.0.0, v8.11.4

#2009 Make fixtures async
  tests/sources/fixtures/azure_blob_storage/fixture.py
  tests/sources/fixtures/dir/fixture.py
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/google_cloud_storage/fixture.py
  tests/sources/fixtures/mongodb/fixture.py
  tests/sources/fixtures/mongodb_serverless/fixture.py
  tests/sources/fixtures/mssql/fixture.py
  tests/sources/fixtures/mysql/fixture.py
  tests/sources/fixtures/network_drive/fixture.py
  tests/sources/fixtures/oracle/fixture.py
  tests/sources/fixtures/postgresql/fixture.py
  tests/sources/fixtures/s3/fixture.py
Labels: auto-backport, v8.12.1, v8.13.0.0

#2007 [PostgreSQL] Remove duplicate PK check in advanced sync rules
  connectors/sources/postgresql.py
Labels: auto-backport, v8.11.0, v8.11.0.0, v8.12.0, v8.12.0.0, v8.12.1, v8.13.0.0

#1556 [8.10] [GMail] Consider RCF configuration value in dls_enabled check (#1555)
  connectors/sources/gmail.py
  tests/test_gmail.py
Labels: backport
