Repository elastic/connectors, pull requests merged in 2023-07, with the labels that each got.

#1148 Improve logging
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1151 [MS-SQL] Add Support for multiple SSL Certificates
  connectors/sources/generic_database.py
  connectors/sources/mssql.py
  tests/sources/test_mssql.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1156 [SPO] Update DLS implementation
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1171 [8.9] [SPO] Update DLS implementation (#1156)
  connectors/sources/sharepoint_online.py
  tests/conftest.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1172 [SPO] Remove domain group id suffixes starting with "_"
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1140 Use a global variable to hold cli loaded config
  connectors/cli.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1181 Fix missing await for _site_access_control in get_docs_incrementally for Sharepoint Online connector
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1178 Close data source after running a validation
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1180 Add more verbose messages why drive item is not downloaded for SPO connector
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1189 Fix Warnings in tests
  tests/sources/test_confluence.py
  tests/sources/test_jira.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1137 [SharePoint Server]Add remote validation for site collection
  connectors/sources/sharepoint_server.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, v8.9.0, team:external, v8.10.0.0

#1179 Make SPO validate configuration before doing custom validation
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1131 [Google Drive] Connector implementation
  .buildkite/nightly_steps.yml
  config.yml
  connectors/sources/google_drive.py
  requirements/framework.txt
  tests/sources/fixtures/google_drive/.env
  tests/sources/fixtures/google_drive/Dockerfile
  tests/sources/fixtures/google_drive/config.yml
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/google_drive/fixture.py
  tests/sources/fixtures/google_drive/requirements.txt
  tests/sources/test_google_drive.py
Labels: v8.10.0.0, v8.10.0

#1198 Remove unused instance variable _dirty
  connectors/sources/mongo.py
Labels: v8.10.0.0, v8.10.0

#1158 Stream files for data extraction
  connectors/utils.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.9.0.0, v8.10.0.0

#1200 [SPO] Make sure that temporary files are deleted
  connectors/sources/sharepoint_online.py
Labels: bug, auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1207 Bump ftest version
  tests/ftest.sh
Labels: auto-backport, v8.10.0.0

#1206 [Google Drive] Use try/except/finally clauses when operating on NamedTemporaryFile
  connectors/sources/google_drive.py
Labels: bug, team:ingestion, v8.10.0.0

#1197 Add support for multi certificate
  connectors/sources/google_cloud_storage.py
  connectors/sources/mssql.py
  connectors/sources/postgresql.py
  connectors/utils.py
  tests/sources/test_mssql.py
  tests/test_utils.py
Labels: auto-backport, v8.10.0.0

#1201 Filter domain groups to federateddirectoryclaimprovider only
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1211 Make Sharepoint Online connector retry only specific errors
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0

#1213 Ignore deleted files when choosing a download function
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: bug, auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1186 Add content extraction support for upper case extensions
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_confluence.py
  tests/sources/test_google_cloud_storage.py
  tests/sources/test_jira.py
  tests/sources/test_network_drive.py
  tests/sources/test_s3.py
  tests/sources/test_servicenow.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1209 Disable MongoDB serverless nightly + max-rss setting
  .buildkite/nightly_steps.yml
  tests/ftest.sh
Labels: auto-backport, v8.9.0, v8.8.0, v8.10.0.0

#1205 Remove duplicate reference documents
  docs/REFERENCE.md
  docs/reference/confluence.md
  docs/reference/jira.md
  docs/reference/servicenow.md
  docs/reference/sharepoint_server.md
Labels: auto-backport, v8.9.0, v8.10.0.0

#1226 [Fix] Specify the job type when starting a sync
  connectors/sync_job_runner.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1223 [8.9] Remove duplicate refrence documents (#1205)
  docs/REFERENCE.md
  docs/reference/confluence.md
  docs/reference/jira.md
  docs/reference/servicenow.md
  docs/reference/sharepoint_server.md
Labels: backport

#1104 [Dropbox] Documentation for Dropbox connector
  docs/reference/dropbox.md
Labels: auto-backport, v8.9.0, team:external, dropbox, v8.10.0.0

#1228 [Sync Job] Make job_type parameter mandatory for sync starts
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  tests/protocol/test_connectors.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1220 Make access control strategy configurable
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1236 Get filename for all attachments
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.9.0.0, v8.10.0.0

#1219 Allow file pointers for local data extraction
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.9.0.0, v8.10.0.0

#1239 Change RCF label and tooltip based on feedback
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1240 Do not download unsupported files
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1230 [Google Drive] Add connector documentation
  docs/reference/google_drive.md
Labels: documentation, v8.10.0.0

#1246 Extend Tika supported file types list
  connectors/utils.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1250 Fix Ftest in Network Drive connector
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.9.0, v8.8.0, v8.10.0.0

#1253 Temporarily revert "[Google Drive] Add connector documentation (#1230)"
  docs/reference/google_drive.md
Labels: v8.10.0.0

#1242 Add extraction service to CONFIG.md
  docs/CONFIG.md
Labels: auto-backport, v8.9.0, v8.9.0.0, v8.10.0.0

#1244 [Dropbox] Fix reference docs relative links 404s
  docs/reference/dropbox.md
Labels: v8.10.0.0

#1233 [Dropbox] Implement E2E Feature
  .buildkite/nightly_steps.yml
  tests/sources/fixtures/dropbox/.env
  tests/sources/fixtures/dropbox/Dockerfile
  tests/sources/fixtures/dropbox/config.yml
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/dropbox/fixture.py
  tests/sources/fixtures/dropbox/requirements.txt
Labels: v8.9.0, team:external, dropbox, v8.10.0

#1260 [SPO] Fix unreachable assertions in drive items delta test
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1255 Performance improvements to the ACL sync
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1267 [8.9] Performance improvements to the ACL sync (#1255)
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: backport

#1266 Use blocklist for retry policy + make user of aiohttp limiter
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1273 [SPO] Limit synced fields
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1280 [SPO] Logs improvements
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1270 Support multiple connectors in services
  connectors/preflight_check.py
  connectors/protocol/connectors.py
  connectors/services/base.py
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  tests/protocol/test_connectors.py
  tests/services/test_base.py
  tests/test_preflight_check.py
Labels: v8.10.0.0, v8.10.0

#1177 Dropbox connector code with AioHTTP
  connectors/sources/dropbox_aiohttp.py
  tests/sources/test_dropbox_aiohttp.py
Labels: auto-backport, v8.9.0, team:external, dropbox, v8.10.0.0, v8.10.0

#1282 [SPO] Tune download/write chunk size
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0

#1259 [SPO] Add configurable drive item permissions support
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1284 Add backport automations for the pre-8.10 branch
  .backportrc.json
Labels: auto-backport, v8.10.0.0

#1264 [SPO] Add configurable unique page permissions support
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1287 [pre-8.10-stable] [SPO] Add configurable drive item permissions support (#1259)
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: backport

#1292 [pre-8.10-stable] [SPO] Add configurable unique page permissions support (#1264)
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: backport

#1283 [Google Drive] Obfuscate Service account JSON in the UI
  connectors/sources/google_drive.py
  tests/sources/fixtures/google_drive/connector.json
Labels: v8.10.0.0

#1286 [Dropbox] Replace dropbox SDK files with AioHTTP files
  connectors/sources/dropbox.py
  connectors/sources/dropbox_aiohttp.py
  tests/sources/test_dropbox.py
  tests/sources/test_dropbox_aiohttp.py
Labels: v8.9.0, team:external, dropbox, v8.10.0

#1289 [GitHub] GraphQL implementation
  connectors/sources/github_graphql.py
  tests/sources/test_github_graphql.py
Labels: team:external, github, v8.10.0

#1305 Remove race condition when killing ingest processes
  tests/ftest.sh
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0, vpre-8.10-stable

#1306 [SPO] Add unique list permissions support
  connectors/sources/sharepoint_online.py
  tests/commons.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
  tests/test_commons.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1302 [SPO] Put dynamic group check into correct context
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1301 [SPO] Remove duplicate test decorator
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1300 [SPO] Deduplicate test name
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1257 [Google Drive] DLS implementation
  connectors/sources/google_drive.py
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/test_google_drive.py
Labels: v8.10.0.0

#1274 [Google Drive] Add docs for Google Drive DLS
  docs/reference/google_drive.md
Labels: v8.10.0.0

#1315 [Google Drive] Use async os stat operation to check file size
  connectors/sources/google_drive.py
Labels: v8.10.0.0

#1294 [OneDrive] Add ping functionality
  config.yml
  connectors/sources/onedrive.py
  tests/sources/test_onedrive.py
Labels: onedrive, v8.10.0.0

#1309 Freezing requirement versions for tests
  requirements/tests.txt
Labels: auto-backport, v8.9.0, v8.10.0.0, v8.10.0, vpre-8.10-stable

#1318 [Sharepoint Server] Use AsyncIterator in tests and remove AsyncIter class
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, v8.10.0.0

#1321 [Google Drive] Remove debug print() statement
  connectors/sources/google_drive.py
Labels: v8.10.0.0

#1279 Allow override ROOT for SPO ftest
  tests/sources/fixtures/sharepoint_online/fixture.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1269 Make files HTML with large binary garbage to increase file size
  tests/sources/fixtures/sharepoint_online/fixture.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1299 [SPO] Reduce number of HasUniqueRoleAssignments requests (guard with config)
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1296 [GitHub] Update E2E as per GraphQL Implementation
  tests/sources/fixtures/github/fixture.py
Labels: team:external, github, v8.10.0.0, v8.10.0

#1271 Use new connectors config in tests
  connectors/kibana.py
  tests/fixtures/config.yml
  tests/fixtures/config_2.yml
  tests/fixtures/config_https.yml
  tests/fixtures/config_mem.yml
  tests/fixtures/memconfig.yml
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/github/config.yml
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/google_drive/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/sharepoint_server/config.yml
Labels: v8.10.0.0, v8.10.0

#1327 Fix GCS ingesting too much in ftest
  tests/sources/fixtures/google_cloud_storage/fixture.py
Labels: auto-backport, v8.9.0, v8.8.0, v8.10.0.0

#1316 [Dropbox] Advanced Sync Rules
  connectors/sources/dropbox.py
  tests/sources/test_dropbox.py
Labels: v8.9.0, team:external, dropbox, v8.10.0

#1335 New config syntax for SPO ftest
  tests/sources/fixtures/sharepoint_online/config.yml
Labels: auto-backport, v8.10.0.0

#1331 [Rich Configurable Fields] Add dev-friendly reference docs
  docs/CONNECTOR_PROTOCOL.md
  docs/DEVELOPING.md
Labels: v8.10.0.0

#1275 Use per-connector api key to sync data if configured
  connectors/services/job_execution.py
  tests/services/test_job_execution.py
Labels: v8.10.0.0, v8.10.0

#1340 Ignore connector configurations with missing connector id
  connectors/services/base.py
  tests/services/test_base.py
Labels: v8.10.0

#1322 [Dropbox] Documentation for Advanced sync rules
  docs/reference/dropbox.md
  docs/sync-rules/DROPBOX.md
Labels: auto-backport, v8.10.0.0

#1336 Dropbox connector with AioHTTP implementation
  .buildkite/nightly_steps.yml
  connectors/sources/dropbox.py
  tests/sources/fixtures/dropbox/.env
  tests/sources/fixtures/dropbox/Dockerfile
  tests/sources/fixtures/dropbox/config.yml
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/dropbox/fixture.py
  tests/sources/fixtures/dropbox/requirements.txt
  tests/sources/test_dropbox.py
Labels: auto-backport, v8.9.0, team:external, dropbox, v8.10.0.0, v8.10.0

#1343 [SPO] Decrease the filesize for SPO ftests to fix nightlies
  tests/sources/fixtures/sharepoint_online/fixture.py
Labels: auto-backport, v8.9.0, v8.9.0.0, v8.10.0.0

#1324 [GitHub] Advanced Sync rules
  README.md
  connectors/sources/github.py
  docs/sync-rules/GITHUB.md
  tests/sources/test_github.py
Labels: team:external, github, v8.10.0

#1348 Fix dropbox ftest config for new structure
  tests/sources/fixtures/dropbox/config.yml
Labels: auto-backport, v8.10.0.0, v8.10.0

#1351 [GitHub] Index markdown files only
  connectors/sources/github.py
  tests/sources/fixtures/github/fixture.py
  tests/sources/test_github.py
Labels: team:external, github, v8.10.0

#1346 Add debug log on successful text extraction
  connectors/utils.py
  tests/test_utils.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1352 [SPO] Change permission inheritance logic for driveItems
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1357 [SPO] Include fix to drive item permissions to incremental sync as well
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1360 [SPO] Propagate site admin access controls by default to site pages
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0, vpre-8.10-stable

#1368 Remove ci skipping
  .buildkite/pull-requests.json
Labels: auto-backport, v8.10.0.0

#1119 [GitHub] Documentation for GitHub connector
  docs/REFERENCE.md
  docs/reference/github.md
Labels: v8.9.0, team:external, github
