Repository elastic/connectors, pull requests merged in 2023-04, with the labels that each got.

#666 [MySQL] Parse tables string to list of tables
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.8.0.0

#648 Update jira configurable fields to new standard
  connectors/sources/jira.py
Labels: v8.8.0.0

#703 [8.7] Make async_bulk a task (#513)
  connectors/byoei.py
  connectors/services/job_scheduling.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoei.py
  connectors/tests/test_sync_job_runner.py
Labels: backport

#706 [8.7] Report ingestion stats during job execution (#515)
  connectors/byoc.py
  connectors/sync_job_runner.py
  connectors/tests/test_byoc.py
  connectors/tests/test_sync_job_runner.py
Labels: backport

#517 Connector service cancels a job during execution
  connectors/sync_job_runner.py
  connectors/tests/test_sync_job_runner.py
Labels: auto-backport, v8.7.0, v8.8.0.0

#705 Rename config fields in confluence
  connectors/sources/confluence.py
  connectors/sources/tests/test_confluence.py
Labels: auto-backport, v8.8.0.0

#680 [MySQL] Remove duplicate database validation
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#704 [MySQL] Separate get_primary_key_columns
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#709 [MySQL] Separate "generate_id" method
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#711 [MySQL] Remove unnecessary database information from ids and docs
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#713 [MySQL] Introduce basic MySQLClient class
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#714 Remove incorrect use of patch_logger
  connectors/sources/tests/test_confluence.py
  connectors/sources/tests/test_directory.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/sources/tests/test_jira.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_mssql.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_network_drive.py
  connectors/sources/tests/test_oracle.py
  connectors/sources/tests/test_postgresql.py
  connectors/sources/tests/test_s3.py
  connectors/sources/tests/test_sharepoint.py
  connectors/tests/test_byoc.py
  connectors/tests/test_byoei.py
  connectors/tests/test_cli.py
  connectors/tests/test_es_client.py
  connectors/tests/test_es_document.py
  connectors/tests/test_es_index.py
  connectors/tests/test_job_cleanup.py
  connectors/tests/test_job_scheduling.py
  connectors/tests/test_sync_job_runner.py
  connectors/tests/test_utils.py
Labels: v8.8.0.0

#710 Add configurable field validations to connector framework
  connectors/source.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#712 Update Confluence configurable fields to new standard
  connectors/sources/confluence.py
Labels: auto-backport, v8.8.0.0

#593 Decouple job execution service
  connectors/cli.py
  connectors/services/__init__.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  connectors/tests/test_job_execution.py
  connectors/tests/test_job_scheduling.py
Labels: v8.8.0.0

#716 [MySQL] Move "ping" method to MySQLClient
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: v8.8.0.0

#715 Add configurable field validations to connector framework 2/2
  connectors/source.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#720 Pass trigger_method explicitly to SyncJobIndex create method
  connectors/byoc.py
  connectors/es/index.py
  connectors/services/job_scheduling.py
  connectors/tests/test_byoc.py
  connectors/tests/test_es_index.py
  connectors/tests/test_job_scheduling.py
Labels: v8.8.0.0

#724 [MySQL] Add "get_column_names" method to MySQLClient
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#722 Add update_by_script method
  connectors/es/index.py
  connectors/tests/test_es_index.py
Labels: v8.8.0.0

#726 [MySQL] Add "get_all_table_names" to "MySQLClient"
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#723 Speed up CI by not sleeping if PERF8 is not enabled
  connectors/tests/ftest.sh
Labels: auto-backport, 8.7, v8.8.0.0

#727 Increase timeout for test_mem_queue
  connectors/tests/test_utils.py
Labels: auto-backport, v8.8.0.0

#728 [8.7] Sleep for 2 minutes only if PERF8 is yes (#723)
  connectors/tests/ftest.sh
Labels: backport

#670 [Jira] Improve the performance of connector
  connectors/sources/jira.py
  connectors/sources/tests/test_jira.py
Labels: auto-backport, v8.8.0.0

#721 [Sync Job] Introduce a hash_id method for ids, which are too long
  connectors/source.py
  connectors/sync_job_runner.py
  connectors/tests/test_sync_job_runner.py
Labels: auto-backport, v8.8.0.0

#717 Remove default values for mongodb default configurable fields
  connectors/sources/mongo.py
  connectors/sources/tests/test_mongo.py
Labels: v8.8.0.0

#725 Use required validation and update ABS to new validations
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/tests/support.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#729 Add last_sync_scheduled_at to Connector class
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.8.0.0

#730 Use update_by_script to reset sync_now flag
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: auto-backport, v8.8.0.0

#731 Make next_run return datetime
  connectors/byoc.py
  connectors/services/job_scheduling.py
  connectors/tests/test_byoc.py
  connectors/tests/test_job_scheduling.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: v8.8.0.0

#732 [Jira] Rename configuration fields
  connectors/sources/jira.py
  connectors/sources/tests/test_jira.py
Labels: auto-backport, v8.8.0.0

#739 [MySQL] Add "get_last_update_time" to MySQLClient
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#745 [Utils] Retryable for async generators
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#743 Set default stats when creating a sync job
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#747 [MySQL] Use get_all_table_names in MySQLDataSource
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#746 [MySQL] Add method fetching rows from a table in batches
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#718 Memory saver: lazy loading of source classes
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  connectors/source.py
  connectors/tests/test_source.py
Labels: auto-backport, v8.8.0.0

#751 Bump Elasticsearch to 8.7.0
  requirements/framework.txt
Labels: auto-backport, v8.8.0.0

#737 Move validations from connector to framework
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/postgresql.py
  connectors/sources/s3.py
  connectors/sources/sharepoint.py
  connectors/sources/tests/test_confluence.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/sources/tests/test_jira.py
  connectors/sources/tests/test_mongo.py
  connectors/sources/tests/test_mysql.py
  connectors/sources/tests/test_s3.py
  connectors/sources/tests/test_sharepoint.py
Labels: v8.8.0.0

#753 [MySQL] Use MySQLClient for interacting with the configured db server
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#755 [MySQL] Remove old data source methods replaced by new MySQLClient methods
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#756 [MySQL] Use CancellableSleeps in MySQLClient
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#754 [MySQL] Fallback on iso_utc, if last_update_time is not present
  connectors/sources/mysql.py
Labels: auto-backport, v8.8.0.0

#733 Refactor validations
  connectors/source.py
  connectors/sources/tests/test_google_cloud_storage.py
  connectors/sources/tests/test_jira.py
Labels: v8.8.0.0

#738 [MySQL] Implement "hash_id" for the MySQLDataSource
  connectors/source.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#741 Make sync_starts use optimistic concurrency control
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#750 Update reset_sync_now_flag
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#736 Add update_last_sync_scheduled_at method
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#759 Use default_value for value when applicable
  connectors/source.py
  connectors/tests/test_source.py
Labels: v8.8.0.0

#677 [Microsoft SQL] Update E2E as per PyTDS library
  connectors/sources/tests/fixtures/mssql/fixture.py
  connectors/sources/tests/fixtures/mssql/requirements.txt
Labels: auto-backport, v8.8.0.0

#647 [Confluence] Documentation for Confluence connector
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#752 [Confluence] Add spaces as a configurable field
  connectors/sources/confluence.py
  connectors/sources/tests/fixtures/confluence/fixture.py
  connectors/sources/tests/test_confluence.py
Labels: auto-backport, v8.8.0.0

#574 [Jira] Documentation for Jira connector
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#772 [Microsoft SQL]Use NamedTemporaryFile for temporary SSL certificate file
  connectors/sources/generic_database.py
  connectors/sources/mssql.py
  connectors/sources/tests/test_generic_database.py
  connectors/sources/tests/test_mssql.py
Labels: auto-backport, 8.7, v8.7.0, v8.8.0.0

#782 [Confluence] Update E2E test for space as configurable field
  connectors/sources/tests/fixtures/confluence/fixture.py
Labels: auto-backport, v8.8.0.0

#784 [Sync Job Runner] Fix log message
  connectors/sync_job_runner.py
Labels: auto-backport, v8.8.0.0

#786 Align aioboto3 version with x86
  requirements/aarch64.txt
Labels: auto-backport, v8.8.0.0

#781 Use unsigned_long for field indexed_document_volume
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.8.0.0

#740 Add concurrency control to job scheduling
  connectors/services/job_scheduling.py
  connectors/tests/test_job_scheduling.py
Labels: v8.8.0.0

#768 Add concurrency control to job execution
  connectors/sync_job_runner.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#777 Add concurrency control to connector validate_filtering method
  connectors/byoc.py
  connectors/tests/test_byoc.py
Labels: v8.8.0.0

#770 Add concurrency control to connector prepare
  connectors/byoc.py
  connectors/services/job_scheduling.py
  connectors/tests/test_byoc.py
  connectors/tests/test_job_scheduling.py
Labels: v8.8.0.0

#790 Sort column names by ORDINAL_POSITION
  connectors/sources/mysql.py
Labels: auto-backport, v8.8.0.0

#791 [MySQL] Support JOIN queries in advanced rules
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#795 Revert "Use unsigned_long for field indexed_document_volume"
  docs/CONNECTOR_PROTOCOL.md
Labels: v8.8.0.0

#793 Execute the oldest sync job first
  connectors/byoc.py
  connectors/es/index.py
  connectors/tests/test_byoc.py
  connectors/tests/test_es_index.py
Labels: v8.8.0.0

#788 Move last_sync_status to Job Execution Service
  connectors/services/job_execution.py
  connectors/sync_job_runner.py
  connectors/tests/test_job_execution.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#797 [MySQL] Make doc id generation more stable using sorted table names/pk columns
  connectors/sources/mysql.py
  connectors/sources/tests/test_mysql.py
Labels: auto-backport, v8.8.0.0

#798 Add MongoDB to nightly runs
  .buildkite/nightly.yml
Labels: auto-backport, v8.8.0.0

#792 Truncate document id when logging it; reduce the message size too
  connectors/sync_job_runner.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0

#800 Round indexed_document_volume
  connectors/byoei.py
Labels: v8.8.0.0

#794 Use custom docker images for our CI
  .buildkite/README.md
  .buildkite/nightly.yml
  .buildkite/pipeline.yml
  .buildkite/run_dockerized_test.sh
  .buildkite/run_nigthly.sh
Labels: auto-backport, 8.7, v8.7.0, v8.8.0.0

#803 [Documentation] Rectify default value of data source in Confluence
  docs/DEVELOPING.md
Labels: auto-backport, v8.8.0.0

#804 Make mongodb instance password-protected and use this password
  connectors/sources/tests/fixtures/mongodb/connector.json
  connectors/sources/tests/fixtures/mongodb/docker-compose.yml
  connectors/sources/tests/fixtures/mongodb/fixture.py
Labels: auto-backport, v8.8.0.0

#802 Parallelise the steps in CI
  .buildkite/pipeline.yml
  .buildkite/run_dockerized_test.sh
  .buildkite/run_nigthly.sh
  connectors/sources/tests/fixtures/fixture.py
Labels: auto-backport, 8.7, v8.8.0.0

#805 Don't set connector/sync job to None when reload fails
  connectors/sync_job_runner.py
  connectors/tests/test_sync_job_runner.py
Labels: v8.8.0.0

#810 Update labels for configurable fields
  connectors/sources/confluence.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/oracle.py
  connectors/sources/s3.py
  connectors/sources/sharepoint.py
  connectors/sources/tests/test_jira.py
Labels: v8.8.0.0

#809 Make connectors respect log level for cloud deployments
  connectors/config.py
  connectors/tests/config.yml
  connectors/tests/entsearch.yml
  connectors/tests/test_config.py
Labels: release_note, auto-backport, 8.7, v8.8.0.0

#812 Increase nightly ES limits to 2GB to avoid memory errors
  connectors/sources/tests/fixtures/azure_blob_storage/docker-compose.yml
  connectors/sources/tests/fixtures/confluence/docker-compose.yml
  connectors/sources/tests/fixtures/dir/docker-compose.yml
  connectors/sources/tests/fixtures/google_cloud_storage/docker-compose.yml
  connectors/sources/tests/fixtures/jira/docker-compose.yml
  connectors/sources/tests/fixtures/mongodb/docker-compose.yml
  connectors/sources/tests/fixtures/mssql/docker-compose.yml
  connectors/sources/tests/fixtures/mysql/docker-compose.yml
  connectors/sources/tests/fixtures/network_drive/docker-compose.yml
  connectors/sources/tests/fixtures/oracle/docker-compose.yml
  connectors/sources/tests/fixtures/postgresql/docker-compose.yml
  connectors/sources/tests/fixtures/s3/docker-compose.yml
  connectors/sources/tests/fixtures/sharepoint/docker-compose.yml
Labels: auto-backport, v8.8.0.0

#813 [8.7] Make connectors respect cloud log level (#809)
  connectors/config.py
  connectors/tests/config.yml
  connectors/tests/entsearch.yml
  connectors/tests/test_config.py
Labels: backport

#816 Use SIGINT to terminate the process from monitor
  connectors/sources/tests/fixtures/fixture.py
Labels: auto-backport, v8.8.0.0

#817 Align mysql and mongodb with native connectors
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/tests/fixtures/mongodb/connector.json
  connectors/sources/tests/fixtures/mysql/connector.json
Labels: auto-backport, v8.8.0.0

#807 Move get_existing_ids to Fetcher
  connectors/byoei.py
  connectors/tests/test_byoei.py
Labels: v8.8.0.0

#818 Fix misformatted mongodb connector.json
  connectors/sources/tests/fixtures/mongodb/connector.json
Labels: auto-backport, v8.8.0.0

#815 [New Connector] ServiceNow: Ping feature
  config.yml
  connectors/sources/servicenow.py
  connectors/sources/tests/test_servicenow.py
Labels: v8.9.0, team:external

#822 [e2e] add a max rss for each connector
  connectors/sources/tests/fixtures/confluence/.env
  connectors/sources/tests/fixtures/google_cloud_storage/.env
  connectors/sources/tests/fixtures/jira/.env
  connectors/sources/tests/fixtures/mssql/.env
  connectors/sources/tests/fixtures/mysql/.env
  connectors/sources/tests/fixtures/oracle/.env
  connectors/sources/tests/fixtures/postgresql/.env
  connectors/tests/ftest.sh
Labels: auto-backport, v8.6.0, v8.7.0, v8.8.0.0

#820 Fix configuration formatting during preparation
  connectors/byoc.py
  connectors/tests/test_byoc.py
  connectors/tests/test_utils.py
  connectors/utils.py
Labels: auto-backport, v8.8.0.0, 8.8, v8.8.0
