Repository elastic/connectors, pull requests merged in 2023-10, with the labels that each got.

#1701 Add ui restrictions for all extraction RCFs
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/github.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/onedrive.py
  connectors/sources/outlook.py
  connectors/sources/s3.py
  connectors/sources/salesforce.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
  connectors/sources/sharepoint_server.py
  connectors/sources/zoom.py
Labels: v8.11.0, v8.11.0.0

#1681 Documentation for Microsoft Teams
  docs/REFERENCE.md
  docs/reference/microsoft_teams.md
Labels: auto-backport, team:external, v8.11.0, teams, v8.11.0.0

#1684 [Microsoft Teams] Moving connector code to main
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/microsoft_teams.py
  requirements/framework.txt
  tests/sources/fixtures/microsoft_teams/.env
  tests/sources/fixtures/microsoft_teams/config.yml
  tests/sources/fixtures/microsoft_teams/connector.json
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/fixture.py
  tests/sources/test_microsoft_teams.py
Labels: auto-backport, team:external, teams, v8.11.0.0

#1602 [Google Drive] Support domain-wide delegation for syncing data
  connectors/sources/google_drive.py
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/test_google_drive.py
Labels: release_note, auto-backport, v8.11.0.0

#1699 Add DLS in Network Drive
  connectors/sources/network_drive.py
  requirements/framework.txt
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.11.0.0

#1688 Replace User Information List usage with role assignments for SPO sites
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, vpre-8.10-stable, v8.11.0.0, v8.10.3

#1711 [pre-8.10-stable] Replace User Information List usage with role assignments for SPO sites (#1688)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1712 [8.10] [SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1713 [8.10] Replace User Information List usage with role assignments for SPO sites (#1688)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1707 [pre-8.10-stable] Forcibly cancel a sync job after waiting for 5 seconds (#1683)
  connectors/es/sink.py
  tests/test_sink.py
Labels: backport

#1729 [8.11] Bump stack versions
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
  tests/ftest.sh
Labels: v8.12.0

#1724 Update tooltips for enumerating all sites.
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.11.0, v8.11.0.0

#1732 [8.10] [SPO] Handle aiohttp.ClientPayloadError (#1660)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1689 Fix unreliable job scheduling by making it look-behind instead of look-ahead
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  connectors/utils.py
  tests/protocol/test_connectors.py
  tests/services/test_job_scheduling.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.8.0, v8.10.0, v8.11.0.0

#1737 Add support for security group prefixes
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, vpre-8.10-stable, v8.11.0, v8.12.0, v8.10.4, v8.12.0.0

#1731 Truncate branches and leafs in incremental sync
  connectors/source.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, vpre-8.10-stable, v8.11.0, v8.10.4, v8.12.0.0

#1752 [pre-8.10-stable] Truncate branches and leafs in incremental sync (#1731)
  connectors/source.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1751 [8.10] Truncate branches and leafs in incremental sync (#1731)
  connectors/source.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1741 Stop nightlies for 8.7 and 8.8
  catalog-info.yaml
Labels: v8.12.0.0

#1728 Box documentation
  docs/REFERENCE.md
  docs/reference/box.md
Labels: auto-backport, v8.11.0.0

#1765 Make test_next_run deterministic
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.10.0, v8.11.0, v8.12.0.0

#1758 fetch site admins separate from role assignments
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, v8.12.0, v8.12.0.0

#1716 Add Documentation for DLS in Network Drive
  docs/document-level-security/NETWORK_DRIVE.md
Labels: auto-backport, v8.11.0.0

#1766 Make test_mem_queue less flaky
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.10.0, v8.11.0, v8.12.0.0

#1779 [README] Change connectors-python to connectors
  README.md
Labels: auto-backport, v8.12.0.0

#1780 [DOCKER] Reflect repository name change in docker docs
  docs/DOCKER.md
Labels: auto-backport, v8.12.0.0

#1781 [RELEASING] Reflect repository name change in releasing docs
  docs/RELEASING.md
Labels: auto-backport, v8.12.0.0

#1709 Make Azure Blob Storage ftest use shared setup
  tests/sources/fixtures/azure_blob_storage/fixture.py
Labels: auto-backport, v8.11.0.0

#1710 Make Dropbox ftest use shared fixture
  tests/sources/fixtures/dropbox/fixture.py
Labels: auto-backport, v8.11.0.0

#1717 Make Github ftest use shared fixture
  tests/sources/fixtures/github/fixture.py
Labels: auto-backport, v8.11.0.0

#1718 Make GCS ftest use shared fixture
  tests/sources/fixtures/google_cloud_storage/fixture.py
Labels: auto-backport, v8.11.0.0

#1719 Make Google Drive ftest use shared fixture
  tests/commons.py
  tests/sources/fixtures/google_drive/fixture.py
Labels: auto-backport, v8.11.0.0

#1782 [SUPPORT] Reflect repository name changes in support docs
  docs/SUPPORT.md
Labels: auto-backport, v8.12.0.0

#1784 [DEVELOPING] Reflect repository name change in developing docs
  docs/DEVELOPING.md
Labels: auto-backport, v8.12.0.0

#1786 [CONTRIBUTING] Reflect repository name changes in contributing docs
  docs/CONTRIBUTING.md
Labels: auto-backport, v8.12.0.0

#1726 Make MSSQL ftest use shared fixture + small fixture optimizations
  tests/sources/fixtures/mssql/fixture.py
Labels: auto-backport, v8.11.0.0

#1783 [UPGRADING] Reflect repository name change in upgrading docs
  docs/UPGRADING.md
Labels: auto-backport, v8.12.0.0

#1756 Make Sharepoint Online ftest use shared fixture
  tests/sources/fixtures/sharepoint_online/fixture.py
Labels: auto-backport, v8.12.0.0

#1762 [GCS] Fix issue related url-encoded
  connectors/sources/google_cloud_storage.py
  tests/sources/test_google_cloud_storage.py
Labels: auto-backport, google-cloud-storage, team:external, v8.12.0.0

#1778 [Outlook] Add a new field for `max concurrent tasks`
  connectors/sources/outlook.py
  docs/reference/outlook.md
Labels: auto-backport, team:external, v8.11.0, outlook, v8.12.0.0

#1787 [BACKPORT] Update upstream repo to new name
  .backportrc.json
Labels: auto-backport, v8.12.0.0

#1773 Add support for DLS in Linux Network Drive
  connectors/sources/network_drive.py
  docs/document-level-security/NETWORK_DRIVE.md
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.12.0.0

#1795 [BACKSTAGE] Update catalog-info.yml to reflect new repo name
  catalog-info.yaml
Labels: auto-backport, v8.12.0.0

#1805 [CI] Update secrets paths
  .buildkite/publish_docker.sh
  .buildkite/run_nigthly.sh
Labels: auto-backport, v8.12.0.0

#1806 [GitHub] Add missing re-raise on ClientResponseError
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.12.0.0

#1811 [CI] Update pull-requests.json
  .buildkite/pull-requests.json
Labels: auto-backport, v8.9.0, v8.10.0, v8.11.0, v8.12.0.0

#1800 Use VersionData endpoint to download content
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: auto-backport, v8.11.0, v8.12.0.0

#1817 [Linter] Add ASYNC rules and fix issues
  .ruff.toml
  connectors/sources/directory.py
  requirements/framework.txt
  tests/test_logger.py
Labels: auto-backport, v8.9.0, v8.10.0, v8.11.0.0, v8.12.0.0

#1785 [DEVELOPING] Point to config on main branch instead of 8.6 branch
  docs/DEVELOPING.md
Labels: auto-backport, v8.12.0.0

#1827 [SPO] Fix bugs when handling drive_items in incremental sync
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, sharepoint, vpre-8.10-stable, v8.11.0, v8.11.0.0, v8.12.0, v8.12.0.0

#1830 Fix configuration migrations to work for peripheral connectors
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.10.0, v8.11.0, v8.12.0

#1823 Improve PostgreSQL query for identifying primary keys
  connectors/sources/postgresql.py
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/fixtures/postgresql/fixture.py
Labels: auto-backport, v8.12.0.0

#1848 Move common functions to test_base.py
  tests/services/test_base.py
  tests/services/test_job_cleanup.py
  tests/services/test_job_execution.py
  tests/services/test_job_scheduling.py
Labels: v8.12.0, v8.12.0.0

#1847 Make pending_jobs fetch jobs by job types
  connectors/protocol/connectors.py
  connectors/services/job_execution.py
  tests/protocol/test_connectors.py
Labels: v8.12.0, v8.12.0.0

#1850 Move _override_es_config to BaseService
  connectors/services/base.py
  connectors/services/job_execution.py
  tests/services/test_base.py
  tests/services/test_job_execution.py
Labels: v8.12.0, v8.12.0.0

#1852 [8.11] Improve PostgreSQL query for identifying primary keys (#1823)
  connectors/sources/postgresql.py
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/fixtures/postgresql/fixture.py
Labels: backport

#1842 [Network Drive] Add Dropdown for Drive type
  connectors/sources/network_drive.py
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.12.0.0

#1851 Move some instance variables to BaseService
  connectors/services/base.py
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
Labels: v8.12.0, v8.12.0.0

#1856 Enable ISC rule + autoformat
  .ruff.toml
  tests/sources/fixtures/postgresql/fixture.py
Labels: auto-backport, v8.12.0.0

#1858 Update user agent string for the ES client
  connectors/es/client.py
Labels: auto-backport, connector-framework, v8.12.0, v8.12.0.0
