Repository elastic/connectors, pull requests merged in 2023-09, with the labels that each got.

#1557 [GMail] Validate subject RCF value
  connectors/sources/gmail.py
  connectors/sources/google_drive.py
  connectors/utils.py
  tests/sources/test_gmail.py
  tests/test_utils.py
Labels: auto-backport, v8.11.0.0

#1531 [DLS] Remove must_not exists clause from access control query
  connectors/access_control.py
  tests/sources/test_confluence.py
  tests/sources/test_google_drive.py
  tests/sources/test_jira.py
  tests/test_access_control.py
Labels: auto-backport, v8.11.0.0

#1561 [8.9] Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)
  tests/sources/test_mongo.py
Labels: backport

#1562 [pre-8.10-stable] Fix mongodb tests by removing mocking of _get_socket + patching admin ping call (#1514)
  tests/sources/test_mongo.py
Labels: backport

#1551 [8.9] [DOCS] Update README.md (#1537)
  README.md
Labels: backport

#1558 [GMail] Validate GMail authentication
  connectors/sources/gmail.py
  connectors/sources/google.py
  tests/sources/test_gmail.py
Labels: auto-backport, v8.11.0.0

#1544 Add ftest.Dockerfile that's used for all functional tests
  Dockerfile
  Dockerfile.ftest
  Makefile
  docs/DOCKER.md
  requirements/ftest.txt
  tests/sources/fixtures/azure_blob_storage/requirements.txt
  tests/sources/fixtures/confluence/Dockerfile
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/confluence/requirements.txt
  tests/sources/fixtures/dropbox/Dockerfile
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/dropbox/requirements.txt
  tests/sources/fixtures/github/Dockerfile
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/github/requirements.txt
  tests/sources/fixtures/google_cloud_storage/Dockerfile
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/requirements.txt
  tests/sources/fixtures/google_drive/Dockerfile
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/google_drive/requirements.txt
  tests/sources/fixtures/jira/Dockerfile
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/jira/requirements.txt
  tests/sources/fixtures/mongodb/requirements.txt
  tests/sources/fixtures/mongodb_serverless/requirements.txt
  tests/sources/fixtures/mssql/requirements.txt
  tests/sources/fixtures/mysql/requirements.txt
  tests/sources/fixtures/network_drive/requirements.txt
  tests/sources/fixtures/onedrive/Dockerfile
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/onedrive/requirements.txt
  tests/sources/fixtures/oracle/requirements.txt
  tests/sources/fixtures/postgresql/requirements.txt
  tests/sources/fixtures/s3/requirements.txt
  tests/sources/fixtures/servicenow/Dockerfile
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/servicenow/requirements.txt
  tests/sources/fixtures/sharepoint_online/Dockerfile
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/requirements.txt
  tests/sources/fixtures/sharepoint_server/Dockerfile
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/requirements.txt
Labels: auto-backport, v8.11.0.0

#1565 [GMail] Validate Google Directory auth
  connectors/sources/gmail.py
  tests/sources/test_gmail.py
Labels: auto-backport, v8.11.0.0

#1560 [Jira] Move common code to Atlassian module
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.10.0, v8.11.0, v8.11.0.0

#1570 [Docs] Add access control sequence diagram
  docs/CONNECTOR_PROTOCOL.md
Labels: auto-backport, v8.10.0.0, v8.11.0.0

#1577 [FTest] Add separate ftest logger
  tests/sources/fixtures/fixture.py
Labels: auto-backport, v8.11.0.0

#1575 [Google Drive/Storage/Gmail] Handle escaped json strings from user input
  connectors/sources/gmail.py
  connectors/sources/google.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  tests/sources/fixtures/description.txt
  tests/sources/test_google.py
  tests/sources/test_google_cloud_storage.py
Labels: bug, auto-backport, v8.10.0.0, v8.10.0, v8.11.0, v8.11.0.0

#1576 Ensure indices are created on startup
  connectors/es/client.py
  connectors/kibana.py
  connectors/preflight_check.py
  connectors/protocol/connectors.py
  requirements/tests.txt
  tests/test_kibana.py
  tests/test_preflight_check.py
Labels: release_note, auto-backport, v8.10.0, v8.11.0, v8.11.0.0

#1585 Include missing lxml library - beautifulsoup attempted to use it, but did not since library is not there
  requirements/framework.txt
  tests/test_utils.py
Labels: auto-backport, v8.10.0, v8.11.0.0

#1588 bump after 8.9.2 release
  connectors/VERSION
Labels: v8.9.3.0

#1572 [Zoom] Moving connector code to main
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/zoom.py
  tests/sources/fixtures/zoom/.env
  tests/sources/fixtures/zoom/config.yml
  tests/sources/fixtures/zoom/connector.json
  tests/sources/fixtures/zoom/docker-compose.yml
  tests/sources/fixtures/zoom/fixture.py
  tests/sources/test_zoom.py
Labels: auto-backport, team:external, v8.11.0, zoom, v8.11.0.0

#1564 [New Connector] Zoom Documentation
  docs/REFERENCE.md
  docs/reference/zoom.md
Labels: team:external, v8.11.0, zoom

#1578 [FTest] Remove retry library and use utils.py retryable decorator
  requirements/tests.txt
  tests/sources/fixtures/fixture.py
Labels: auto-backport, v8.11.0.0

#1594 [pre-8.10-stable] [SPO] Remove site_group_id and site_user_id (#1467)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1595 Skip site collection query if * is configured for site collections
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0, v8.11.0, v8.11.0.0

#1501 [Outlook] Implement Ping + Indexing
  connectors/config.py
  connectors/sources/outlook.py
  requirements/framework.txt
  tests/sources/test_outlook.py
Labels: team:external, v8.11.0, outlook

#1589 [Salesforce] Add ftests
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/salesforce.py
  tests/sources/fixtures/salesforce/.env
  tests/sources/fixtures/salesforce/config.yml
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/salesforce/fixture.py
Labels: auto-backport, v8.10.0

#1600 [pre-8.10-stable] Skip site collection query if * is configured for site collections (#1595)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1598 [8.10] [SPO] Remove site_group_id and site_user_id (#1467)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1591 Run all functional tests on changes in Dockerfile.ftest
  .buildkite/pipeline.yml
Labels: auto-backport, v8.11.0.0

#1597 [FTest] Use logger instead of print
  tests/sources/fixtures/fixture.py
Labels: auto-backport, v8.11.0.0

#1599 [8.10] [Salesforce] Add ftests (#1589)
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/salesforce.py
  tests/sources/fixtures/salesforce/.env
  tests/sources/fixtures/salesforce/Dockerfile
  tests/sources/fixtures/salesforce/config.yml
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/salesforce/fixture.py
  tests/sources/fixtures/salesforce/requirements.txt
Labels: backport

#1606 Update CONFIG.md
  docs/CONFIG.md
Labels: documentation, auto-backport, v8.10.0.0, v8.11.0.0

#1608 [FTest] Separate Kibana fake logger from framework logger
  connectors/kibana.py
  tests/test_kibana.py
Labels: auto-backport, v8.11.0.0

#1610 catch 400 on list item unique role assignments
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, vpre-8.10-stable, v8.11.0, v8.11.0.0, v8.10.1

#1574 [New Connector] Microsoft Teams: Indexing feature
  connectors/sources/microsoft_teams.py
  tests/sources/test_microsoft_teams.py
Labels: auto-backport, team:external, v8.11.0.0

#1623 [Zoom] Add recording age as config param
  connectors/sources/zoom.py
  docs/reference/zoom.md
  tests/sources/fixtures/zoom/connector.json
  tests/sources/test_zoom.py
Labels: auto-backport, team:external, v8.11.0, zoom, v8.11.0.0

#1619 Improve OneDrive Connector Performance
  connectors/sources/onedrive.py
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/onedrive/fixture.py
  tests/sources/test_onedrive.py
Labels: v8.11.0, v8.11.0.0

#1629 Outlook connector
  connectors/config.py
  connectors/sources/outlook.py
  requirements/framework.txt
  tests/sources/test_outlook.py
Labels: auto-backport, team:external, v8.11.0, outlook, v8.11.0.0

#1636 Introduce connector list command
  connectors/cli/connector.py
  connectors/connectors_cli.py
  requirements/framework.txt
Labels: auto-backport, v8.11.0.0

#1635 [OneDrive] Document level security
  connectors/sources/onedrive.py
  docs/document-level-security/ONEDRIVE.md
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/test_onedrive.py
Labels: auto-backport, team:external, onedrive, v8.11.0, v8.11.0.0

#1627 [Microsoft Teams] Add ftests
  .buildkite/pipeline.yml
  connectors/sources/microsoft_teams.py
  tests/sources/fixtures/microsoft_teams/.env
  tests/sources/fixtures/microsoft_teams/config.yml
  tests/sources/fixtures/microsoft_teams/connector.json
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/fixture.py
  tests/sources/test_microsoft_teams.py
Labels: auto-backport, team:external, v8.11.0.0

#1601 Pass retry_count to the retry handler
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.11.0.0

#1656 [8.10] Pass retry_count to the retry handler (#1601)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1649 [Zoom] Recording age validation
  connectors/sources/zoom.py
Labels: auto-backport, team:external, v8.11.0, zoom, v8.11.0.0

#1657 Bump version to 8.10.2
  connectors/VERSION
Labels: auto-backport, v8.10.0, v8.11.0.0

#1658 Add retryable to bulk api call
  connectors/config.py
  connectors/es/sink.py
  connectors/utils.py
  tests/test_sink.py
Labels: v8.11.0, v8.11.0.0

#1641 Outlook Documentation
  docs/REFERENCE.md
  docs/reference/outlook.md
Labels: auto-backport, team:external, v8.11.0, outlook, v8.11.0.0

#1660 Handle aiohttp.ClientPayloadError
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.11.0, v8.11.0.0

#1654 [8.10] Fix yaml indentation (#1614)
  docs/CONFIG.md
Labels: backport

#1659 [SPO] Add logic to handle sitegroups in ACL for drive_items and sites
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.11.0.0

#1672 [pre-8.10-stable] [SPO] Add logic to handle sitegroups in ACL for drive_items and sites (#1659)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#1653 [SPO] individual site lookup RCF
  connectors/protocol/connectors.py
  connectors/sources/sharepoint_online.py
  tests/protocol/test_connectors.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.11.0, v8.11.0.0, v8.10.1

#1677 [pre-8.10-stable] [SPO] individual site lookup RCF (#1653)
  connectors/protocol/connectors.py
  connectors/sources/sharepoint_online.py
  tests/protocol/test_connectors.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: backport

#1676 [8.10] [SPO] individual site lookup RCF (#1653)
  connectors/protocol/connectors.py
  connectors/sources/sharepoint_online.py
  tests/protocol/test_connectors.py
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: backport

#1680 Fix issues of Microsoft Teams
  connectors/sources/microsoft_teams.py
  tests/sources/fixtures/microsoft_teams/fixture.py
  tests/sources/test_microsoft_teams.py
Labels: auto-backport, team:external, v8.11.0.0

#1674 Add docker release docs
  docs/RELEASING.md
Labels: v8.11.0, v8.11.0.0

#559 [PostgreSQL] Allow only one schema to be configured
  connectors/sources/postgresql.py
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/test_postgresql.py
Labels: v8.11.0, v8.11.0.0

#1679 Update NOTICE.txt to include link to certifi source
  NOTICE.txt
Labels: v8.11.0, v8.11.0.0

#1685 Abstract download file extraction and conversion
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
Labels: auto-backport, v8.11.0.0

#1686 Alphabetize sources
  connectors/config.py
Labels: v8.11.0, v8.11.0.0

#1693 Expand extraction service to more connectors #2
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/jira.py
  connectors/sources/s3.py
  connectors/utils.py
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/fixtures/s3/connector.json
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_confluence.py
  tests/sources/test_dropbox.py
  tests/sources/test_jira.py
  tests/sources/test_s3.py
Labels: v8.11.0, v8.11.0.0

#1590 Add common perftest classes for data generation + use in confluence to demonstrate
  Dockerfile.ftest
  tests/commons.py
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/zoom/docker-compose.yml
Labels: auto-backport, v8.11.0.0

#1661 [Box] E2E feature
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/box.py
  tests/sources/fixtures/box/.env
  tests/sources/fixtures/box/config.yml
  tests/sources/fixtures/box/connector.json
  tests/sources/fixtures/box/docker-compose.yml
  tests/sources/fixtures/box/fixture.py
Labels: team:external, v8.11.0, box

#1694 Expand extraction service to more connectors #3
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/onedrive.py
  connectors/sources/s3.py
  connectors/sources/salesforce.py
  connectors/sources/servicenow.py
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/servicenow/connector.json
  tests/sources/test_google_cloud_storage.py
  tests/sources/test_google_drive.py
  tests/sources/test_onedrive.py
  tests/sources/test_salesforce.py
  tests/sources/test_servicenow.py
Labels: v8.11.0, v8.11.0.0

#1691 [PostgreSQL] Advanced Sync rules
  connectors/sources/postgresql.py
  docs/sync-rules/POSTGRESQL.md
  tests/sources/test_postgresql.py
Labels: auto-backport, team:external, v8.11.0, v8.11.0.0

#1698 Expand extraction service to more connectors #4
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/github.py
  connectors/sources/google.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/onedrive.py
  connectors/sources/outlook.py
  connectors/sources/s3.py
  connectors/sources/salesforce.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_server.py
  connectors/sources/zoom.py
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/fixtures/zoom/connector.json
  tests/sources/test_github.py
  tests/sources/test_outlook.py
  tests/sources/test_sharepoint_server.py
  tests/sources/test_zoom.py
Labels: v8.11.0, v8.11.0.0

#1683 Forcibly cancel a sync job after waiting for 5 seconds
  connectors/es/sink.py
  tests/test_sink.py
Labels: v8.11.0, v8.11.0.0

#1702 [SPO] Do not use retry-after as multiplier
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, vpre-8.10-stable, v8.11.0, v8.11.0.0, v8.10.3
