Repository elastic/connectors, pull requests merged in 2023-06, with the labels that each got.

#924 [SharePoint] Pagination support in the fake SharePoint server
  tests/sources/fixtures/sharepoint/fixture.py
Labels: team:external, v8.9.0.0

#899 [ServiceNow] Documentation for ServiceNow connector
  docs/DEVELOPING.md
Labels: servicenow, v8.9.0, team:external

#981 Document sync rules for Jira and Confluence
  README.md
  docs/reference/confluence.md
  docs/reference/jira.md
  docs/sync-rules/CONFLUENCE.md
  docs/sync-rules/JIRA.md
Labels: documentation, auto-backport, team:external, v8.9.0.0

#963 Update sync_cursor for a completed sync job
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: v8.9.0, v8.9.0.0

#977 Modify scheduling structure in connector index
  connectors/kibana.py
  connectors/protocol/connectors.py
  docs/CONNECTOR_PROTOCOL.md
  tests/fixtures/connector.json
  tests/protocol/test_connectors.py
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mysql/connector.json
Labels: v8.9.0, v8.9.0.0

#996 Bump elasticsearch package to 8.8.0
  requirements/framework.txt
Labels: auto-backport, v8.9.0.0

#967 [Sharepoint] Add server relative url for list and its items
  connectors/sources/sharepoint.py
  tests/sources/test_sharepoint.py
Labels: auto-backport, team:external, v8.9.0.0

#970 [DLS] Rename "permissions sync" to "access control sync"
  connectors/kibana.py
  connectors/protocol/connectors.py
  docs/CONNECTOR_PROTOCOL.md
  tests/fixtures/connector.json
  tests/protocol/test_connectors.py
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mysql/connector.json
Labels: v8.9.0.0

#995 Allow to create job with job type
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  tests/protocol/test_connectors.py
  tests/services/test_job_scheduling.py
Labels: v8.9.0, v8.9.0.0

#993 Support incremental sync in JobExecutionService
  connectors/services/job_execution.py
  tests/services/test_job_execution.py
Labels: v8.9.0, v8.9.0.0

#999 Fix the aarch64 build
  .buildkite/nightly_aarch64.py
Labels: auto-backport, v8.9.0.0

#986 Add incremental sync support to BaseDataSource
  connectors/source.py
  tests/test_source.py
Labels: v8.9.0, v8.9.0.0

#1001 [DLS] At most one access control sync per connector guard
  connectors/services/job_execution.py
  tests/services/test_job_execution.py
Labels: auto-backport, v8.9.0.0

#1000 [DLS] Access control sync scheduling
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  tests/protocol/test_connectors.py
  tests/services/test_job_scheduling.py
Labels: v8.9.0.0

#968 [Sharepoint][Bugfix]Encode Site Pages URL
  connectors/sources/sharepoint.py
  tests/sources/test_sharepoint.py
Labels: auto-backport, team:external, v8.9.0.0

#1012 Add incremental sync support to JobSchedulingService
  connectors/services/job_scheduling.py
  tests/fake_sources.py
  tests/fixtures/config.yml
  tests/services/test_job_scheduling.py
Labels: v8.9.0, v8.9.0.0

#1010 [DLS] Add "last_access_control_sync_error" to fixture files/kibana fake
  connectors/kibana.py
  tests/fixtures/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mysql/connector.json
Labels: v8.9.0.0

#1011 [DLS] Add "last_access_control_sync_error" to protocol docs
  docs/CONNECTOR_PROTOCOL.md
Labels: v8.9.0.0

#1017 [Sharepoint] Use correct throttling headers
  tests/sources/fixtures/sharepoint/fixture.py
Labels: auto-backport, v8.9.0, v8.9.0.0

#1009 [DLS] Add last access control sync information to sync_starts and sync_done
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: v8.9.0.0

#1024 skipping on aarch64
  .buildkite/nightly_steps.yml
  .buildkite/run_nigthly.sh
Labels: v8.9.0.0

#1025 Add tooltip for fields overridden by Advanced Sync Rules
  connectors/sources/confluence.py
  connectors/sources/jira.py
Labels: auto-backport, v8.9.0, team:external, v8.9.0.0

#1003 Make Extractor support incremental sync
  connectors/es/sink.py
  connectors/sync_job_runner.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: v8.9.0, v8.9.0.0

#1028 Import from connectors.protocol
  connectors/es/sink.py
  connectors/services/job_execution.py
  connectors/sync_job_runner.py
  tests/protocol/test_connectors.py
  tests/services/test_job_execution.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: v8.9.0, v8.9.0.0

#1029 Tweak the aarch64 flag
  .buildkite/run_nigthly.sh
Labels: v8.9.0.0

#1026 [SharePoint]Add elastic field `editor_id` for list items
  connectors/sources/sharepoint.py
  tests/sources/test_sharepoint.py
Labels: auto-backport, team:external, v8.9.0.0

#1037 only main for aarch64 for now
  catalog-info.yaml
Labels: auto-backport, v8.9.0.0

#1039 Remove -x from CI script
  .buildkite/publish_docker.sh
Labels: auto-backport, v8.9.0.0, v8.8.2, v8.7.2, v8.6.2, v8.5.3

#1013 [DLS] Guard access control scheduling and execution with a license check
  connectors/es/client.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  tests/es/test_client.py
  tests/services/test_job_execution.py
  tests/services/test_job_scheduling.py
Labels: v8.9.0.0

#1030 add premium connectors
  connectors/services/job_execution.py
  connectors/source.py
  tests/fake_sources.py
  tests/services/test_job_execution.py
Labels: v8.9.0

#1048 Fix typo
  tests/fake_sources.py
Labels: auto-backport, v8.9.0.0

#969 Basic Sharepoint online connector
  SHAREPOINT.md
  config.yml
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  requirements/framework.txt
  tests/sources/fixtures/sharepoint_online/.env
  tests/sources/fixtures/sharepoint_online/Dockerfile
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/fixture.py
  tests/sources/fixtures/sharepoint_online/nginx/conf/sharepoint.com
  tests/sources/fixtures/sharepoint_online/requirements.txt
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: release_note, v8.9.0.0

#1050 [SharePoint]Add AuthorId in e2e
  tests/sources/fixtures/sharepoint/fixture.py
Labels: auto-backport, team:external, v8.9.0.0

#1052 Create Jobs index with mappings for ftests
  connectors/kibana.py
Labels: auto-backport, v8.9.0.0

#1046 [DLS] Separate access control syncs task pool from content syncs task pool
  config.yml
  connectors/services/job_execution.py
  docs/CONFIG.md
  tests/fixtures/config.yml
  tests/services/test_job_execution.py
Labels: release_note, v8.9.0.0

#1051 Fix make lint|autoformat to also work on tests
  Makefile
  tests/conftest.py
  tests/es/test_client.py
  tests/es/test_index.py
  tests/fake_sources.py
  tests/protocol/test_connectors.py
  tests/services/test_job_execution.py
  tests/services/test_job_scheduling.py
  tests/sources/fixtures/sharepoint_online/fixture.py
  tests/sources/test_generic_database.py
  tests/sources/test_google_cloud_storage.py
  tests/sources/test_mongo.py
  tests/sources/test_s3.py
  tests/sources/test_sharepoint.py
  tests/sources/test_sharepoint_online.py
  tests/test_logger.py
  tests/test_sink.py
  tests/test_source.py
  tests/test_sync_job_runner.py
Labels: v8.9.0.0

#1054 [DLS] Move license check to separate module
  connectors/es/license.py
  connectors/services/job_execution.py
  tests/es/test_license.py
Labels: auto-backport, v8.9.0.0

#1036 Support for serverless
  .buildkite/nightly_steps.yml
  .buildkite/publish_docker.sh
  .buildkite/run_nigthly.sh
  connectors/es/client.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  scripts/verify.py
  tests/ftest.sh
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mongodb_serverless/docker-compose.yml
  tests/sources/fixtures/mongodb_serverless/fixture.py
  tests/sources/fixtures/mongodb_serverless/requirements.txt
Labels: v8.9.0.0

#1005 [Dropbox] Implement Indexing Feature
  connectors/sources/dropbox.py
  tests/sources/test_dropbox.py
Labels: v8.9.0, team:external, dropbox

#1060 Display MSSQL validate_host bool as toggle
  connectors/sources/mssql.py
Labels: auto-backport, v8.9.0, v8.9.0.0

#1062 Update configurable field cases
  connectors/sources/sharepoint_online.py
Labels: v8.9.0.0

#1067 Small renames for download functions in SPO connector + important comment for attachment download
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: v8.9.0.0

#1059 Add incremental sync support to SyncJobRunner
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  tests/protocol/test_connectors.py
  tests/test_sync_job_runner.py
Labels: v8.9.0, v8.9.0.0

#1068 Update catalog-info.yaml
  catalog-info.yaml
Labels: auto-backport, v8.9.0.0

#1035 Add extraction service
  config.yml
  connectors/es/sink.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: v8.9.0

#1038 Attempt to use non-native default and ftest configs
  config.yml
  connectors/kibana.py
  connectors/services/job_execution.py
  requirements/tests.txt
  tests/ftest.sh
  tests/sources/fixtures/README.md
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mssql/fixture.py
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/mysql/connector.json
  tests/sources/fixtures/mysql/fixture.py
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/oracle/fixture.py
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/postgresql/fixture.py
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/sharepoint/config.yml
Labels: release_note, auto-backport, v8.9.0, v8.9.0.0

#1063 deprecate native mode configurably
  connectors/preflight_check.py
  tests/test_preflight_check.py
Labels: release_note, v8.9.0

#1061 [ServiceNow] Add batching in APIs
  connectors/sources/servicenow.py
  connectors/sources/tests/fixtures/servicenow/fixture.py
  connectors/sources/tests/test_servicenow.py
Labels: servicenow, v8.9.0, team:external

#1074 Refactor extraction service session handling
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.9.0.0

#1073 [DLS] Prefix target index for access control syncs
  connectors/protocol/connectors.py
  connectors/utils.py
  tests/protocol/test_connectors.py
Labels: v8.9.0, v8.9.0.0

#1072 Reuse enqueue_docs_to_delete method
  connectors/es/sink.py
Labels: v8.9.0, v8.9.0.0

#1078 Fix minor issues with data extraction service
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/test_utils.py
Labels: v8.9.0, v8.9.0.0

#1070 Remove sync_now flag support
  connectors/kibana.py
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  docs/CONNECTOR_PROTOCOL.md
  tests/fixtures/connector.json
  tests/protocol/test_connectors.py
  tests/services/test_job_scheduling.py
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mysql/connector.json
  tests/sources/fixtures/sharepoint_online/connector.json
Labels: v8.9.0, v8.9.0.0

#1075 Use string interpolation for warning when Retry-After is not provided
  connectors/sources/sharepoint_online.py
Labels: v8.9.0.0

#1081 Add preflight check for unmodified config
  connectors/preflight_check.py
  tests/fake_sources.py
  tests/test_cli.py
  tests/test_preflight_check.py
Labels: release_note, auto-backport, v8.9.0, v8.9.0.0

#1076 Properly populate ids for site pages and list items
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0.0

#1083 [8.7] Add nightly_docker.yml for docker builds
  .buildkite/nightly_docker.yml
Labels: v8.7.2

#1080 Servicenow connector
  .buildkite/nightly_steps.yml
  config.yml
  connectors/sources/servicenow.py
  docs/REFERENCE.md
  docs/reference/servicenow.md
  tests/sources/fixtures/servicenow/.env
  tests/sources/fixtures/servicenow/Dockerfile
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/servicenow/fixture.py
  tests/sources/fixtures/servicenow/requirements.txt
  tests/sources/test_servicenow.py
Labels: auto-backport, servicenow, v8.9.0, team:external, v8.9.0.0

#1086 [DLS] Set data provider features to corresponding connector features
  connectors/source.py
  connectors/sync_job_runner.py
  tests/test_source.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.9.0.0

#1055 Add retryable to requests done by MicrosoftAPISession class
  connectors/sources/sharepoint_online.py
  tests/conftest.py
  tests/sources/test_sharepoint_online.py
Labels: v8.9.0.0

#1088 [DLS] Add permissions to SPO docs
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0.0

#1090 Don't run permissions query if DLS is disabled
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: v8.9.0, v8.9.0.0

#1087 Log filename for failed extractions
  config.yml
  connectors/es/sink.py
  connectors/sources/sharepoint_online.py
  connectors/sync_job_runner.py
  connectors/utils.py
  tests/sources/test_sharepoint_online.py
  tests/test_utils.py
Labels: v8.9.0, v8.9.0.0

#1089 Add extraction service preflight check
  connectors/preflight_check.py
  tests/fixtures/config.yml
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/sharepoint/config.yml
  tests/test_preflight_check.py
Labels: v8.9.0, v8.9.0.0

#1079 [Sharepoint Online] Support incremental sync
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0.0

#1091 Assign empty list if native_service_types is configured to None
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
Labels: v8.9.0, v8.9.0.0

#1065 Complete connector separation of SharePoint Server from SharePoint Online
  .buildkite/nightly_steps.yml
  config.yml
  connectors/sources/sharepoint_server.py
  docs/REFERENCE.md
  docs/reference/sharepoint.md
  docs/reference/sharepoint_server.md
  tests/sources/fixtures/sharepoint_server/Dockerfile
  tests/sources/fixtures/sharepoint_server/config.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/fixture.py
  tests/sources/fixtures/sharepoint_server/requirements.txt
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, team:external, v8.9.0.0

#1093 Dropbox connector
  config.yml
  connectors/sources/dropbox.py
  requirements/framework.txt
  tests/sources/test_dropbox.py
Labels: auto-backport, v8.9.0, team:external, v8.9.0.0

#1085 Rename maxDataAge to skipDriveItemsOlderThan
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0.0

#1099 [Incremental Sync] Enable ignored test
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0.0

#1096 Make extraction service config optional
  config.yml
  connectors/preflight_check.py
  connectors/sources/sharepoint_online.py
  connectors/utils.py
  tests/fixtures/config.yml
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/sharepoint_server/config.yml
  tests/sources/test_sharepoint_online.py
  tests/test_preflight_check.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, v8.9.0.0

#1097 bump connector versions
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
Labels: auto-backport, v8.9.0.0

#806 Log correlation
  connectors/es/document.py
  connectors/es/sink.py
  connectors/filtering/validation.py
  connectors/logger.py
  connectors/protocol/connectors.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
  connectors/source.py
  connectors/sources/azure_blob_storage.py
  connectors/sources/confluence.py
  connectors/sources/directory.py
  connectors/sources/generic_database.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/network_drive.py
  connectors/sources/s3.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
  connectors/sources/sharepoint_server.py
  connectors/sync_job_runner.py
  tests/sources/test_mysql.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0

#1102 Update backportrc
  .backportrc.json
Labels: v8.10.0.0

#1092 [Google Cloud Storage] Replace mockserver with Flask to make E2E work for aarch64 and M1 chip
  .buildkite/nightly_steps.yml
  connectors/sources/google_cloud_storage.py
  tests/sources/fixtures/google_cloud_storage/Dockerfile
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/fixture.py
  tests/sources/fixtures/google_cloud_storage/gcs_dummy_cert.pem
  tests/sources/fixtures/google_cloud_storage/mocked_http_responses.json
  tests/sources/fixtures/google_cloud_storage/mocker.py
  tests/sources/fixtures/google_cloud_storage/mockerserver.properties
  tests/sources/fixtures/google_cloud_storage/requirements.txt
Labels: auto-backport, v8.9.0, team:external, v8.9.0.0

#1095 [GitHub] Implement Indexing Feature
  connectors/sources/github.py
  connectors/utils.py
  tests/sources/test_github.py
  tests/test_utils.py
Labels: v8.9.0, team:external, github

#1110 Enable incremental sync for SPO
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1098 [DLS] get_access_control and access_control_query for SPO
  connectors/source.py
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
  tests/test_source.py
Labels: auto-backport, v8.9.0.0

#1120 Update Dropbox SDK to 11.36.2
  requirements/framework.txt
Labels: bug, auto-backport, v8.9.0, v8.10.0.0

#1082 [S3]Replace AWS CLI configuration and add it in s3.py configuration
  connectors/sources/s3.py
  tests/sources/fixtures/s3/fixture.py
  tests/sources/test_s3.py
Labels: auto-backport, team:external, v8.9.0.0

#1107 Update logging in the Developer's guide
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.0, v8.10.0.0

#1109 Remove references to running natively
  README.md
  docs/CONFIG.md
  docs/DOCKER.md
Labels: auto-backport, v8.9.0, v8.10.0.0

#1101 [GitHub] E2E feature
  .buildkite/nightly_steps.yml
  connectors/sources/github.py
  tests/sources/fixtures/github/.env
  tests/sources/fixtures/github/Dockerfile
  tests/sources/fixtures/github/config.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/github/fixture.py
  tests/sources/fixtures/github/requirements.txt
Labels: v8.9.0, team:external, github

#1114 populate features for connector clients and customized connectors
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  connectors/source.py
  connectors/sources/confluence.py
  connectors/sources/jira.py
  connectors/sources/mongo.py
  connectors/sources/mysql.py
  connectors/sources/sharepoint_online.py
  tests/fake_sources.py
  tests/protocol/test_connectors.py
  tests/test_source.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1132 Change Subextract -> Extract for SPO Advanced Filtering
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1130 GitHub connector
  .buildkite/nightly_steps.yml
  config.yml
  connectors/sources/github.py
  connectors/utils.py
  requirements/framework.txt
  tests/sources/fixtures/github/.env
  tests/sources/fixtures/github/Dockerfile
  tests/sources/fixtures/github/config.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/github/fixture.py
  tests/sources/fixtures/github/requirements.txt
  tests/sources/test_github.py
  tests/test_utils.py
Labels: auto-backport, v8.9.0, team:external, github

#1116 Servicenow advanced rules
  README.md
  connectors/sources/servicenow.py
  docs/reference/servicenow.md
  docs/sync-rules/SERVICENOW.md
  tests/sources/test_servicenow.py
Labels: auto-backport, servicenow, team:external, v8.10.0.0

#1135 Increase SPO connector test coverage
  connectors/sources/sharepoint_online.py
  tests/conftest.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0

#1127 Few little fixes for ACL index prefix
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  connectors/utils.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.9.0, v8.10.0.0

#1129 Update developer guide for incremental sync
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.0, v8.10.0.0

#1143 Update qa_connector_package.md
  .github/ISSUE_TEMPLATE/qa_connector_package.md
Labels: auto-backport, v8.10.0.0

#1123 [SPO] Check if DLS RFC is enabled
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v8.10.0.0

#1152 Bump version to 8.8.3
  connectors/VERSION
Labels: v8.8.0

#1161 [8.9] [SPO] Check if DLS RFC is enabled (#1123)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport
