Repository elastic/connectors, pull requests merged in 2024-11, with the labels that each got.

#2928 Retry buildkite pipelines for nightly tests + on-commit pipelines except the ones in the diff plugin
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
Labels: auto-backport, v9.0.0

#2923 Followup on #2861
  connectors/agent/connector_record_manager.py
  connectors/protocol/connectors.py
  connectors/utils.py
  tests/agent/test_connector_record_manager.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v9.0.0

#2943 Bump pyOpenSSL lib version
  Makefile
  NOTICE.txt
  requirements/framework.txt
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0

#2911 [DOCS] Updates links to Elasticsearch documentation for 8.16.0
  README.md
  config.yml.example
  connectors/sync_job_runner.py
  docs/CONFIG.md
  docs/DEVELOPING.md
  docs/DOCKER.md
  docs/REFERENCE.md
  docs/UPGRADING.md
  docs/document-level-security/DROPBOX.md
  docs/document-level-security/GITHUB.md
  docs/document-level-security/SALESFORCE.md
  docs/document-level-security/SERVICENOW.md
  docs/reference/graphql.md
  docs/reference/notion.md
  docs/reference/opentext_documentum.md
  docs/reference/redis.md
  scripts/stack/README.md
Labels: documentation, auto-backport, v8.16.0, v9.0.0

#2951 Add nightly 8.16 DRA builds
  catalog-info.yaml
Labels: auto-backport, v9.0.0

#2957 use quotes on 8.16 version in catalog-info.yml
  catalog-info.yaml
Labels: auto-backport, v9.0.0

#2955 Fix `apt` invocations in `Dockerfile`s
  Dockerfile
  Dockerfile.ftest
Labels: auto-backport, v9.0.0

#2956 Adjusting inbetween release process to use dev branches
  .buildkite/release-pipeline.yml
  docs/RELEASING.md
Labels: auto-backport, v9.0.0, v8.17.0, v8.16.1

#2948 Remove MSSQL nightly functional tests from 8.15 for aarch64
  .buildkite/nightly_steps.yml
Labels: auto-backport, v9.0.0

#2965 updating the notice file
  NOTICE.txt
Labels: auto-backport, v9.0.0

#2966 Make local stack scripts work
  scripts/stack/run-stack.sh
  scripts/stack/update-kibana-user-password.sh
Labels: auto-backport, v9.0.0, v8.17.0, v8.16.1

#2959 update elasticsearch python client to 8.16
  NOTICE.txt
  pytest.ini
  requirements/framework.txt
Labels: auto-backport, v9.0.0, v8.17.0

#2967 [outlook] Filter users to only include active ones
  connectors/sources/outlook.py
  tests/sources/test_outlook.py
Labels: release_note, auto-backport, v9.0.0, v8.15.4, v8.17.0, v8.16.1, v8.15.5

#2981 [8.x] [Publishing] Load ES image for ftest from DRA artifact (#2979)
  tests/ftest.sh
  tests/sources/fixtures/azure_blob_storage/docker-compose.yml
  tests/sources/fixtures/box/docker-compose.yml
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/dir/docker-compose.yml
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/graphql/docker-compose.yml
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/mongodb/docker-compose.yml
  tests/sources/fixtures/mongodb_serverless/docker-compose.yml
  tests/sources/fixtures/mssql/docker-compose.yml
  tests/sources/fixtures/mysql/docker-compose.yml
  tests/sources/fixtures/network_drive/docker-compose.yml
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/oracle/docker-compose.yml
  tests/sources/fixtures/postgresql/docker-compose.yml
  tests/sources/fixtures/redis/docker-compose.yml
  tests/sources/fixtures/s3/docker-compose.yml
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/zoom/docker-compose.yml
Labels: backport

#2980 [CI] Add retries when fetching DRA artifacts
  tests/ftest.sh
Labels: auto-backport, v9.0.0, v8.17.0

#2984 Change dto for page blog documents to access fields in safe manner
  connectors/sources/confluence.py
Labels: release_note, auto-backport, v9.0.0, v8.17.0, v8.16.1, v8.15.5

#2994 Update for 8.17 FF
  .backportrc.json
  .buildkite/pipeline.yml
Labels: v9.0.0

#2996 [8.17] Update for 8.17 FF (#2994)
  .backportrc.json
  .buildkite/pipeline.yml
Labels: backport

#2998 Add nightly 8.17 CI
  catalog-info.yaml
Labels: v9.0.0

#2989 [Agent] Respect connector_id defined in agentless
  Dockerfile.agent
  connectors/agent/connector_record_manager.py
  connectors/agent/protocol.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  connectors/source.py
  connectors/sync_job_runner.py
  tests/agent/test_connector_record_manager.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v9.0.0

#2995 [8.x] Update for 8.17 FF (#2994)
  .backportrc.json
  .buildkite/pipeline.yml
Labels: backport

#2988 [8.15] Change dto for page blog documents to access fields in safe manner (#2984)
  connectors/sources/confluence.py
Labels: backport

#3007 Upgrade aiohttp to 3.11.7
  requirements/framework.txt
Labels: auto-backport, v9.0.0, v8.17.0, v8.16.1

#3010 Update pyOpenSSL to 24.3.0
  requirements/framework.txt
Labels: auto-backport, v9.0.0, v8.17.0, v8.16.1, v8.15.5
