Repository elastic/connectors, pull requests merged in 2024-10, with the labels that each got.

#2526 [Confluence] Update logs
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, team:external, v8.15.0.0

#2860 [8.x] [Confluence] Update logs (#2526)
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: backport

#2554 [Box] add logs
  connectors/sources/box.py
Labels: v8.16.0

#2528 [Oracle] Add logs
  connectors/sources/oracle.py
Labels: auto-backport, team:external, oracle, v8.15.0.0

#2865 [8.x] [Oracle] Add logs (#2528)
  connectors/sources/oracle.py
Labels: backport

#2867 Fix cli docs link
  connectors/cli/README.md
Labels: auto-backport, v9.0.0

#2861 Create connector record in agent component
  connectors/agent/component.py
  connectors/agent/config.py
  connectors/agent/connector_record_manager.py
  connectors/agent/protocol.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/agent/test_agent_config.py
  tests/agent/test_connector_record_manager.py
  tests/agent/test_protocol.py
Labels: v9.0.0

#2869 include full stack trace in concurrent exception
  connectors/utils.py
Labels: auto-backport, v8.16.0, v9.0.0, v8.15.3

#2859 Update docker namespace to integrations
  .buildkite/publish/publish-common.sh
  Makefile
  docs/DOCKER.md
  docs/RELEASING.md
  scripts/stack/docker/docker-compose.yml
Labels: auto-backport, v8.16.0, v9.0.0

#2874 Bump 8.15 branch to 8.15.4.0
  connectors/VERSION
Labels: v8.15.4

#2882 Fix stack scripts version logic
  scripts/stack/set-env.sh
Labels: auto-backport, v8.16.0, v9.0.0

#2885 [Docker] Add git so that non-wolfi images are usable
  Dockerfile
  Dockerfile.ftest
Labels: auto-backport, v8.16.0, v9.0.0

#2887 Docker: make a symlink to maintain backwards-compatibility after venv change, update makefile to build with --no-cache
  Dockerfile
  Dockerfile.wolfi
  Makefile
Labels: auto-backport, v8.16.0.0, v9.0.0

#2891 Update backportrc to alias 8.17.0 -> 8.x and dealias 8.16.0
  .backportrc.json
Labels: auto-backport, v9.0.0

#2893 Add 8.16 build jobs
  .backportrc.json
  catalog-info.yaml
Labels: auto-backport, v9.0.0

#2894 Update pipeline.yml to do packaging on 8.16
  .buildkite/pipeline.yml
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0

#2881 Properly display stacktrace for errors in extractor/sink tasks
  connectors/es/sink.py
Labels: auto-backport, v8.16.0, v9.0.0, v8.15.4, v8.17.0

#2905 Check for task cancelation before fetching exception
  connectors/es/sink.py
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0

#2902 [Connector APIs] Enable Connector APIs framework-wide + update functional tests
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/es/index.py
  connectors/kibana.py
  connectors/protocol/connectors.py
  connectors/sources/notion.py
  tests/sources/fixtures/README.md
  tests/sources/fixtures/azure_blob_storage/connector.json
  tests/sources/fixtures/box/connector.json
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/graphql/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/fixtures/microsoft_teams/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mssql/connector.json
  tests/sources/fixtures/mysql/connector.json
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/fixtures/notion/connector.json
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/oracle/connector.json
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/fixtures/redis/connector.json
  tests/sources/fixtures/s3/connector.json
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/servicenow/connector.json
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/fixtures/zoom/connector.json
  tests/test_kibana.py
Labels: auto-backport, v9.0.0

#2908 [8.x] [Connector APIs] Enable Connector APIs framework-wide + update functional tests (#2902)
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/es/index.py
  connectors/kibana.py
  connectors/protocol/connectors.py
  connectors/sources/notion.py
  tests/sources/fixtures/README.md
  tests/sources/fixtures/azure_blob_storage/connector.json
  tests/sources/fixtures/box/connector.json
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/graphql/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/fixtures/microsoft_teams/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mssql/connector.json
  tests/sources/fixtures/mysql/connector.json
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/fixtures/notion/connector.json
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/oracle/connector.json
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/fixtures/redis/connector.json
  tests/sources/fixtures/s3/connector.json
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/servicenow/connector.json
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/fixtures/zoom/connector.json
  tests/test_kibana.py
Labels: backport

#2909 [8.16] [Connector APIs] Enable Connector APIs framework-wide + update functional tests (#2902)
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/es/index.py
  connectors/kibana.py
  connectors/protocol/connectors.py
  connectors/sources/notion.py
  tests/sources/fixtures/README.md
  tests/sources/fixtures/azure_blob_storage/connector.json
  tests/sources/fixtures/box/connector.json
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/dropbox/connector.json
  tests/sources/fixtures/fixture.py
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/graphql/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/fixtures/microsoft_teams/connector.json
  tests/sources/fixtures/mongodb/connector.json
  tests/sources/fixtures/mongodb_serverless/connector.json
  tests/sources/fixtures/mssql/connector.json
  tests/sources/fixtures/mysql/connector.json
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/fixtures/notion/connector.json
  tests/sources/fixtures/onedrive/connector.json
  tests/sources/fixtures/oracle/connector.json
  tests/sources/fixtures/postgresql/connector.json
  tests/sources/fixtures/redis/connector.json
  tests/sources/fixtures/s3/connector.json
  tests/sources/fixtures/salesforce/connector.json
  tests/sources/fixtures/servicenow/connector.json
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/fixtures/zoom/connector.json
  tests/test_kibana.py
Labels: backport

#2914 Update example config yml with connectors api feature flag
  config.yml.example
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0

#2913 Allow Insecure HTTPS
  config.yml.example
  connectors/config.py
  connectors/es/client.py
  docs/DOCKER.md
Labels: auto-backport, v9.0.0

#2921 Removes gratuitous 'critical' logging
  connectors/es/sink.py
  connectors/protocol/connectors.py
  connectors/services/job_cleanup.py
  connectors/services/job_execution.py
  connectors/services/job_scheduling.py
Labels: auto-backport, v9.0.0

#2552 [Google Cloud Storage] Add logs
  connectors/sources/google_cloud_storage.py
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0
