Repository elastic/connectors, pull requests merged in 2024-07, with the labels that each got.

#2666 Bump aioboto
  requirements/aarch64.txt
  requirements/framework.txt
  requirements/ftest.txt
  requirements/x86_64.txt
  tests/sources/test_s3.py
Labels: auto-backport, v8.15.0, v8.15.0.0, v8.14.3

#2665 Build and publish Wolfi-based images only
  .buildkite/nightly_docker.yml
  .buildkite/publish/publish-common.sh
  .buildkite/release-pipeline.yml
Labels: auto-backport, v8.15.0.0

#2670 Remove Opentext Documentum connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/opentext_documentum.py
  tests/sources/fixtures/opentext_documentum/.env
  tests/sources/fixtures/opentext_documentum/config.yml
  tests/sources/fixtures/opentext_documentum/connector.json
  tests/sources/fixtures/opentext_documentum/docker-compose.yml
  tests/sources/fixtures/opentext_documentum/fixture.py
  tests/sources/fixtures/opentext_documentum/requirements.txt
  tests/sources/test_opentext_documentum.py
Labels: auto-backport, team:external, ot-documentum, v8.15.0.0

#2674 Include `manage_connector` privilege in generated api keys
  connectors/cli/connector.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2676 Bump stack version to 8.16
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
  tests/ftest.sh
Labels: auto-backport, v8.16.0

#2681 [PostgreSQL] Add new field id_columns in sync rules to generate id and adding support for views
  connectors/sources/postgresql.py
  tests/sources/test_postgresql.py
Labels: release_note, auto-backport, team:external, postgresql, v8.15.0.0

#2690 Replace task.name with task.get_name()
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v8.15.0, v8.14.3, v8.16.0, v8.16.0.0

#2694 clean more things
  Makefile
Labels: auto-backport, v8.16.0, v8.16.0.0

#2703 Bump VERSION to 8.14.3.1
  connectors/VERSION
Labels: auto-backport, v8.16.0.0

#2695 log in utc
  connectors/logger.py
  tests/test_logger.py
Labels: release_note, auto-backport, v8.16.0, v8.16.0.0

#2712 [DOCS] Update connectors overview table for 8.15
  docs/REFERENCE.md
Labels: documentation, auto-backport, v8.15.0.0

#2710 Cancel and fail downloads if exception happened
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v8.16.0.0

#2668 [Confluence] Fix flaky test case
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport

#2716 [Confluence] Fix HTML Tags from Body Content
  connectors/sources/atlassian.py
  connectors/sources/confluence.py
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/test_confluence.py
Labels: confluence, team:external, v8.16.0, v8.15.1, v8.14.4

#2696 [MSSQL] Add new field id_columns in sync rules to generate id and adding support for views
  connectors/sources/mssql.py
  tests/sources/test_mssql.py
Labels: release_note, auto-backport, team:external, mssql, v8.16.0.0

#2679 [Google Drive] Add Incremental Sync
  connectors/sources/google_drive.py
  tests/sources/test_google_drive.py
Labels: auto-backport, team:external, google-drive, v8.16.0, v8.16.0.0

#2723 Change docker-compose network in stack scripts to `elastic`
  scripts/stack/docker/docker-compose.yml
  scripts/stack/run-stack.sh
Labels: v8.16.0.0
