Repository elastic/connectors, pull requests merged in 2024-06, with the labels that each got.

#2609 [8.14] [Confluence] Ingest full body of documents in sync rules (#2602)
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: backport

#2611 Fix glob in artifact_paths steps for release
  .buildkite/release-pipeline.yml
Labels: auto-backport, v8.14.0.0, v8.15.0.0

#2606 Catch job claim failures, and result in job termination
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  tests/protocol/test_connectors.py
  tests/test_sync_job_runner.py
Labels: release_note, auto-backport, v8.14.0, v8.15.0, v8.15.0.0, v8.13.5

#2620 [8.13] Catch job claim failures, and result in job termination (#2606)
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  tests/protocol/test_connectors.py
  tests/test_sync_job_runner.py
Labels: backport

#2626 [Connector API] Validate and activate filtering with API call
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0.0

#2529 [PostgreSQL] Add logs
  connectors/sources/postgresql.py
Labels: auto-backport, team:external, postgresql, v8.15.0.0

#2628 Bump elasticsearch and elastic-transport versions
  requirements/framework.txt
Labels: v8.15.0.0

#2633 Bump to 8.14.2.0
  connectors/VERSION
Labels: v8.14.1.0

#2630 [Confluence] Add Fields Author and Created Date
  connectors/sources/confluence.py
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/test_confluence.py
Labels: confluence, team:external

#2644 Create scheduled jobs with Connector APIs
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2646 Claim sync jobs with Connector APIs
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2648 use buildkite image for main
  README.md
Labels: auto-backport, v8.15.0.0

#2649 Add set_env to tests that init elasticsearch client
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0.0

#2651 [Confluence] Fix data loss for Data Center during Advance-Sync
  connectors/sources/confluence.py
Labels: confluence, team:external, v8.15.0, v8.14.2

#2652 Update stack scripts README
  scripts/stack/README.md
Labels: auto-backport, v8.15.0.0

#2653 Add service.idling: 1 to all ftests + decrease size of ftest for gcs
  tests/sources/fixtures/azure_blob_storage/config.yml
  tests/sources/fixtures/box/config.yml
  tests/sources/fixtures/confluence/config.yml
  tests/sources/fixtures/dir/config.yml
  tests/sources/fixtures/dropbox/config.yml
  tests/sources/fixtures/github/config.yml
  tests/sources/fixtures/google_cloud_storage/config.yml
  tests/sources/fixtures/google_cloud_storage/fixture.py
  tests/sources/fixtures/google_drive/config.yml
  tests/sources/fixtures/graphql/config.yml
  tests/sources/fixtures/jira/config.yml
  tests/sources/fixtures/microsoft_teams/config.yml
  tests/sources/fixtures/mongodb/config.yml
  tests/sources/fixtures/mongodb_serverless/config.yml
  tests/sources/fixtures/mssql/config.yml
  tests/sources/fixtures/mysql/config.yml
  tests/sources/fixtures/network_drive/config.yml
  tests/sources/fixtures/notion/config.yml
  tests/sources/fixtures/onedrive/config.yml
  tests/sources/fixtures/opentext_documentum/config.yml
  tests/sources/fixtures/oracle/config.yml
  tests/sources/fixtures/postgresql/config.yml
  tests/sources/fixtures/redis/config.yml
  tests/sources/fixtures/s3/config.yml
  tests/sources/fixtures/salesforce/config.yml
  tests/sources/fixtures/servicenow/config.yml
  tests/sources/fixtures/sharepoint_online/config.yml
  tests/sources/fixtures/sharepoint_server/config.yml
  tests/sources/fixtures/zoom/config.yml
Labels: auto-backport, v8.15.0.0, v8.13.4, v8.14.2

#2656 [Amazon S3] Remove security concerned logs
  connectors/sources/s3.py
Labels: auto-backport, team:external, s3, v8.15.0.0, v8.13.5, v8.14.2

#2659 Use Connector APIs to update sync job stats
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2661 Ensure orchestrator tasks are always canceled
  connectors/connectors_cli.py
  connectors/es/sink.py
  connectors/sync_job_runner.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: release_note, auto-backport, v8.15.0, v8.15.0.0, v8.14.2

#2650 Check ES version compatibility and build flavor on startup
  README.md
  connectors/es/client.py
  connectors/preflight_check.py
  connectors/service_cli.py
  scripts/verify.py
  tests/ftest.sh
  tests/test_preflight_check.py
  tests/test_service_cli.py
Labels: v8.15.0.0
