Repository elastic/connectors, pull requests merged in 2024-02, with the labels that each got.

#2075 Add RCFs for Jira and Confluence data center
  connectors/sources/confluence.py
  connectors/sources/jira.py
  tests/sources/test_confluence.py
  tests/sources/test_jira.py
Labels: auto-backport, v8.13.0.0

#2114 Improve debug log for next sync message
  connectors/services/job_scheduling.py
Labels: auto-backport, v8.13.0.0

#2102 fix acl query template
  connectors/access_control.py
  tests/sources/test_confluence.py
  tests/sources/test_github.py
  tests/sources/test_google_drive.py
  tests/sources/test_jira.py
  tests/sources/test_salesforce.py
  tests/sources/test_servicenow.py
  tests/test_access_control.py
Labels: release_note, auto-backport, v8.13.0, v8.13.0.0

#2107 Switch to an official Oracle container image in functional tests
  tests/sources/fixtures/oracle/connector.json
  tests/sources/fixtures/oracle/docker-compose.yml
  tests/sources/fixtures/oracle/fixture.py
Labels: auto-backport, v8.12.0, v8.13.0.0

#2111 Add problem URL to error message
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2079 Make MemQueue used in sync configurable via config options
  config.yml
  connectors/config.py
  connectors/es/sink.py
Labels: release_note, auto-backport, v8.12.0, v8.13.0.0

#2109 [8.12] [GitHub] Fix scopes related issue (#1997)
  connectors/sources/github.py
  tests/sources/fixtures/github/fixture.py
  tests/sources/test_github.py
Labels: backport

#2083 [Redis] Add ftests
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  tests/sources/fixtures/redis/config.yml
  tests/sources/fixtures/redis/connector.json
  tests/sources/fixtures/redis/docker-compose.yml
  tests/sources/fixtures/redis/fixture.py
  tests/sources/fixtures/redis/requirements.txt
Labels: auto-backport, v8.13.0.0

#2082 [Redis] Advanced Sync rules and documentation
  connectors/sources/redis.py
  docs/REFERENCE.md
  docs/reference/redis.md
  tests/sources/test_redis.py
Labels: v8.13.0

#2119 Revert "Specify port when calling all smbclient methods in network drive connector (#1898)"
  connectors/sources/network_drive.py
Labels: auto-backport, v8.12.1, v8.13.0.0

#2115 Use API keys for native connector syncs
  connectors/es/management_client.py
  connectors/es/sink.py
  connectors/protocol/connectors.py
  connectors/source.py
  connectors/sync_job_runner.py
  docs/CONNECTOR_PROTOCOL.md
  tests/es/test_management_client.py
  tests/protocol/test_connectors.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2105 Add logic to send a ping to connector's backend every loop
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: release_note, auto-backport, v8.13.0.0

#2056 Documentation for Salesforce DLS
  docs/document-level-security/SALESFORCE.md
Labels: auto-backport, team:external, salesforce, v8.13.0, v8.13.0.0

#2110 Add Notion configurations and indexing Implementation
  connectors/config.py
  connectors/sources/notion.py
  requirements/framework.txt
  tests/sources/test_notion.py
Labels: v8.13.0, notion

#2138 Make Gmail connector's 'subject' field label match docs
  connectors/sources/gmail.py
Labels: auto-backport, v8.13.0.0

#2132 Add volumes to Salesforce Fixture
  connectors/sources/salesforce.py
  tests/sources/fixtures/salesforce/fixture.py
Labels: auto-backport, v8.13.0.0

#2142 Enabled incremental syncs for more connectors
  connectors/sources/azure_blob_storage.py
  connectors/sources/github.py
  connectors/sources/gmail.py
  connectors/sources/microsoft_teams.py
  connectors/sources/outlook.py
  connectors/sources/salesforce.py
Labels: release_note, auto-backport, v8.13.0, v8.13.0.0

#2090 Bump idle job threshold to 5 minutes
  connectors/protocol/connectors.py
Labels: release_note, auto-backport, v8.13.0.0

#2148 Revert "Add logic to send a ping to connector's backend every loop (#2105)"
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2146 Revert "Bump Dockerfile base image to python:3.11.6-slim (#1911)"
  Dockerfile
  Dockerfile.ftest
Labels: auto-backport, v8.13.0, v8.13.0.0, v8.12.1.1

#2150 Bump 8.12 Branch to Version 8.12.1.2
  connectors/VERSION
Labels: v8.12.1.2

#2145 Redis connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/redis.py
  docs/REFERENCE.md
  docs/reference/redis.md
  requirements/framework.txt
  tests/sources/fixtures/redis/config.yml
  tests/sources/fixtures/redis/connector.json
  tests/sources/fixtures/redis/docker-compose.yml
  tests/sources/fixtures/redis/fixture.py
  tests/sources/fixtures/redis/requirements.txt
  tests/sources/test_redis.py
Labels: auto-backport, v8.13.0.0

#2143 Add E2E for Notion
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/notion.py
  tests/sources/fixtures/notion/.env
  tests/sources/fixtures/notion/config.yml
  tests/sources/fixtures/notion/connector.json
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/notion/fixture.py
  tests/sources/test_notion.py
Labels: v8.13.0.0

#2108 Add DLS for Jira Data Center
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.13.0, v8.13.0.0

#2141 [Sharepoint server] crawl the root site
  connectors/sources/sharepoint_server.py
  tests/sources/test_sharepoint_server.py
Labels: release_note, sharepoint, v8.13.0.0

#2153 Notion Connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/notion.py
  requirements/framework.txt
  tests/sources/fixtures/notion/.env
  tests/sources/fixtures/notion/config.yml
  tests/sources/fixtures/notion/connector.json
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/notion/fixture.py
  tests/sources/test_notion.py
Labels: auto-backport, v8.13.0.0

#2158 [8.13] Bump stack versions.
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
  tests/ftest.sh
Labels: auto-backport, v8.13.0.0

#2157 [Notion] Increase test coverage
  tests/sources/test_notion.py
Labels: auto-backport, v8.13.0.0

#2151 Add documentation for Notion connector
  docs/reference/notion.md
Labels: auto-backport, v8.13.0.0

#2171 Add retry to ESIndex class methods
  connectors/es/index.py
  tests/es/test_index.py
Labels: auto-backport, v8.14.0.0

#2155 Change log level for retry messages
  connectors/es/client.py
  connectors/utils.py
Labels: auto-backport, v8.13.0.0, v8.14.0

#2152 Pipeline Creation for Building and Pushing Connectors Docker Images
  .buildkite/publish/build-docker.sh
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
  catalog-info.yaml
Labels: auto-backport, v8.13.0.0

#2180 [CI] Fix Issues in Docker Publishing Pipeline
  .buildkite/publish/build-docker.sh
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2184 Remove unsafe dict call from ServiceNow
  connectors/sources/servicenow.py
  tests/sources/test_servicenow.py
Labels: auto-backport, v8.13.0, v8.14.0, v8.14.0.0, v8.12.2.0

#2161 Add atlassian.py for Jira Data Center DLS
  connectors/sources/atlassian.py
Labels: auto-backport, jira, team:external, v8.13.0, v8.14.0.0

#2196 Fix native API key authentication
  connectors/es/sink.py
  connectors/sync_job_runner.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.13.0, v8.13.0.0, v8.14.0, v8.14.0.0

#2198 [8.13] Generate API keys when running native connector syncs (#2188)
  connectors/es/management_client.py
  connectors/services/job_execution.py
  connectors/source.py
  connectors/utils.py
  tests/es/test_management_client.py
  tests/services/test_job_execution.py
  tests/test_utils.py
Labels: backport

#2187 [Network Drive] Fix Download of documents in Windows and debug logs
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.13.0, v8.14.0.0

#2208 Bump version to 8.12.2.0
  connectors/VERSION
Labels: auto-backport, v8.12.2.0

#2204 Add more debug logging in job execution
  connectors/services/job_execution.py
  connectors/sync_job_runner.py
Labels: auto-backport, v8.14.0.0

#2207 [Notion]Fix error on fetching search queries
  connectors/sources/notion.py
  tests/sources/test_notion.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2206 Add more logs in Outlook connector
  connectors/sources/outlook.py
  tests/sources/test_outlook.py
Labels: auto-backport, team:external, outlook, v8.13.0.0, v8.14.0.0

#2219 [8.12] Pipeline Creation for Building and Pushing Connectors Docker Images (#2152)
  .buildkite/publish/build-docker.sh
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
  catalog-info.yaml
Labels: backport

#2220 [8.12] [CI] Fix Issues in Docker Publishing Pipeline (#2180)
  .buildkite/publish/build-docker.sh
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/release-pipeline.yml
Labels: backport

#2221 Update VERSION after 8.12.2.0 release
  connectors/VERSION
Labels: v8.12.2.1
