Repository elastic/connectors, pull requests merged in 2024-05, with the labels that each got.

#2481 Upgrade motor and pymongo[srv]
  requirements/aarch64.txt
  requirements/arm64.txt
  requirements/x86_64.txt
Labels: auto-backport, v8.14.0, v8.13.3, v8.15.0.0

#2445 Copy config.yml from config.yml.example
  scripts/stack/copy-config.sh
  scripts/stack/run-stack.sh
Labels: auto-backport, v8.14.0, v8.15.0.0

#2484 Use 8.3 mysql docker image for ftest
  tests/sources/fixtures/mysql/docker-compose.yml
Labels: auto-backport, v8.14.0, v8.13.3, v8.15.0.0

#2429 Update Oracle connector to support service name
  connectors/sources/oracle.py
  tests/sources/fixtures/oracle/connector.json
  tests/sources/test_oracle.py
Labels: auto-backport, v8.15.0.0

#2489 Add debug logs for extraction configuration state
  connectors/sync_job_runner.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2399 Build and push Docker image based on Chainguard base image
  .buildkite/nightly_docker.yml
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  .buildkite/publish/build-docker.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/publish_docker.sh
  .buildkite/release-pipeline.yml
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  Makefile
  docs/DOCKER.md
  tests/ftest.sh
  tests/sources/fixtures/box/docker-compose.yml
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/graphql/docker-compose.yml
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/opentext_documentum/docker-compose.yml
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/zoom/docker-compose.yml
Labels: auto-backport, v8.14.0.0

#2496 Bump product version to 8.13.3.0
  connectors/VERSION
Labels: v8.13.3

#2498 Bump product version to 8.13.3.1
  connectors/VERSION
Labels: v8.13.3

#2500 Update `connectors-nightly-dockers` pipeline to use the right branches
  catalog-info.yaml
Labels: auto-backport, v8.15.0.0

#2503 Make CLI docs up-to-date
  docs/CLI.md
Labels: auto-backport, v8.15.0.0

#2494 Fix SharePoint Server API response for Site Pages and IDs
  connectors/sources/sharepoint_server.py
  tests/sources/fixtures/sharepoint_server/fixture.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, v8.14.0, v8.15.0.0

#2511 Support serverless in index list command
  connectors/cli/index.py
  connectors/connectors_cli.py
  connectors/es/management_client.py
  tests/test_connectors_cli.py
Labels: bug, v8.14.0

#2506 [Jira] Handle empty response when status code is 200
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.15.0.0

#2508 Add author and editor name instead of author/editor id
  connectors/sources/sharepoint_server.py
  tests/sources/fixtures/sharepoint_server/fixture.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, team:external, v8.15.0.0

#2507 [GitHub] Raising 403 exception
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: release_note, auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2516 Run all functional tests if any requirements change
  .buildkite/pipeline.yml
Labels: auto-backport, v8.13.0, v8.14.0, v8.15.0.0

#2521 [8.13] Run all functional tests if any requirements change (#2516)
  .buildkite/pipeline.yml
Labels: backport

#2515 Upgrade aiohttp and pyOpenSSL
  requirements/framework.txt
Labels: auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2514 [PostgreSQL] Updated queries to support primary key column name with uppercase letters
  connectors/sources/postgresql.py
Labels: release_note, auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2532 Add * as default value for comma-separated lists that support it
  connectors/sources/mssql.py
  connectors/sources/mysql.py
  connectors/sources/oracle.py
  connectors/sources/postgresql.py
  connectors/sources/redis.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.14.0, v8.15.0.0

#2505 [Jira] show custom fields seperately
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: release_note, auto-backport, jira, team:external, v8.15.0.0

#2534 Bump version to 8.13.4.0
  connectors/VERSION
Labels: v8.13.4

#2495 Add ancestor title in confluence
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, v8.15.0.0

#2535 Update setuptools package on installation
  Makefile
Labels: auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2536 [8.14][Jira] Handle empty response when status code is 200 (#2506)
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: backport

#2537 [8.13][Jira] Handle empty response when status code is 200 (#2506)
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: backport

#2547 Enabled incremental syncs for Notion Connector
  connectors/sources/notion.py
Labels: release_note, auto-backport, v8.15.0.0

#2540 [Confluence] Fix flaky test case
  tests/sources/test_confluence.py
Labels: auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2548 Add author/editor for all entities
  connectors/sources/sharepoint_server.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, v8.15.0.0

#2556 Use newer discuss category
  .github/ISSUE_TEMPLATE/config.yml
Labels: auto-backport, v8.15.0.0

#2558 [SharePoint Server]Fix flaky test
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, team:external, v8.15.0.0

#2549 [Confluence] Add labels in confluence
  connectors/sources/confluence.py
  tests/sources/fixtures/confluence/connector.json
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, team:external, v8.15.0.0

#2561 Implement feature flag for Elasticsearch API + use for connector heartbeat
  config.yml.example
  connectors/config.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  connectors/utils.py
  tests/test_utils.py
Labels: release_note, auto-backport, v8.15.0.0

#2563 [Confluence] Fix flaky test_get_with_429_status
  tests/sources/test_confluence.py
Labels: auto-backport, v8.15.0.0

#2543 [Azure Blob Storage] Optimize memory consumption
  connectors/sources/azure_blob_storage.py
  requirements/framework.txt
  tests/sources/test_azure_blob_storage.py
Labels: auto-backport, azure-blob-storage, team:external, v8.14.0, v8.15.0.0, v8.13.4

#2560 [Box] Fix end signal not enqueued
  connectors/sources/box.py
  tests/sources/test_box.py
Labels: auto-backport, box, v8.14.0, v8.15.0, v8.15.0.0

#2570 Update docker.elastic.co/ci-agent-images/drivah Docker tag to v0.25.0
  .buildkite/release-pipeline.yml
Labels: auto-backport, v8.15.0.0

#2576 [Outlook] Upgrade Exchangelib
  requirements/framework.txt
Labels: release_note, auto-backport, outlook, v8.14.0, v8.15.0.0

#2546 [Servicenow] Fix end signal not enqueued
  connectors/sources/servicenow.py
  tests/sources/test_servicenow.py
Labels: auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2575 Use same aiomysql version on different platforms
  requirements/aarch64.txt
  requirements/framework.txt
  requirements/x86_64.txt
Labels: auto-backport, v8.14.0.0, v8.15.0.0, v8.13.4

#2586 [Job scheduling] Use UTC timezone with timestamps
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  connectors/utils.py
  tests/services/test_job_scheduling.py
  tests/test_utils.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2587 Migration for timezone aware timestamps
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v8.15.0, v8.15.0.0

#2527 [MSSQL] Add logs
  connectors/sources/mssql.py
Labels: auto-backport, team:external, mssql, v8.15.0.0

#2594 Switch to tzcron for schedule parsing + add tests for supported cron expressions in Kibana
  connectors/utils.py
  requirements/framework.txt
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/fixtures/google_drive/connector.json
  tests/sources/fixtures/graphql/connector.json
  tests/sources/fixtures/jira/connector.json
  tests/sources/fixtures/notion/connector.json
  tests/test_utils.py
Labels: release_note, auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2593 Saleforce client token generation error logging
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: auto-backport, v8.14.0, v8.15.0.0, v8.13.4

#2601 Change version after 8.11.4.1 release
  connectors/VERSION
Labels: v8.11.4.2

#2598 [Sharepoint Online] Replace deep dictionary gets with safer util function
  connectors/sources/sharepoint_online.py
Labels: auto-backport, v8.14.0, v8.15.0.0

#2602 [Confluence] Ingest full body of documents in sync rules
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, v8.14.0, v8.15.0.0
