Repository elastic/connectors, pull requests merged in 2024-04, with the labels that each got.

#2289 Update RELEASING.md with new docker release steps
  docs/DOCKER.md
  docs/RELEASING.md
Labels: auto-backport, v8.14.0.0

#2297 [Notion] Implement an ability to retry for failed paginated api call
  connectors/sources/notion.py
  tests/sources/test_notion.py
Labels: auto-backport, v8.14.0.0

#2304 [Jira] Add more logs
  connectors/sources/jira.py
Labels: auto-backport, jira, team:external, v8.14.0, v8.14.0.0

#2134 Add GraphQL configurations and indexing Implementation
  connectors/config.py
  connectors/sources/graphql.py
  requirements/framework.txt
  tests/sources/test_graphql.py
Labels: team:external, v8.14.0, graphql

#2322 remind folks not to make a PR with leaked creds
  .github/PULL_REQUEST_TEMPLATE.md
Labels: auto-backport, v8.14.0.0

#2328 Create a nested_get_from_dict function in utils
  connectors/protocol/connectors.py
  connectors/sources/github.py
  connectors/utils.py
  tests/protocol/test_connectors.py
  tests/sources/test_github.py
  tests/test_utils.py
Labels: v8.14.0, v8.14.0.0

#2330 Apply function nested_get_from_dict to more places
  connectors/sources/github.py
Labels: v8.14.0, v8.14.0.0

#2342 Update README.md
  scripts/stack/README.md
Labels: auto-backport, v8.14.0.0

#2344 Bump elasticsearch package from 8.12.0 to 8.13.0
  requirements/framework.txt
Labels: auto-backport, v8.14.0.0

#2323 Log all counters
  connectors/sync_job_runner.py
  tests/test_sync_job_runner.py
Labels: release_note, auto-backport, v8.14.0, v8.14.0.0

#2308 Fix pagination for confluence datacenter sync rules
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, v8.14.0.0

#2359 [Framework] Use Cancellable sleeps in retryable
  connectors/service_cli.py
  connectors/utils.py
  tests/test_service_cli.py
Labels: auto-backport, v8.11.0, v8.12.0, v8.13.0, v8.14.0.0

#2352 Say that we only work with python 3.10
  docs/DEVELOPING.md
Labels: auto-backport, v8.9.3.0, v8.10.5, v8.11.5

#2367 [CLI] Show help page for "-h" argument
  connectors/connectors_cli.py
  docs/CLI.md
  tests/test_connectors_cli.py
Labels: auto-backport, v8.14.0.0

#2368 [CLI] Extend version test
  tests/test_connectors_cli.py
Labels: auto-backport, v8.14.0.0

#2369 [CLI] Improve config missing error handling
  connectors/connectors_cli.py
Labels: auto-backport, v8.14.0.0

#2371 [Service CLI] Log exception, if uvloop couldn't be enabled
  connectors/service_cli.py
Labels: auto-backport, v8.14.0.0

#2363 Add X-elastic-product-origin header
  connectors/es/client.py
Labels: v8.14.0, v8.14.0.0

#2374 Update connector.json for GitHub ftest
  tests/sources/fixtures/github/connector.json
Labels: v8.14.0, v8.14.0.0

#2375 [Service CLI] Migrate to click
  connectors/service_cli.py
  tests/test_service_cli.py
Labels: auto-backport, v8.14.0.0

#2326 [Jira] Add more logging, tests and constants
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, v8.14.0.0

#2347 count more things
  connectors/es/sink.py
  connectors/protocol/connectors.py
  connectors/sync_job_runner.py
  connectors/utils.py
  tests/test_sink.py
Labels: release_note, auto-backport, v8.14.0, v8.14.0.0

#2379 [CLI] Track CLI usage through user agent header
  connectors/cli/auth.py
  connectors/cli/connector.py
  connectors/cli/index.py
  connectors/cli/job.py
  connectors/es/cli_client.py
  connectors/es/client.py
  tests/es/test_cli_client.py
  tests/es/test_client.py
  tests/test_connectors_cli.py
Labels: auto-backport, v8.14.0.0

#2350 Refactor code structure of Jira and Confluence
  connectors/sources/confluence.py
  connectors/sources/jira.py
  tests/sources/test_confluence.py
  tests/sources/test_jira.py
Labels: auto-backport, team:external, v8.14.0.0

#2336 [GraphQL] Update GraphQL Object List RCF for identifying unique fields
  connectors/sources/graphql.py
  tests/sources/fixtures/graphql/connector.json
  tests/sources/test_graphql.py
Labels: v8.14.0.0

#2377 [Jira] Fix NotFound when the path is present in host URL
  connectors/sources/jira.py
  tests/sources/test_atlassian.py
  tests/sources/test_jira.py
Labels: release_note, auto-backport, jira, team:external, v8.14.0.0, v8.13.3

#2383 GraphQL Connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/graphql.py
  requirements/framework.txt
  tests/sources/fixtures/graphql/config.yml
  tests/sources/fixtures/graphql/connector.json
  tests/sources/fixtures/graphql/docker-compose.yml
  tests/sources/fixtures/graphql/fixture.py
  tests/sources/test_graphql.py
Labels: auto-backport, team:external, v8.14.0, graphql, v8.14.0.0

#2372 Use graphql method of GitHubAPI for GraphQL requests
  connectors/sources/github.py
  tests/sources/fixtures/github/connector.json
  tests/sources/fixtures/github/fixture.py
  tests/sources/test_github.py
Labels: v8.14.0, v8.14.0.0

#2389 Update connector.json for GitHub ftest
  tests/sources/fixtures/github/connector.json
Labels: v8.14.0, v8.14.0.0

#2381 Update GitHubClient to support GitHub App authentication
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: v8.14.0, v8.14.0.0

#2388 [8.13] [Jira] Fix NotFound when the path is present in host URL #2377
  connectors/sources/jira.py
  tests/sources/test_atlassian.py
  tests/sources/test_jira.py
Labels: backport

#2318 Opentext Documentum connector
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/config.py
  connectors/sources/opentext_documentum.py
  tests/sources/fixtures/opentext_documentum/.env
  tests/sources/fixtures/opentext_documentum/config.yml
  tests/sources/fixtures/opentext_documentum/connector.json
  tests/sources/fixtures/opentext_documentum/docker-compose.yml
  tests/sources/fixtures/opentext_documentum/fixture.py
  tests/sources/fixtures/opentext_documentum/requirements.txt
  tests/sources/test_opentext_documentum.py
Labels: auto-backport, team:external, v8.14.0, v8.14.0.0, ot-documentum

#2380 [Confluence] Ensure end signals are added to queue if exception occurs
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, v8.14.0.0

#2390 [Jira] Add a new field for project and issue doc
  connectors/sources/jira.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.14.0.0

#2398 Add unit test for atlassian fetch_all_users
  tests/sources/test_atlassian.py
Labels: auto-backport, v8.14.0, v8.14.0.0

#2364 Attempt to handle errors from Sink
  connectors/es/sink.py
  connectors/sync_job_runner.py
  connectors/utils.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
  tests/test_utils.py
Labels: release_note, auto-backport, v8.14.0, v8.14.0.0, v8.15.0

#2337 [Notion] [Bugfix] Handle error on fetching children of external objects
  connectors/sources/notion.py
  tests/sources/test_notion.py
Labels: auto-backport, v8.14.0.0

#2384 Update config validation to support GitHub App authentication
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.14.0, v8.14.0.0

#2402 [8.14] Attempt to handle errors from Sink (#2364)
  connectors/es/sink.py
  connectors/sync_job_runner.py
  connectors/utils.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
  tests/test_utils.py
Labels: backport, v8.14.0

#2401 Bump to 8.15
  .backportrc.json
  catalog-info.yaml
  connectors/VERSION
  tests/ftest.sh
Labels: auto-backport, v8.14.0.0, v8.15.0, v8.15.0.0

#2404 new community slack channel
  docs/SUPPORT.md
Labels: auto-backport, v8.14.0.0, v8.15.0

#2386 Update GitHub access control sync to support GitHub App
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.14.0, v8.14.0.0

#2312 [Bugfix][Notion] Objects not shared with Integration or not found should not fail the sync
  connectors/sources/notion.py
  tests/sources/test_notion.py
Labels: auto-backport, v8.14.0.0, v8.15.0.0

#2409 Bump es version for ftests to 8.15
  tests/ftest.sh
Labels: auto-backport, v8.15.0.0

#2414 [8.14] [Notion] Handle error on fetching children of external objects and Objects not shared with Integration
  connectors/sources/notion.py
  tests/sources/test_notion.py
Labels: backport

#2392 GraphQL documentation
  docs/reference/graphql.md
Labels: auto-backport, team:external, graphql, v8.14.0.0

#2428 Safely get author login for PR reviews
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.12.0, v8.13.0, v8.14.0, v8.15.0.0

#2425 [GraphQL] Rename "graphql_object_list" to "graphql_object_to_id_map"
  connectors/sources/graphql.py
  docs/reference/graphql.md
  tests/sources/fixtures/graphql/connector.json
  tests/sources/test_graphql.py
Labels: auto-backport, v8.14.0, v8.14.0.0

#2412 Update GitHub connector to sync content for GitHub App authentication
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.14.0

#2417 [Confluence] Use close_session to unset session variable
  connectors/sources/confluence.py
Labels: auto-backport, v8.14.0, v8.14.0.0, v8.15.0.0

#2416 [Opentext Documentum] Connector client documentation
  docs/reference/opentext_documentum.md
Labels: auto-backport, team:external, ot-documentum, v8.15.0.0

#2447 [8.14] [Opentext Documentum] Connector client documentation (#2416)
  docs/reference/opentext_documentum.md
Labels: backport

#2419 Add SharePoint Server DLS
  connectors/sources/sharepoint_server.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, team:external, v8.15.0.0

#2449 Update scripts/stack/README.md
  scripts/stack/README.md
Labels: auto-backport, v8.14.0, v8.15.0.0

#2442 [Jira] Map custom field ids with their names
  connectors/sources/jira.py
  tests/sources/fixtures/jira/fixture.py
  tests/sources/test_jira.py
Labels: auto-backport, jira, team:external, v8.15.0.0

#2444 [Jira] Add support for reserved keywords as a project key in `Jira project keys` RCF
  connectors/sources/jira.py
Labels: auto-backport, jira, team:external, v8.15.0.0

#2454 [GitHub] Add author to issue and pull request docs
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.14.0, v8.15.0.0

#2355 [Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree for sync rule
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.14.0.0, v8.13.3

#2338 [8.13] [Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree (#2286)
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: backport

#2458 [Network Drive] Fix unknown enum error: 0xc0000070
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.14.0, v8.13.3, v8.15.0.0

#2462 [8.13] [Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree for sync rule (#2355)
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: backport

#2421 Add DLS in outlook
  connectors/sources/outlook.py
  tests/sources/test_outlook.py
Labels: auto-backport, v8.15.0.0

#2459 [Confluence] Handle rate limit
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, confluence, team:external, v8.15.0.0

#2470 Fix concurrent scheduling
  connectors/services/job_scheduling.py
Labels: release_note, auto-backport, v8.14.0, v8.15.0.0

#2271 Don't fail the sync if there are failed operations in the bulk api request
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v8.14.0, v8.14.0.0, v8.15.0
