Repository elastic/connectors, pull requests merged in 2024-09, with the labels that each got.

#2787 Add code for running connectors in Agent
  Makefile
  connectors/agent/README.md
  connectors/agent/cli.py
  connectors/agent/component.py
  connectors/agent/config.py
  connectors/agent/protocol.py
  connectors/agent/service_manager.py
  connectors/config.py
  requirements/agent.txt
  requirements/framework.txt
  requirements/ftest.txt
  setup.py
  tests/agent/test_agent_config.py
  tests/agent/test_cli.py
  tests/agent/test_component.py
  tests/agent/test_protocol.py
  tests/agent/test_service_manager.py
Labels: auto-backport, v8.16.0

#2797 [Postgres] Removed sorting for primary keys
  connectors/sources/postgresql.py
Labels: team:external, postgresql, v8.16.0, v8.15.0.1

#2794 [Docs] Add tip about self-signed certificate
  docs/DOCKER.md
Labels: v8.16.0, v8.16.0.0

#2807 Delete README + add comment to test_cli
  connectors/agent/README.md
  tests/agent/test_cli.py
Labels: auto-backport, v8.16.0

#2796 Allow connectors to sync content into alias
  connectors/es/management_client.py
  connectors/es/sink.py
  tests/es/test_management_client.py
  tests/test_sink.py
Labels: auto-backport, v8.16.0

#2810 Return back connectors/sources/__init__.py
  connectors/sources/__init__.py
Labels: auto-backport, v8.16.0

#2811 Add missing __init__.py files
  .coveragerc
  connectors/agent/__init__.py
  connectors/cli/__init__.py
Labels: auto-backport, v8.16.0

#2812 Mass backport into 8.x branch
  .coveragerc
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  connectors/agent/README.md
  connectors/agent/__init__.py
  connectors/cli/__init__.py
  connectors/es/management_client.py
  connectors/es/sink.py
  connectors/sources/__init__.py
  connectors/sync_job_runner.py
  tests/agent/test_cli.py
  tests/es/test_management_client.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: v8.16.0

#2817 Forcefully downgrade pyasn1 to 0.6.0
  requirements/framework.txt
Labels: auto-backport, v8.16.0, v8.15.2

#2800 Bump main to 9.0
  connectors/VERSION
  tests/ftest.sh
Labels: auto-backport, v9.0.0

#2806 Make CI run agent tests too for now
  .coveragerc
  Makefile
Labels: auto-backport, v8.16.0

#2825 Add retry for on-commit and nightly pipelines
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
Labels: auto-backport, v8.16.0, v9.0.0, v8.15.2

#2815 Add everything needed to have a dockerfile for agent testing
  Dockerfile.agent
  Makefile
  resources/agent/python-elastic-agent-client
  resources/agent/python-elastic-agent-client.spec.yml
Labels: auto-backport, v8.16.0, v9.0.0

#2804 add back release pipeline
  .buildkite/publish/build-docker.sh
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/git-setup.sh
  .buildkite/publish/manual-release/restore-stack-version.sh
  .buildkite/publish/manual-release/update-release-version.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/publish_docker.sh
  .buildkite/release-pipeline.yml
  .coveragerc
  .gitignore
  catalog-info.yaml
  connectors/preflight_check.py
  docs/RELEASING.md
  tests/test_preflight_check.py
Labels: auto-backport, v8.16.0

#2839 Minor fixes for agent component
  Makefile
  connectors/agent/config.py
  tests/agent/test_agent_config.py
Labels: auto-backport, v9.0.0

#2842 Bump 8.15 Branch Version to 8.15.2.0
  connectors/VERSION
Labels: v8.15.2

#2832 [Network Drive] fix duplicate ids in access control sync
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: release_note, auto-backport, team:external, network_drive, v8.16.0, v8.15.2

#2809 Update approach to logging in connector component
  connectors/agent/cli.py
  connectors/agent/component.py
  connectors/agent/config.py
  connectors/agent/logger.py
  connectors/agent/protocol.py
  connectors/agent/service_manager.py
  connectors/config.py
  tests/agent/test_agent_config.py
  tests/agent/test_protocol.py
Labels: auto-backport, v8.16.0

#2854 Bump 8.15 Branch to 8.15.3.0
  connectors/VERSION
Labels: v8.15.3

#2850 [Agent] Improvements to agents protocol handler
  connectors/agent/protocol.py
  tests/agent/test_protocol.py
Labels: auto-backport, v9.0.0

#2846 Rename the ingestion-team
  .github/CODEOWNERS
  catalog-info.yaml
  docs/CONTRIBUTING.md
Labels: auto-backport, v9.0.0

#2852 Unify smbprotocol deps and bump to latest
  requirements/aarch64.txt
  requirements/x86_64.txt
Labels: release_note, auto-backport, v8.16.0, v9.0.0, v8.15.3

#2857 Fix broken link in CONFIG.md
  docs/CONFIG.md
Labels: auto-backport, v8.16.0, v9.0.0
