Repository elastic/connectors, pull requests merged in 2024-01, with the labels that each got.

#2021 Update Elasticsearch client to 8.11
  requirements/framework.txt
Labels: auto-backport, v8.13.0.0

#2019 Update aiohttp to latest
  requirements/framework.txt
  requirements/tests.txt
Labels: auto-backport, v8.13.0.0

#2016 Replace more places accessing Elasticsearch client directly with proxied calls
  connectors/cli/auth.py
  connectors/cli/connector.py
  connectors/cli/index.py
  connectors/cli/job.py
  connectors/es/client.py
  connectors/es/management_client.py
  connectors/es/settings.py
  connectors/es/sink.py
  connectors/kibana.py
  connectors/preflight_check.py
  connectors/services/job_cleanup.py
  tests/es/test_client.py
  tests/es/test_management_client.py
  tests/services/test_job_cleanup.py
  tests/sources/fixtures/fixture.py
  tests/test_connectors_cli.py
  tests/test_kibana.py
  tests/test_sink.py
Labels: auto-backport, v8.13.0.0

#2028 Make bin/connectors index without arguments output help
  connectors/connectors_cli.py
Labels: auto-backport, v8.13.0.0

#2029 Make clean_index method proceed on conflicts
  connectors/es/index.py
Labels: auto-backport, v8.13.0.0

#1982 Added new RCF `bucket` for GCS and ABS
  connectors/sources/azure_blob_storage.py
  connectors/sources/google_cloud_storage.py
  tests/sources/fixtures/azure_blob_storage/connector.json
  tests/sources/fixtures/google_cloud_storage/connector.json
  tests/sources/test_azure_blob_storage.py
  tests/sources/test_google_cloud_storage.py
Labels: auto-backport, v8.13.0.0

#1997 [GitHub] Fix scopes related issue
  connectors/sources/github.py
  tests/sources/fixtures/github/fixture.py
  tests/sources/test_github.py
Labels: auto-backport, team:external, github, v8.13.0.0

#2031 [CLI] Add documentation
  README.md
  docs/CLI.md
Labels: auto-backport, v8.12.0, v8.13.0.0

#2024 [Google Drive] Fix permission fetching bug for domain-wide delegation sync
  connectors/sources/google_drive.py
Labels: bug, auto-backport, v8.11.0, v8.12.0, v8.13.0, v8.13.0.0

#2023 Make mongodb work without admin privelege
  connectors/sources/mongo.py
  tests/sources/test_mongo.py
Labels: auto-backport, v8.12.1, v8.13.0.0

#2038 Remove automatically deleting indices for orphaned jobs
  connectors/services/job_cleanup.py
  tests/services/test_job_cleanup.py
Labels: bug, release_note, auto-backport, v8.12.0, v8.12.0.0, v8.10.5, v8.13.0.0, v8.11.4

#1947 Working Docker Compose Stack for Connectors
  .gitignore
  README.md
  connectors/connectors_cli.py
  scripts/stack/README.md
  scripts/stack/configure-connectors.sh
  scripts/stack/copy-config.sh
  scripts/stack/docker/docker-compose.yml
  scripts/stack/parse-params.sh
  scripts/stack/run-stack.sh
  scripts/stack/set-env.sh
  scripts/stack/stop-stack.sh
  scripts/stack/update-kibana-user-password.sh
  scripts/stack/view-connectors-logs.sh
  scripts/stack/wait-for-elasticsearch.sh
  scripts/stack/wait-for-kibana.sh
Labels: auto-backport, v8.12.0.0, v8.13.0.0

#2042 Raise an error if our ES client fails to execute a _search
  connectors/es/index.py
  tests/es/test_index.py
Labels: release_note, auto-backport, v8.12.0, v8.13.0, v8.13.0.0, v8.11.4

#2048 Revert Changes to Connectors CLI Config Loading and Use Separate Configuration for Stack Scripts
  connectors/connectors_cli.py
  scripts/stack/README.md
  scripts/stack/configure-connectors.sh
  scripts/stack/copy-config.sh
  scripts/stack/run-stack.sh
Labels: auto-backport, v8.12.0.0, v8.13.0.0

#2004 [Network Drive] [DLS] Fix precedence for Deny permissions
  connectors/sources/network_drive.py
  tests/sources/fixtures/network_drive/connector.json
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.12.0, v8.12.0.0, v8.12.1, v8.13.0.0

#2025 [ServiceNow] DLS documentation
  docs/document-level-security/SERVICENOW.md
Labels: auto-backport, v8.13.0.0

#2054 Bump VERSION to 8.11.5
  connectors/VERSION
Labels: v8.11.5

#2000 Introduce automated testing CLI
  scripts/testing/README.md
  scripts/testing/cli.py
  scripts/testing/docker-compose.yml
  scripts/testing/pull-connectors.sh
  scripts/testing/scenarios/clients/spo_automated_testing_site.json
  scripts/testing/scenarios/clients/spo_full_and_incremental_syncs.yml
  scripts/testing/startup_scipt.sh
  setup.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2049 give CTA if no connectors are configured
  connectors/preflight_check.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2041 [8.10] Remove automatically deleting indices for orphaned jobs (#2038)
  connectors/services/job_cleanup.py
  tests/services/test_job_cleanup.py
Labels: backport

#2055 [Salesforce] Add custom object support with different API Names
  connectors/sources/salesforce.py
Labels: auto-backport, team:external, salesforce, v8.13.0, v8.13.0.0

#2061 Update Vault paths in SPO automated test config to reflect new locations
  scripts/testing/scenarios/clients/spo_automated_testing_site.json
Labels: auto-backport, v8.13.0.0

#2040 [8.11] Remove automatically deleting indices for orphaned jobs (#2038)
  connectors/services/job_cleanup.py
  tests/services/test_job_cleanup.py
Labels: backport

#2045 Mark orphaned idle sync jobs as error
  connectors/protocol/connectors.py
  connectors/services/job_cleanup.py
  tests/protocol/test_connectors.py
  tests/services/test_job_cleanup.py
Labels: auto-backport, v8.12.1, v8.13.0.0

#2018 [MongoDB] Validate & Ensure consistency of enabling SSL
  connectors/sources/mongo.py
  tests/sources/test_mongo.py
Labels: auto-backport, team:external, v8.12.0, v8.12.0.0, v8.13.0.0

#2051 [CLI] Improve Connectors CLI's service type picker during prompted config; also some small fixes to the CLI docs
  connectors/connectors_cli.py
  docs/CLI.md
  requirements/framework.txt
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0.0

#2072 Bump version to 8.12.1
  connectors/VERSION
Labels: v8.12.1

#2059 [Docs] Update README.md for 8.12.0
  README.md
Labels: auto-backport, v8.12.0, v8.12.0.0, v8.13.0.0

#2071 [Setup] Add logging, when default architecture is set
  setup.py
Labels: auto-backport, v8.13.0.0

#2076 Replace usages of 'elastic_server' with 'sync_orchestrator'
  connectors/sync_job_runner.py
  tests/test_sink.py
  tests/test_sync_job_runner.py
Labels: auto-backport, tech-improvement, v8.13.0, v8.13.0.0

#2084 Bump elasticsearch and elasticsearch-transport to 8.12.0
  requirements/framework.txt
Labels: auto-backport, v8.12.1, v8.13.0.0

#2057 Support timestamp-based optimization
  connectors/es/sink.py
  connectors/sources/box.py
  connectors/sources/confluence.py
  connectors/sources/dropbox.py
  connectors/sources/google_cloud_storage.py
  connectors/sources/google_drive.py
  connectors/sources/jira.py
  connectors/sources/network_drive.py
  connectors/sources/onedrive.py
  connectors/sources/servicenow.py
  connectors/sources/sharepoint_server.py
  connectors/sources/zoom.py
  connectors/sync_job_runner.py
  tests/test_sync_job_runner.py
Labels: release_note, auto-backport, v8.13.0.0

#2086 Fix packaging
  connectors/utils.py
  setup.py
  tests/test_utils.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2088 Add faker dependency to tests.txt requirements file
  requirements/tests.txt
Labels: auto-backport, v8.12.0, v8.13.0.0

#2085 [Network Drive] Handle smb connection timeout
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: release_note, auto-backport, v8.13.0.0

#2063 Implement consistent retry policy when calling Elasticsearch
  config.yml
  connectors/config.py
  connectors/es/client.py
  connectors/es/management_client.py
  connectors/es/sink.py
  connectors/utils.py
  tests/es/test_client.py
  tests/es/test_management_client.py
  tests/test_sink.py
Labels: auto-backport, v8.13.0.0

#2093 Validate configurable fields every loop of job scheduling service
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: release_note, auto-backport, v8.13.0.0

#2091 Stop erroring CLI when using API key to authenticate
  connectors/cli/connector.py
  connectors/connectors_cli.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2097 [CI] Update 'connectors-nightly-dockers' to stop trying to install Docker
  .buildkite/publish_docker.sh
  catalog-info.yaml
Labels: auto-backport, v8.13.0.0

#2096 Treat inability to create mappings as warning instead of breaking error
  connectors/es/management_client.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2092 [CLI] API keys authentication
  connectors/cli/auth.py
  connectors/cli/connector.py
  connectors/cli/index.py
  connectors/connectors_cli.py
  docs/CLI.md
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0, v8.13.0.0

#2103 [CI] Update nightly CI pipelines to use the right branches
  catalog-info.yaml
Labels: auto-backport, v8.13.0.0
