Repository elastic/connectors, pull requests merged in 2024-08, with the labels that each got.

#2708 Sharepoint Server NTLM authentication support
  connectors/sources/sharepoint_server.py
  requirements/framework.txt
  tests/sources/fixtures/sharepoint_server/connector.json
  tests/sources/fixtures/sharepoint_server/fixture.py
  tests/sources/test_sharepoint_server.py
Labels: auto-backport, sharepoint, team:external, v8.16.0, v8.16.0.0

#2647 [MySQL] Add new field id_columns in sync rules to generate id and adding support for views
  connectors/sources/mysql.py
  tests/sources/test_mysql.py
Labels: release_note, auto-backport, v8.16.0.0

#2732 Improve test coverage for content_extraction.py
  tests/test_content_extraction.py
Labels: v8.16.0.0

#2726 replace flakey spec
  connectors/service_cli.py
  tests/test_service_cli.py
Labels: auto-backport, v8.16.0, v8.16.0.0

#2735 Add _id to failed bulk logs
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v8.16.0.0

#2717 [MSSQL] Fix serialization to parse time object
  connectors/source.py
  tests/sources/fixtures/mssql/fixture.py
Labels: release_note, auto-backport, team:external, mssql, v8.16.0, v8.16.0.0

#2731 [OneDrive] Add support for field mime-type
  connectors/sources/onedrive.py
  tests/sources/test_onedrive.py
Labels: release_note, auto-backport, v8.16.0.0

#2729 [MySQL] Add custom pagination to fix connector dies issue
  connectors/sources/mysql.py
  lib64
  tests/sources/test_mysql.py
Labels: release_note, mysql, auto-backport, team:external, v8.16.0.0

#2740 Bump msal to 1.30.0
  requirements/framework.txt
Labels: auto-backport, v8.16.0.0, v8.15.1, v8.14.4

#2711 [Github] Fix Rate limit error
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: release_note, auto-backport, team:external, github, v8.16.0, v8.16.0.0, v8.15.0.1

#2718 [Dropbox] Fix fetching documents from team shared folders
  connectors/sources/dropbox.py
  tests/sources/fixtures/dropbox/fixture.py
  tests/sources/test_dropbox.py
Labels: release_note, auto-backport, team:external, dropbox, v8.16.0, v8.16.0.0

#2734 Make connectors work with python 3.10 and 3.11
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  .buildkite/run_functional_test.sh
  .buildkite/run_linter.sh
  .buildkite/run_tests.sh
  Dockerfile
  Dockerfile.ftest
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  Makefile
  requirements/framework.txt
  requirements/ftest.txt
  scripts/stack/README.md
  tests/sources/fixtures/oracle/fixture.py
Labels: auto-backport, v8.16.0.0

#2748 Revert default python to python3
  Makefile
Labels: auto-backport, v8.16.0.0

#2747 Bump elasticsearch and elastic-transport packages to 8.15
  requirements/framework.txt
Labels: auto-backport, v8.16.0.0

#2754 Remove `lib64` symlink from repo, add it to gitignore
  .gitignore
  lib64
Labels: auto-backport, v8.16.0.0

#2763 Replace python setup.py develop with pip install --editable .
  Makefile
  pytest.ini
Labels: auto-backport, v8.16.0.0

#2766 Revert "Replace python setup.py develop with pip install --editable ."
  Makefile
  pytest.ini
Labels: auto-backport, v8.16.0.0

#2771 pip is now in .venv/bin
  Dockerfile.ftest
  Dockerfile.ftest.wolfi
  Makefile
  tests/sources/fixtures/box/docker-compose.yml
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/graphql/docker-compose.yml
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/zoom/docker-compose.yml
Labels: auto-backport, v8.16.0

#2772 Comment out release-manager
  .buildkite/publish/dra/publish-daily-release-artifact.sh
Labels: auto-backport, v8.16.0

#2769 Bump `aiohttp` version to 3.10.4
  requirements/framework.txt
Labels: auto-backport, v8.16.0, v8.16.0.0

#2764 Document release process changes with DRA
  .gitignore
  docs/RELEASING.md
Labels: v8.16.0

#2778 Use .venv/bin for sdist and pip-licenses
  Makefile
Labels: auto-backport, v8.16.0

#2781 rename VENV_DIR->VIRTUAL_ENV
  tests/ftest.sh
Labels: auto-backport, v8.16.0

#2765 add docker images to dra
  .buildkite/nightly_docker.yml
  .buildkite/pipeline.yml
  .buildkite/publish/build-multiarch-docker.sh
  .buildkite/publish/dra/init_dra_publishing.sh
  .buildkite/publish/dra/publish-daily-release-artifact.sh
  .buildkite/publish/publish-common.sh
  .buildkite/publish/push-docker.sh
  .buildkite/publish/test-docker.sh
  .buildkite/publish_docker.sh
  .buildkite/release-pipeline.yml
  .buildkite/run_functional_test.sh
  catalog-info.yaml
Labels: auto-backport, v8.16.0, v8.16.0.0

#2782 Fix docker test, and add label hack for running packaging from PRs
  .buildkite/pipeline.yml
  .buildkite/publish/dra/init_dra_publishing.sh
  .buildkite/publish/test-docker.sh
  catalog-info.yaml
Labels: auto-backport, v8.16.0, ci:packaging

#2784 Ensure required python libs are installed before generating csv
  .buildkite/publish/dra/init_dra_publishing.sh
Labels: auto-backport, v8.16.0

#2783 Change back to amd64 instead of x86_64
  .buildkite/publish/dra/init_dra_publishing.sh
Labels: auto-backport, v8.16.0, ci:packaging

#2785 Clean was a mistake
  .buildkite/publish/dra/init_dra_publishing.sh
Labels: auto-backport, v8.16.0, ci:packaging

#2786 Make job cleanup service not sleep if it's not running any more
  connectors/services/job_cleanup.py
Labels: auto-backport, v8.16.0

#2790 Fix the on-commit pipeline ftests
  .buildkite/pipeline.yml
Labels: auto-backport, v8.16.0

#2762 [SPO] Add support of `sites.selected` permission
  connectors/sources/sharepoint_online.py
  tests/sources/fixtures/sharepoint_online/fixture.py
  tests/sources/test_sharepoint_online.py
Labels: release_note, auto-backport, team:external, sharepoint_online, v8.16.0, v8.16.0.0

#2791 Post-process deps-csv to meet DRA needs
  Makefile
  scripts/deps-csv.py
Labels: auto-backport, v8.16.0, ci:packaging

#2733 [Confluence] Allow to ingest space separately
  connectors/sources/confluence.py
  tests/sources/fixtures/confluence/fixture.py
  tests/sources/test_confluence.py
Labels: confluence, team:external, v8.16.0
