Repository elastic/connectors, pull requests merged in 2024-03, with the labels that each got.

#2223 [Network Drive] Fix connector hanging the framework
  connectors/sources/network_drive.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2218 Reduce lag in Outlook connector
  connectors/sources/outlook.py
  tests/sources/test_outlook.py
Labels: auto-backport, team:external, outlook, v8.13.0.0, v8.14.0.0

#2123 Code for Redis SSL
  connectors/sources/redis.py
  docs/reference/redis.md
  tests/sources/fixtures/redis/connector.json
  tests/sources/test_redis.py
Labels: auto-backport, v8.13.0.0

#2228 Fix problem with cancel jobs action using closed client
  connectors/cli/job.py
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2224 [Network Drive] Allow connector to work with non-default ports
  connectors/sources/network_drive.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2233 Revert "Generate API keys when running native connector syncs #2188"
  connectors/es/management_client.py
  connectors/protocol/connectors.py
  connectors/services/job_execution.py
  connectors/utils.py
  tests/es/test_management_client.py
  tests/services/test_job_execution.py
  tests/test_utils.py
Labels: auto-backport, v8.13.0, v8.14.0, v8.14.0.0

#2230 Fix table/db names not being escaped for MySQL connector
  connectors/sources/mysql.py
  tests/sources/test_mysql.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2236 [CLI] Add connector name support
  connectors/cli/connector.py
  connectors/connectors_cli.py
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0, v8.14.0.0

#2243 Avoid ftest perf8 race condition
  tests/ftest.sh
Labels: auto-backport, v8.13.0, v8.14.0.0, v8.12.3

#2240 Catch unauthorized errors during sync
  connectors/sync_job_runner.py
  tests/test_sync_job_runner.py
Labels: auto-backport, v8.13.0, v8.14.0, v8.14.0.0

#2244 [CLI] Index list - show all indices
  connectors/es/management_client.py
  tests/es/test_management_client.py
Labels: release_note, auto-backport, v8.13.0, v8.14.0, v8.14.0.0

#2242 [PostgreSQL] Add custom pagination to reduce memory consumption
  connectors/sources/postgresql.py
Labels: auto-backport, v8.14.0.0

#2249 change some logging
  connectors/es/client.py
  connectors/preflight_check.py
  connectors/sources/mongo.py
  tests/es/test_client.py
Labels: auto-backport, v8.14.0.0

#2252 [CLI] Create and store API keys for native connectors in CLI
  connectors/cli/connector.py
  connectors/connectors_cli.py
  connectors/es/management_client.py
  tests/es/test_management_client.py
  tests/test_connectors_cli.py
Labels: auto-backport, v8.13.0, v8.14.0, v8.14.0.0

#2247 Automatically update content index settings and mappings
  connectors/es/management_client.py
  connectors/es/sink.py
  connectors/sync_job_runner.py
  tests/es/test_management_client.py
  tests/test_sink.py
Labels: release_note, auto-backport, v8.13.0, v8.14.0, v8.14.0.0

#2259 Fix logs for incorrect configuration values in Redis
  connectors/sources/redis.py
  tests/sources/test_redis.py
Labels: auto-backport, v8.14.0.0

#2260 [8.13] [Redis] Log correct message when cannot connect to Redis (#2259)
  connectors/sources/redis.py
  tests/sources/test_redis.py
Labels: backport

#2202 [Network Drive]Add local extraction feature
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.14.0.0

#2261 Clarify Elasticsearch Client Log Message While Waiting for Connection
  connectors/es/client.py
Labels: auto-backport, v8.13.0.0, v8.14.0.0

#2231 Add Advanced Sync Rules for Notion connector
  connectors/sources/notion.py
  docs/sync-rules/NOTION.md
  tests/sources/test_notion.py
Labels: auto-backport, notion, v8.14.0.0

#2270 log filtering validation result at info
  connectors/filtering/validation.py
Labels: v8.13.0, v8.14.0

#2273 Wait for sync jobs to finish before closing clients
  connectors/services/job_execution.py
  connectors/utils.py
Labels: auto-backport, v8.14.0.0, v8.13.1

#2182 Fix Box and Network Drive ftests
  connectors/services/job_scheduling.py
  connectors/sources/network_drive.py
  tests/services/test_job_scheduling.py
  tests/sources/fixtures/box/fixture.py
  tests/sources/fixtures/network_drive/fixture.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.14.0.0

#2276 Eliminate Duplicate Buildkite Builds on Branches and PRs
  .buildkite/pull-requests.json
  catalog-info.yaml
Labels: auto-backport, v8.12.0.0, v8.13.0.0, v8.14.0.0

#2281 [Sink] Use constant for END_DOCS and FETCH_ERROR
  connectors/es/sink.py
Labels: auto-backport, v8.14.0.0

#2282 [Sink] Improve wording
  connectors/es/sink.py
Labels: auto-backport, v8.14.0.0

#2283 [Sink] Fix typos
  connectors/es/sink.py
Labels: auto-backport, v8.14.0.0

#2284 [8.12] Make MemQueue used in sync configurable via config options (#2079)
  config.yml
  connectors/config.py
  connectors/es/sink.py
Labels: backport

#2268 [GitHub] Do not add ACL list for objects from public repos
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v8.13.0, v8.14.0.0

#2287 Check both repo_type and use_document_level_security for dls_enabled
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: v8.14.0, v8.14.0.0

#2291 Add connector name param to automated test runner
  scripts/testing/README.md
  scripts/testing/cli.py
  scripts/testing/scenarios/clients/spo_full_and_incremental_syncs.yml
Labels: auto-backport, v8.14.0.0

#2272 Update GitHub RCF to support GitHub App authentication
  connectors/sources/github.py
Labels: v8.14.0, v8.14.0.0

#2280 gitignore config.yml
  .gitignore
  Makefile
  config.yml.example
  docs/CONFIG.md
  docs/CONTRIBUTING.md
  docs/DEVELOPING.md
  docs/DOCKER.md
  scripts/stack/README.md
Labels: auto-backport, v8.14.0, v8.14.0.0, v8.13.1

#2294 [ABS] Fix typos
  connectors/sources/azure_blob_storage.py
Labels: auto-backport, v8.14.0.0

#2296 [Confluence] Fix typo, split long comments and add two log lines
  connectors/sources/confluence.py
Labels: auto-backport, v8.14.0.0

#2293 [Sink] rename get_mb_size to get_mib_size
  connectors/es/sink.py
Labels: auto-backport, v8.14.0.0

#2300 Bump VERSION to 8.13.1.0
  connectors/VERSION
Labels: v8.13.1

#2117 [Framework] Allow bulk operations result logging
  config.yml.example
  connectors/config.py
  connectors/es/sink.py
  connectors/sync_job_runner.py
  tests/test_sink.py
Labels: auto-backport, v8.13.0.0

#2302 [Box] Improve logging, test naming and variable naming
  connectors/sources/box.py
  tests/sources/test_box.py
Labels: auto-backport, v8.14.0.0

#2286 [Network Drive] Change traversal strategy to ingest as you go instead of pre-fetching the whole tree
  connectors/sources/network_drive.py
  tests/sources/test_network_drive.py
Labels: auto-backport, v8.14.0.0

#2311 Add a buildkite status badge to the README
  README.md
Labels: auto-backport, v8.14.0.0
