Repository elastic/connectors, pull requests merged in 2024-12, with the labels that each got.

#3013 Stop providing mappings/settings for data indices
  connectors/cli/connector.py
  connectors/connectors_cli.py
  connectors/es/__init__.py
  connectors/es/management_client.py
  connectors/es/settings.py
  connectors/es/sink.py
  connectors/kibana.py
  tests/es/test_management_client.py
  tests/es/test_settings.py
  tests/test_sink.py
Labels: release_note, auto-backport, v9.0.0

#3014 Send one heartbeat on scheduling service startup anyway
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: auto-backport, v9.0.0

#3015 Stringify doc[id] field
  connectors/es/sink.py
  tests/test_sink.py
Labels: auto-backport, v9.0.0, v8.17.0

#3020 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bed0cbf (#3006)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3031 also cast doc_id to str
  connectors/es/sink.py
  connectors/utils.py
  tests/test_sink.py
Labels: release_note, auto-backport, v9.0.0, v8.16.2, v8.17.1, v8.18.0

#3040 Update aiohttp to latest
  requirements/framework.txt
Labels: auto-backport, v9.0.0, v8.17.0, v8.16.2, v8.18

#3036 [8.16] also cast doc_id to str (#3031)
  connectors/es/sink.py
  connectors/utils.py
  tests/test_sink.py
Labels: backport

#3043 Manually bump dockerfiles in 8.17
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: auto-backport, v9.0.0

#3045 Remove 8.15 maintenance
  catalog-info.yaml
  docs/RELEASING.md
Labels: auto-backport, v9.0.0

#3048 build(release): Bump 8.16.2 -> 8.16.3
  connectors/VERSION
Labels: v8.16.2

#3046 [8.17] Update aiohttp to latest (#3040)
  requirements/framework.txt
Labels: backport

#3047 [8.16] Update aiohttp to latest (#3040)
  requirements/framework.txt
Labels: backport

#3044 Fix mysql advanced sync rule execute error
  connectors/sources/mysql.py
Labels: auto-backport, v9.0.0

#3025 [8.x] Allow Insecure HTTPS (#2913)
  config.yml.example
  connectors/config.py
  connectors/es/client.py
  docs/DOCKER.md
Labels: backport

#3037 [8.x] Update elasticsearch client to 8.17 (#3033)
  NOTICE.txt
  requirements/framework.txt
Labels: backport

#3059 Set connector status to CONNECTED after successful validation and ping
  connectors/protocol/connectors.py
  connectors/services/job_scheduling.py
  tests/commons.py
  tests/services/test_job_scheduling.py
Labels: auto-backport, v9.0.0, v8.17.1, v8.18.0, v8.16.3
