Repository elastic/connectors, pull requests merged in 2025-07, with the labels that each got.

#3504 Update CONTRIBUTING.md
  NOTICE.txt
  docs/CONTRIBUTING.md
Labels: auto-backport, v9.2.0

#3506 [8.19] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3508 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3505 [9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 61d6ceb (#3496)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3497 Remove MySQLQueries class and inline its methods
  NOTICE.txt
  connectors/sources/mysql.py
Labels: auto-backport, v9.1.0, v8.17.6, v9.0.3, v8.18.3, v8.19.1, v9.2.0

#3498 Speed up column name fetching
  connectors/sources/mysql.py
Labels: auto-backport, v9.1.0, v8.17.6, v9.0.3, v8.18.3, v8.19.3, v9.2.0

#3554 Bump aiohttp to 3.12.14
  NOTICE.txt
  requirements/framework.txt
Labels: auto-backport, v9.2.0, v9.0.5, v8.18.5, v8.17.10

#3558 [9.1] Bump aiohttp to 3.12.14 (#3554)
  NOTICE.txt
  requirements/framework.txt
Labels: backport

#3546 test: Simplify functional test Dockerfile setup
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  Dockerfile.ftest
  Dockerfile.ftest.wolfi
  Makefile
  tests/Dockerfile.ftest
  tests/ftest.sh
Labels: auto-backport, v9.0.0, v8.17.0, v8.18.0, v9.1.0, v9.2.0

#3559 [ServiceNow] Paginate API calls when we have advanced sync rules
  connectors/sources/servicenow.py
  tests/sources/test_servicenow.py
Labels: auto-backport, v9.2.0, v9.0.5, v8.18.5, v8.17.10, v9.1.1
