Repository elastic/connectors, pull requests merged in 2025-08, with the labels that each got.

#2671 Port ErrorMonitor class from ruby connectors
  NOTICE.txt
  config.yml.example
  connectors/config.py
  connectors/es/client.py
  connectors/es/sink.py
  connectors/source.py
  connectors/utils.py
  tests/test_sink.py
  tests/test_utils.py
Labels: auto-backport, v9.0.0, v8.17.0, v8.18.0, v9.1.0, v8.19.0, v9.2.0

#3629 Handle KeyError in the ES sink.py
  connectors/es/sink.py
Labels: auto-backport, v8.19.3, v9.2.0, 8.17.10, v8.18.6, v9.1.3, v9.0.6

#3613 Salesforce and Google Drive mappings
  NOTICE.txt
  connectors/agent/mappings/google_drive.json
  connectors/agent/mappings/salesforce.json
  connectors/agent/pipelines/googledrive_pipeline.json
  connectors/agent/pipelines/salesforce_pipeline.json
Labels: auto-backport, v9.2.0

#3644 8.18.7 release bump
  NOTICE.txt
  connectors/VERSION
Labels: v8.18.6
