Repository elastic/connectors, pull requests merged in 2025-06, with the labels that each got.

#3441 [8.18] Make job_scheduling service run schedule in a task pool (#3335)
  config.yml.example
  connectors/config.py
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: backport

#3431 bump for 9.0.2 release
  NOTICE.txt
  connectors/VERSION
Labels: v9.0.3

#3460 [8.19] Fix Confluence connector swallowing all errors (#3384)
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: backport

#3459 Add support for default UUID type 4 serialization
  connectors/sources/mongo.py
  tests/sources/fixtures/mongodb/fixture.py
  tests/sources/test_mongo.py
Labels: auto-backport, v9.0.0, v9.1.0, v8.19.0, v8.18.3

#3468 Refactor MongoDB connector `get_client` method to not produce unexpected side-effects
  connectors/sources/mongo.py
  tests/sources/test_mongo.py
Labels: auto-backport, v9.0.0, v9.1.0, v8.19.0, v8.18.3

#3480 Bump requests to 2.32.4
  NOTICE.txt
  requirements/framework.txt
  requirements/tests.txt
Labels: auto-backport, v9.0.0, v8.17, v9.1.0, v8.18.3, v8.19.1

#3485 [8.17] Bump requests to 2.32.4 (#3480)
  NOTICE.txt
  requirements/framework.txt
  requirements/tests.txt
Labels: backport

#3494 [9.1] Update CI files for 9.1 branch
  .buildkite/pipeline.yml
  NOTICE.txt
  catalog-info.yaml
Labels: v9.1.0
