Repository elastic/connectors, pull requests merged in 2025-03, with the labels that each got.

#3244 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3245 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3243 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to f56d29e (#3241)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3238 Improve PostgreSQL primary key detection with enhanced SQL query
  connectors/sources/postgresql.py
  tests/sources/test_postgresql.py
Labels: auto-backport, v9.0.0, v8.17.1, v8.18.0, v9.1.0

#3251 Drop some internal docs as they're moved elsewhere
  docs/INTERNAL.md
  docs/RELEASING.md
Labels: auto-backport, v9.1.0

#3284 [9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3285 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3286 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3288 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to bad9ad1 (#3283)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3290 Fix ABS concurrent download configuration
  NOTICE.txt
  connectors/sources/azure_blob_storage.py
Labels: auto-backport, v9.0.0, v8.17.0, v8.18.0, v9.1.0, v8.19.0

#3312 Remove make release command
  Makefile
Labels: auto-backport, v9.1.0

#3324 prep for 9.0.0 release
  .buildkite/publish/publish-common.sh
  NOTICE.txt
Labels: v9.0.0

#3326 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3327 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3329 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3328 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 3135203 (#3319)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#2816 [Github] Update Logs Private Repository Sync Errors
  connectors/sources/github.py
Labels: github

#3334 Run renovate only on weekends
  renovate.json
Labels: auto-backport, v9.1.0
