Repository elastic/connectors, pull requests merged in 2025-05, with the labels that each got.

#3418 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3417 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3416 [8.19] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3415 [9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to cfb2947 (#3414)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3425 Leverage slack integration
  NOTICE.txt
  catalog-info.yaml
Labels: auto-backport, v9.1.0

#3427 try adding message
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  .buildkite/release-pipeline.yml
Labels: auto-backport, v9.1.0

#3428 backport slack configs
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  .buildkite/release-pipeline.yml
  NOTICE.txt
Labels: auto-backport, v8.18, v8.17, v8.19.0

#3438 Use type for access control list
  connectors/sources/salesforce.py
Labels: auto-backport, v9.1.0
