Repository elastic/connectors, pull requests merged in 2025-04, with the labels that each got.

#3335 Make job_scheduling service run schedule in a task pool
  NOTICE.txt
  config.yml.example
  connectors/config.py
  connectors/services/job_scheduling.py
  tests/services/test_job_scheduling.py
Labels: auto-backport, v9.0.0, v9.1.0, v8.19.0, v8.17.4, v8.18.1

#3340 [9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3341 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3342 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3343 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3344 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 485e1ad (#3339)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3353 [9.0] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3356 Fix log line for when too many jobs are attempted to be scheduled
  connectors/services/job_scheduling.py
Labels: auto-backport, v9.0.0, v9.1.0

#3349 Bump version to 8.17.6
  connectors/VERSION
Labels: v8.17.5

#3367 handling ELASTIC_PASSWORD when running run-stack.sh
  scripts/stack/copy-config.sh
  scripts/stack/wait-for-elasticsearch.sh
Labels: auto-backport, v9.1.0

#3369 Make Job Scheduling service emit debug log instead of info
  NOTICE.txt
  connectors/services/job_scheduling.py
Labels: auto-backport, v9.0.0, v9.1.0, v8.19.0, v8.18.1, v8.17.5

#3365 [Post 8.18 Release] bump client to 8.18
  NOTICE.txt
  requirements/framework.txt
Labels: auto-backport, v9.1.0

#3358 Attempt to retry 403 errors when they are actually secondary throttling limit
  NOTICE.txt
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: auto-backport, v9.0.0, v9.1.0, v8.19.0, v8.18.1, v8.17.5

#3380 [9.0] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)
  NOTICE.txt
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: backport

#3382 [8.18] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)
  NOTICE.txt
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: backport

#3383 [8.17] Attempt to retry 403 errors when they are actually secondary throttling limit (#3358)
  NOTICE.txt
  connectors/sources/github.py
  tests/sources/test_github.py
Labels: backport

#3355 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0863e59 (#3350)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3379 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 497ea22 (#3374)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
  NOTICE.txt
Labels: backport

#3373 [8.x] Make Job Scheduling service emit debug log instead of info (#3369)
  connectors/services/job_scheduling.py
Labels: backport

#3385 [8.x] 8.18 Release Activities for DRA / Backport (#3166)
  .backportrc.json
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: backport

#3389 [8.19] Rename 8.x to 8.19 (#3387)
  .backportrc.json
  .buildkite/pipeline.yml
  NOTICE.txt
  catalog-info.yaml
Labels: backport

#3392 Pin Setuptools to 79.0.1
  Makefile
Labels: auto-backport, v9.1.0, v8.19.0, v8.18.1, v8.17.6, v9.0.1

#3384 Fix Confluence connector swallowing all errors
  connectors/sources/confluence.py
  tests/sources/test_confluence.py
Labels: auto-backport, v9.0.0, v9.1.0
