Repository elastic/connectors, pull requests merged in 2025-02, with the labels that each got.

#3177 SharePoint Online Connector: Added credentials.close() call to _fetch_token() method
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: bug, auto-backport, v9.0.0, v9.1.0

#3180 [8.x] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#3181 [8.18] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#3183 [8.16] SharePoint Online Connector: Added credentials.close() call to _fetch_token() method (#3177)
  connectors/sources/sharepoint_online.py
  tests/sources/test_sharepoint_online.py
Labels: backport

#3178 [Framework] Correctly handle soft deleted connectors
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v9.0.0, v9.1.0

#3190 [Makefile] Improvements to python selection and requirement changes
  Makefile
Labels: auto-backport, v9.1.0

#3189 Adding warning filter to suppress GA warning from ES Python client
  connectors/es/__init__.py
Labels: auto-backport, v9.0.0, v8.18.0, v9.1.0

#3192 [8.18] Adding warning filter to suppress GA warning from ES Python client (#3189)
  connectors/es/__init__.py
Labels: backport

#3198 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3199 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to ff16db3 (#3194)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3202 Add v8.19.0 label to renovate.json
  NOTICE.txt
  renovate.json
Labels: auto-backport, v9.1.0

#3205 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3206 [8.18] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3208 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 8d32370 (#3203)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3221 Update README.md for 9.0
  README.md
Labels: documentation, auto-backport, v9.0.0, v9.1.0

#3223 switch version qualifier to `rc1`
  .buildkite/publish/publish-common.sh
Labels: v9.0.0

#3236 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3234 [8.x] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3237 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 0bdec4b (#3227)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport
