Repository elastic/connectors, pull requests merged in 2025-01, with the labels that each got.

#3071 Update NOTICE.txt
  NOTICE.txt
Labels: auto-backport, v9.0.0

#3079 Make config.yml an order dependency
  Makefile
Labels: auto-backport, v9.0.0, v8.17.1, v8.18.0, v8.16.3

#3076 Make lint step run autoformat and commit changes for you + minor refactoring
  .buildkite/pipeline.yml
  .buildkite/run_linter.sh
  .buildkite/run_notice_check.sh
  .buildkite/shared.sh
Labels: v9.0.0

#3086 Use actual PyPi version of elastic-agent-client
  requirements/agent.txt
Labels: auto-backport, v9.0.0, v8.18.0

#3089 Minor CI lint/notice steps improvement
  .buildkite/run_linter.sh
  .buildkite/run_notice_check.sh
  .buildkite/shared.sh
Labels: auto-backport, v9.0.0

#3064 Add authentication via Entra with a certificate
  NOTICE.txt
  connectors/sources/sharepoint_online.py
  requirements/framework.txt
  tests/sources/fixtures/sharepoint_online/connector.json
  tests/sources/test_sharepoint_online.py
Labels: auto-backport, v9.0.0, v8.17.1, v8.18.0, v8.16.3

#3095 Avoid git commands when running against a fork
  .buildkite/run_linter.sh
  .buildkite/run_notice_check.sh
  .buildkite/shared.sh
Labels: auto-backport, v9.0.0

#3098 Update NOTICE.txt
  NOTICE.txt
Labels: auto-backport, v9.0.0

#3101 DRA release pipeline, pass qualifier to release cli
  .buildkite/publish/dra/publish-daily-release-artifact.sh
Labels: auto-backport, v9.0.0, v8.18.0

#3099 Fix CI considering every change a fork
  .buildkite/run_notice_check.sh
  .buildkite/shared.sh
Labels: auto-backport, v9.0.0

#3104 Auto-backport Renovate PRs
  .backportrc.json
  renovate.json
Labels: auto-backport, v9.0.0

#3105 Revert "DRA release pipeline, pass qualifier to release cli"
  .buildkite/publish/dra/publish-daily-release-artifact.sh
Labels: auto-backport, v9.0.0

#3109 Fix autofixing in CI
  .buildkite/run_linter.sh
  .buildkite/run_notice_check.sh
Labels: auto-backport, v9.0.0

#3112 [8.16] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3111 [8.17] Update docker.elastic.co/wolfi/python:3.11-dev Docker digest to 4ce83a8 (#3108)
  Dockerfile.ftest.wolfi
  Dockerfile.wolfi
Labels: backport

#3114 Update docs
  docs/CLI.md
  docs/DEVELOPING.md
  scripts/testing/README.md
Labels: auto-backport, v8.16.0, v9.0.0, v8.17.0, v8.18.0

#3113 Add step to update Renovate config to release docs
  .backportrc.json
  docs/RELEASING.md
Labels: auto-backport, v9.0.0

#3090 Remove ' ' as a configured Confluence space when there's a trailing comma
  connectors/source.py
  tests/test_source.py
Labels: auto-backport, v9.0.0

#3077 [Agent] Don't auto-create connector doc if connector was deleted
  Dockerfile.agent
  connectors/agent/connector_record_manager.py
  connectors/es/index.py
  connectors/protocol/connectors.py
  tests/protocol/test_connectors.py
Labels: auto-backport, v9.0.0

#3119 Enable basic DRA qualifiers
  .buildkite/publish/dra/init_dra_publishing.sh
  .buildkite/publish/dra/publish-daily-release-artifact.sh
  docs/RELEASING.md
Labels: auto-backport, v9.0.0

#3123 Fix SNAPSHOT workflow to not have VERSION_QUALIFIER
  .buildkite/publish/dra/publish-daily-release-artifact.sh
  docs/RELEASING.md
Labels: auto-backport, v9.0.0

#3124 version qualifier fixes
  .buildkite/publish/dra/publish-daily-release-artifact.sh
Labels: auto-backport, v9.0.0

#3063 Switch Dockerfile image to wolfi and add pipeline for vulnerability scanning
  .buildkite/pipeline.yml
  Dockerfile
  Dockerfile.ftest
Labels: release_note, v8.18.0

#3129 Update renovate labels
  renovate.json
Labels: auto-backport, v9.0.0

#3084 Bump 8.16.3 -> 8.16.4
  connectors/VERSION
Labels: v8.16.3

#3150 Update elastic-agent-client to 0.0.1dev2
  NOTICE.txt
  requirements/agent.txt
Labels: auto-backport, v9.0.0

#3110 Updating ESApi class methods to use ES client calls instead of temporary wrapper methods
  NOTICE.txt
  connectors/es/index.py
  requirements/framework.txt
  tests/es/test_index.py
Labels: auto-backport, v9.0.0, v8.17.1, v8.18.0

#3134 Add pagerduty service link
  catalog-info.yaml
Labels: auto-backport, v9.0.0

#3159 [8.x] Updating ESApi class methods to use ES client calls instead of temporary wrapper methods (#3110)
  NOTICE.txt
  connectors/es/index.py
  connectors/protocol/connectors.py
  requirements/framework.txt
  tests/es/test_index.py
Labels: backport

#3162 Add hardcoded qualifier
  .buildkite/publish/publish-common.sh
Labels: auto-backport, v9.0.0

#3166 8.18 Release Activities for DRA / Backport
  .backportrc.json
  .buildkite/pipeline.yml
  catalog-info.yaml
Labels: auto-backport, v9.0.0

#3165 Bumping main to 9.1
  .backportrc.json
  .buildkite/pipeline.yml
  .buildkite/publish/publish-common.sh
  NOTICE.txt
  catalog-info.yaml
  connectors/VERSION
  renovate.json
Labels: auto-backport, v9.0.0

#3170 Fix to ESApi connector_sync_job_update_stats() to ensure undefined metadata passed as {} when undefined
  connectors/es/index.py
  tests/es/test_index.py
Labels: bug, auto-backport, v9.0.0, v8.18.0, v9.1.0, v8.19.0
