Repository elastic/connectors, pull requests merged in 2025-09, with the labels that each got.

#3657 [8.19] ci: improve ftest ES DRA fetching (#3651)
  tests/ftest.sh
Labels: backport

#3679 [8.18] [Salesforce] optimize field validation to reduce API calls (#3668)
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: backport

#3680 [8.17] [Salesforce] optimize field validation to reduce API calls (#3668)
  connectors/sources/salesforce.py
  tests/sources/test_salesforce.py
Labels: backport

#3694 Pin Oracle DB version for ftest to 23.8.0.0
  NOTICE.txt
  tests/sources/fixtures/oracle/docker-compose.yml
Labels: auto-backport, v9.2.0

#3701 Define pyproject.toml
  .buildkite/publish/dra/init_dra_publishing.sh
  .ruff.toml
  MANIFEST.in
  Makefile
  NOTICE.txt
  docs/DEVELOPING.md
  pyproject.toml
  requirements/agent.txt
  scripts/__init__.py
  setup.py
  tests/__init__.py
  tests/fixtures/config.yml
  tests/fixtures/config_2.yml
  tests/fixtures/config_https.yml
  tests/fixtures/config_mem.yml
  tests/ftest.sh
  tests/sources/fixtures/box/docker-compose.yml
  tests/sources/fixtures/confluence/docker-compose.yml
  tests/sources/fixtures/dropbox/docker-compose.yml
  tests/sources/fixtures/github/docker-compose.yml
  tests/sources/fixtures/google_cloud_storage/docker-compose.yml
  tests/sources/fixtures/google_drive/docker-compose.yml
  tests/sources/fixtures/graphql/docker-compose.yml
  tests/sources/fixtures/jira/docker-compose.yml
  tests/sources/fixtures/microsoft_teams/docker-compose.yml
  tests/sources/fixtures/notion/docker-compose.yml
  tests/sources/fixtures/onedrive/docker-compose.yml
  tests/sources/fixtures/salesforce/docker-compose.yml
  tests/sources/fixtures/sandfly/docker-compose.yml
  tests/sources/fixtures/servicenow/docker-compose.yml
  tests/sources/fixtures/sharepoint_online/docker-compose.yml
  tests/sources/fixtures/sharepoint_server/docker-compose.yml
  tests/sources/fixtures/zoom/docker-compose.yml
  tests/test_source.py
Labels: auto-backport, v9.2.0

#3722 Add sandfly to nightly CI
  .buildkite/nightly_steps.yml
  .buildkite/pipeline.yml
  connectors/sources/sandfly.py
Labels: auto-backport, v9.2.0

#3710 Update Jira API
  connectors/sources/jira.py
  tests/sources/fixtures/jira/fixture.py
  tests/sources/test_jira.py
Labels: release_note, auto-backport, v9.2.0, v9.1.5, v8.18.8, v8.19.5, v9.0.8

#3735 Update .backportrc.json - remove 8.17
  .backportrc.json
Labels: auto-backport, v9.2.0
